### ISSUE TITLE
Crashing simulation when positioning mobileHost at the left upper edge

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#100]
When positioning a mobileHost by setting initialX and initialY both to "0m". Now moving the mobile host with an angle of 270deg(linearMobility) downwards and up again, while reaching the left upper edge again the simulation crashes. Happens with Linear- as well as MassMobility. My constraint area is (0,0,0) to (1000,1000,0). I've only experienced this bug on the left upper edge, when I try doing this at the right end of the constraint area everything works fine.

output: /bin/sh: line 1: 3654 Segmentation fault /home/x/x/x/x/x -c OneWHost -l /home/x/x/libs/inet/inet -n /home/x/x/simulations/x";"/home/x/x/src/x";"/home/x/x/libs/inet/src
make: **\* [Run_main] Error 139

But it's not all the time a segmentation fault, it changes! Doing the same simulation multiple times the error messages were "segmentation fault", "illegal instruction" as well as "bus error".
Additional Information  Error happens also if setting one of the two parameters initialX or initalY to "0m" and the other one "1m" as well as both set to "1m".

from: http://dev.omnetpp.org/bugs/view.php?id=609

**Comment by ZoltanBojthe** [comment]
can not be reproduced in inet 3.99
