### ISSUE TITLE
Periodic Gate + PriorityScheduler ERROR

### ISSUE THREAD

**Issue by GOAguiar99** [inet-framework/inet#1003]
Hello!

I'm implementing a different pending queue in the IEEE80211 module. Below is the new pending queue design:
![image](https://github.com/user-attachments/assets/50147d9f-9d4f-46da-afb8-1488610b24e0)

The issue is that when a gate is closed, the scheduler still tries to schedule a packet, resulting in an error. Is this the expected behavior? Do you have any suggestions for what I could change to resolve this?

![image](https://github.com/user-attachments/assets/becb5304-a9c6-4f4e-81e5-ef136cdf900f)

Here is the relevant part of the PriorityScheduler.cc code:
`int PriorityScheduler::schedulePacket()
{
    for (size_t i = 0; i < providers.size(); i++) {
        int inputIndex = getInputGateIndex(i);
        if (inputIndex == inProgressGateIndex || providers[inputIndex]->canPullSomePacket(inputGates[inputIndex]->getPathStartGate()))
            return inputIndex;
    }
    return -1;
}`

**Comment by levy** [comment]
The scheduler should not try to pull a packet through a gate which is closed. Actually, the call to canPullSomePacket makes sure that there is a packet which can be pulled. When a gate is closed, canPullSomePacket supposed to return false independently of whether the queue contains packets or not. So your design should work the way you expect.

**Comment by GOAguiar99** [comment]
I appreciate your reply, @levy . Unfortunately, I need to have this working by next Monday, as it’s part of a project for my master’s class. Could you help me resolve this issue or at least point me to where the bug might be occurring?

**Comment by levy** [comment]
Please attach a minimal example, preferably your NED and INI files, and the exact steps to reproduce/see the erroneous behavior.

**Comment by GOAguiar99** [comment]
Sorry for the delayed response. Attached is the zip file containing all the files I created. It does not include the FTM app, as it’s not relevant to this error—it's simply a UDP-based application.
[WifiTSN.zip](https://github.com/user-attachments/files/17895479/WifiTSN.zip)

**Comment by levy** [comment]
The example that you have attached doesn't run because of missing modules. I understand that I don't need the FTM app, but if you want me to help you, then at least provide a *minimal* example and *exact* steps to reproduce the error. For example, there are multiple configurations, which one am I supposed to run?

**Comment by GOAguiar99** [comment]
@levy Got it. Here is the FTM app. 
[FTM.zip](https://github.com/user-attachments/files/17954040/FTM.zip)
Here is the FTM app and the .ini file with just one config so you don't have problems with which one to use. This FTM app is in the application directory of inet in my case (i created there).
[omnetpp.zip](https://github.com/user-attachments/files/17954054/omnetpp.zip).


The pendingqueue file and TimeAwareShaperWifi.ned that i sent you before you put in: inet4.5/src/inet/linklayer/ieee80211/mac/queue

**Comment by GOAguiar99** [comment]
@levy Tested. It's working. Appreciate!
