### ISSUE TITLE
3D models are not animated anymore in Network Node Visualization showcase

### ISSUE THREAD

**Issue by adamgeorge309** [inet-framework/inet#1008]

**Comment by levy** [comment]
Interestingly enough neither the 'osganimationviewer boxman.osgb' plays the animation. This tool says: no osgAnimation::AnimationManagerBase found in the subgraph, no animations available

This model used to play the animation in Qtenv.

**Comment by levy** [comment]
So it turns out the osgb is a binary format and may not be backward compatible. The most likely cause is that OSG cannot fully load this osgb model correctly, so it just leaves out the animation part.

**Comment by levy** [comment]
This can be solved by replacing the model with another one where the animation actually works.

**Comment by adamgeorge309** [comment]
Replaced the model with a newer version. Animation works now.
