### ISSUE TITLE
Problems launching the debug

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#1014]
I have tried to launch the debug, but it is impossible, and I have this message

Os kubuntu 24.04
Omnet++ 6.1
inet-framework master branch updated to commit [5236543](https://github.com/inet-framework/inet/commit/52365439d35b8500048e39fb74a36bef085e9655) 

Error in final launch sequence:

Failed to execute MI command:
source /home/alfonso/omnetpp/omnetpp-6.1//misc/gdb/gdbinit.py
Error message from debugger back end:
Error occurred in Python: No module named 'inetgdb'
Failed to execute MI command:
source /home/alfonso/omnetpp/omnetpp-6.1//misc/gdb/gdbinit.py
Error message from debugger back end:
Error occurred in Python: No module named 'inetgdb'
Error occurred in Python: No module named 'inetgdb'

**Comment by aarizaq** [comment]
If "source setenv" is executed, the problem disappeared.

**Comment by rhornig** [comment]
Yes. `setenv` sets the PYTHONPATH that actually points to the directory where the required files are. The big frameworks are inherently require some state and this is really confusing. If you use an IDE, it is natural to start it from an icon on the desktop, but all the frameworks require various environment variables that can be set only **before** starting the IDE process so the proper way is to start a shell, specify what frameworks you intend to use by sourcing the `setenv` scripts and only after that start the IDE from that shell.

I admit, this is not ideal, but I have no idea how to work around this.
