### ISSUE TITLE
IPv4NetworkConfigurator is not working if the IEEE802.11 feature is turned off

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#104]
The configurator should be tested if it is working also when ethernet or wlan feature is turned off.

from: http://dev.omnetpp.org/bugs/view.php?id=565

**Comment by ZoltanBojthe** [comment]
it's work correctly in current master (7af8ef693a8072beafa5d759154b87f0db41c305).
All fingerprints passed, except when the simulation not run with error:
      Class "......." not found -- perhaps its code was not linked in, ...
