### ISSUE TITLE
-D feature selection flags should be easily accessible for compilation of dependent libraries

### ISSUE THREAD

**Issue by pkerling** [inet-framework/inet#115]
I have come across a quite intriguing problem while using the INET libraries from a separate shared library that contains other OMNeT modules. The following might apply to ELF/UNIX only, I haven't tested it with DLLs.

The INET headers (in my case, `src/networklayer/ipv6/IPv6InterfaceData.h`) contain lots of inline functions in the class bodys (in my case, `IPv6InterfaceData::getNumAddresses()`). If I place a call to such a function in my own code, the function will be compiled and linked into my library, too, and overwrite the same function from the inet library if it is loaded. Now this is in itself not a problem, since they should be identical anyway. Except they aren't - `IPv6InterfaceData::getNumAddresses` accesses the addresses private member variable of the `IPv6InterfaceData` class. The layout of the class and as a consequence the location of the `addresses` variable in memory changes depending on the `WITH_xMIPv6` preprocessor flag. If I do not set that flag during the compilation of my library to the same value the INET library was compiled with, strange and seemingly unrelated things happen (`addresses.size()` will return garbage in both INET and my code causing assertion failures in INET). Only because of a call to the function placed somewhere within a file - it doesn't matter whether the code using the function eventually gets called or not.
Now I can compile my library with `-DWITH_xMIPv6`, but everything might fall apart randomly because other things might depend on different flags and so I'd have to include them all. Still when INET is compiled with some features disabled it will stop working again, so this is definitely not a solution. A much cleaner way would be for INET to either
* write the feature selection flags to a file that is included by the INET headers, or
* provide an easy way to read the compile flags needed (maybe a pkg-config spec?)

Also, a note about this should be added to the `README`.

It might be worthwhile to note that e.g. juggling with symbol visibility will not help. The above applies to the debug build (`-O0`). When compiling with optimizations the call will be inlined anyway. Then at least INET doesn't break since the function isn't overriden, but my code would still not be able to correctly determine the size of `addresses`.

**Comment by rhornig** [comment]
Opps you are right, this is an OMNeT++ issue. See http://dev.omnetpp.org/bugs/view.php?id=819

Unfortunately features are handled by the OMNeT++ IDE so the IDE must provide the necessary flags on the command line. I see also the issue that once someone starts using a precompiled library there is no way to know with what features it was built. A generated header file could be a solution, but we have to define somehow where this header file is generated.

I'm closing this now as this is az OMNeT++ issue and I have created a separate tracker for it.
Thanks a lot for reporting.

**Comment by pkerling** [comment]
Thanks, but I want to add that this is not strictly an IDE issue. You can build INET from the commandline with `opp_makemake` (which the IDE internally uses too), so I'd say it needs to be fixed in makemake.
Futhermore, not all projects use the IDE/opp_makemake, or even <em>can</em> use it for that matter. Makemake is too restricted for use in heterogenous applications that also need to build normal binaries and other stuff besides the OMNeT things. Whatever the solution is gonna be, the flags should be either used by INET automatically (header file) or easily readable/parsable for maximum interoperability.
