### ISSUE TITLE
measure  end to end delay in omet++

### ISSUE THREAD

**Issue by jana123** [inet-framework/inet#124]
Hi All,

ineed your help guys, i have problem, that is,  i cant calculate the end to end delay in GPSR routing protocol, i have changed the application layer to be basic burst insted of  default one , i have enterd the data is in examples here but there is no result!!! i am fully confused. please  could u help me,,

best bregds

**Comment by rhornig** [comment]
Please do NOT use the bugtracker for support requests. Use the mailing list.

**Comment by jana123** [comment]
ok sure, but please i need your help for measure end to end delay, i am not sure what i have to do, best regards
