### ISSUE TITLE
Allow easier configuration of routing protocols in hosts

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#130]
Right now each routing protocol has its own XXXRouter NED type. It would be great to be able to configure a routing protocol by specifying a parameter only (just like NICs, mobility types etc.)

**Comment by rhornig** [comment]
This reuires a major rearchitecting of StandardHost. Running in:

https://github.com/inet-framework/inet/tree/topic/standardhost

**Comment by levy** [comment]
There's a ManetRouter which contains a configurable routing application. For internet routing, this hardly makes any sense.
