### ISSUE TITLE
Support external queues in CSMA, LMAC and BMAC

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#134]
While Ieee80211Nic and the IdealWirelessNic both allows changing the external queue implementation, CSAM, LMac and BMac has only an internal queue. Would be great to have the possibility to use external queues.

**Comment by edlongman** [comment]
Related to the internal Queue in BMAC, The statistic queue overflow statistic is currently (4.1.0) with the wrong name.: *packetDropQueueOverlow* it should be *packetDropQueueOverlow* 

Currently the port Queuing to BMac (253bab3) has left the old statistic in and now a new statistic will be available from the Queueing module. Doesn't this leave room for confusion and double counting when collecting signals (specifically packetDropped) Which is emitted by both BMac->Queue and BMac.

**Comment by levy** [comment]
The explict configurable queues are already added to all MAC protocols in the INET master branch. The packetDropQueueOverflow signal name typo is fixed. I'm not sure about the duplication of the packetDropQueueOverflow signal in the MAC and the queue modules. There are other reasons in a MAC module to drop a frame, and it may be a good idea to have a statistic for all kinds of different reasons at one place. For example, this may simplify result analysis. Clearly, you are right if there's only one queue in the MAC (and there is right now), then for the packetDropQueueOverflow statistic the values must be the same. I think this is the case right now, becase the MAC doesn't emit a packetDrop signal with QueueOverflow reason.

So I'll close this issue if there's no objection.
