### ISSUE TITLE
ieee80211_adhoc_twohost_speed.test

### ISSUE THREAD

**Issue by asangau** [inet-framework/inet#161]
Unlike in the previous INET version, the test network in the file "ieee80211_adhoc_twohost_speed.test" of the new version (inet-3.0.0) prevents the execution of simulations with the following message.

Error in module (inet::physicallayer::IsotropicAntenna) Throughput.cliHost[0].wlan.radio.antenna (id=11) during network initialization: getContainingNode(): node module not found (it should have a property named networkNode) for module 'Throughput.cliHost[0].wlan.radio.antenna'.

I found that this issue was related to the NetworkNode changes included in the new INET version.

FIX (temporary):
Include the "@networkNode();" in "parameters:" section of the ThroughputClient and ThroughputServer NED definitions.

Asanga Udugama

**Comment by levy** [comment]
This has been fixed in master as suggested. Thanks for the bug report.
