### ISSUE TITLE
EtherMACFullDuplex - move getNextFrameFromQueue() to scheduleEndIFGPeriod

### ISSUE THREAD

**Issue by tillsteinbach** [inet-framework/inet#163]
Dear INET-Community,

I want to suggest a change in the EtherMACFullDuplex module: Currently, the next frame is already requested before the IFG has finished. This way the next frame idles for the time of one IFG in the MAC. The behavior is not wrong, but it makes the implementation of shaper-algorithms more complex as the shaper cannot expect that the frame is sent immediately. Thus I would suggest that the next frame is requested after the end of the IFG. This is also much more intuitive.

If there are no arguments against such an extension I can offer to implement those changes and provide a pull request.

**Comment by ZoltanBojthe** [comment]
The correct title is:
EtherMACFullDuplex - move getNextFrameFromQueue() to handleEndIFGPeriod
