### ISSUE TITLE
[Radio bug] Insane IntervalTree

### ISSUE THREAD

**Issue by felixpoisot** [inet-framework/inet#169]
##### The bug: 
We run simulations of a long-range CDMA radio link. Some runs never complete : the simulation just hangs in an infinite loop, console output is frozen, and Ctrl+C does nothing.
Attaching a debugger shows that the nodes in an IntervalTree have somehow come to form a cycle, over which the tree traversal operations will never complete.

##### Diagnostic:
The infinite loop situation is somewhat rare / hard to reproduce (you need to generate reasonably big trees), so I've trapped the IntervalTree code with the following self-checks, called after each insert or remove operation :
```
// call this on 'nil' to check for damage
void IntervalTreeNode::chkNil()
{
   if (left != this || right != this || parent != this || red || stored_interval)
         throw cRuntimeError("nilpanic");
   const auto nts = -SimTime::getMaxTime();
   if (key != nts || high != nts || max_high != nts)
         throw cRuntimeError("nilpanic");
}

// call this on root->left to check on the RBTree invariants
int IntervalTree::selfCheck(IntervalTreeNode* n)
{
   int ld = 0, rd = 0; // black depths on each subtree
   if (n->left != nil) {
      ld = selfCheck(n->left);
      if (n->left->parent != n)
         throw cRuntimeError("Broken IntervalTree");
      if (n->red && n->left->red)
         throw cRuntimeError("Broken IntervalTree");
      if (n->left->key > n->key)
         throw cRuntimeError("Broken IntervalTree");
   }
   if (n->right != nil) {
      rd = selfCheck(n->right);
      if (n->right->parent != n)
         throw cRuntimeError("Broken IntervalTree");
      if (n->red && n->right->red)
         throw cRuntimeError("Broken IntervalTree");
      if (n->key > n->right->key)
         throw cRuntimeError("Broken IntervalTree");
   }
   if (ld != rd)
      throw cRuntimeError("Broken IntervalTree");
   if (!n->red)
      ++ld;
   return ld;
}
```
These traps will trigger almost immediately on all of our simulations, as well as on simple unit tests outside of Omnet. They give evidence that the 'nil' node is touched by invalid tree rebalancing operation considering it as a part of the tree. Depending on your particular data, it might be really made a part of the tree, deleted by the tree remove operation, etc...

I have trouble getting my head around red-black trees. I managed to adapt another implementation I found on the internet to expose the same interface : it passes the above self-checks and let all our simulations complete. But rewriting everything to fix this bug seems a bit excessive. It also seems slower on the simulation runs that could complete with the original IntervalTree, but timing that is not relevant.

**Comment by levy** [comment]
Unfortunately the IntervalTree implementation as stated by its copyright is not created by us. Nevertheless, I'll try to figure this out. Thanks for reporting!

**Comment by levy** [comment]
The implementation is based on this book: http://www.mif.vu.lt/~valdas/ALGORITMAI/LITERATURA/Cormen/Cormen.pdf 

I checked the IntervalTree::insert function, and I think it colors nodes incorrectly. I could actually come up with a simple standalone test case that breaks red-black tree properties with only 4 nodes.

    void insertNodes(IntervalTree *tree)
    {
       for (int i = 0; i < 4; i++)
       {
           double low = (double)rand() / RAND_MAX;
           double high = low + (double)rand() / RAND_MAX;
           char *c = new char[16];
           sprintf(c, "%d", i);
           Interval *interval = new Interval(low, high, c);
           tree->insert(interval);
       }
    }

    int main()
    {
        IntervalTree tree;
        insertNodes(&tree);
        tree.print();
        tree.nil->checkNil();
        tree.selfCheck(tree.root->left);
    }

I fixed this bug in IntervalTree::insert as follows (replacing 2 true values with false values)

    while (x->parent->red)
    {
        /// use sentinel instead of checking for root
        if (x->parent == x->parent->parent->left)
        {
            y = x->parent->parent->right;
            if (y->red)
            {
                x->parent->red = false;
                y->red = false;

At least now it passes the insertion test with 1 million nodes, I'm not sure if deletion is right. You could check your simulations while I'm looking at it...

**Comment by levy** [comment]
I've pushed two IntervalTree fixes to master and integartion branches. I also added a separate IntervalTreeTest under tests/unit. You can run it via ./runtest intervaltree.test. I commented out the parent check in checkNil because it seems to be harmless and the code just doesn't deal with keeping that intact. The IntervalTree test passes but for some reason node deletion doesn't scale as good as node insertion.

Could you please verify if this fixes your simulation?

**Comment by felixpoisot** [comment]
I'm running them now.
I just found out the replacement I wrote was not correct (by the way, you might want to have the unit test checking the interval query result against the result from a linear scan), but it surely was faster on remove.

This remove is slow because it does not take advantage of the binary search to find the interval to remove, and does a full tree scan in recursiveSearch(). 
My version defined a full order (compare Interval pointer values if keys are equal), so I could get to the node faster.

**Comment by levy** [comment]
This explains why it's slow with 100,000 nodes, and I guess it wouldn't be
hard to fix it.

**Comment by felixpoisot** [comment]
All runs could finish normally (results are still bad, but that's a problem with my code). 
I also ran a few more standalone tests, and IntervalTree seems to work fine, for what I know.
Aside from that slow remove thing, I guess we can call it fixed. 
Thanks a lot !
