### ISSUE TITLE
INET 3.0 cRuntimeError on OS X when terminating the simulation

### ISSUE THREAD

**Issue by tillsteinbach** [inet-framework/inet#170]
I get a cRuntimeError on OS X only. Unfortunately I cannot trace it down due to the current lack of debugging functionality on OS X 10.10

```
libc++abi.dylib: terminating with uncaught exception of type cRuntimeError: SerializerRegistrationList not empty, should call the SerializerRegistrationList::clear() function
```

This happens in a network with EtherMACFullDuplex thus I guess it is related to the Ethernet Serializer? Maybe EXECUTE_ON_SHUTDOWN is not properly executed?

**Comment by weinrank** [comment]
+1
