### ISSUE TITLE
INET 3.1 build fail on Windows version

### ISSUE THREAD

**Issue by xinnanlyu** [inet-framework/inet#173]
Fresh install of OMNeT++ v5.0b2 on windows 10 64-bit.  Same issue also exist when building INET v3.1 on OMNeT++ v4.6.

![capture](https://cloud.githubusercontent.com/assets/13437778/10577985/21f3e748-7667-11e5-9495-d328cac0a3c5.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13437778/10578062/a8ef2b2c-7667-11e5-989d-4338b6f7b5d8.PNG)

Is there a way to use INET 3.1 on windows without using packetdrill?

**Comment by xinnanlyu** [comment]
I removed /application/packetdrill and /node/packetdrill, and build INET again on Windows, and it fix.

**Comment by rhornig** [comment]
Thanks for reporting. You should have left the issue as OPEN. This is a legitimate bug even if you were able to work around INET still have to fixed as other users will face the same issue.
Working on it and will create an INET 3.1.1 release :(

**Comment by xinnanlyu** [comment]
Thanks Rudolf. I'm new to Github as I use Google Groups mostly. Will let you know once I find any bug in the future.

**Comment by rhornig** [comment]
No problem. I have fixed this and will release INET 3.1.1 shortly.

**Comment by rhornig** [comment]
Fixed in 3.1.1
