### ISSUE TITLE
Ieee80211Mac private members

### ISSUE THREAD

**Issue by segmentation-fault** [inet-framework/inet#177]
Hello,
it would be very useful if the private members at the beginning of the Ieee80211Mac class would be changed from private to protected. Just add the keyword protected at the beginning. It is extremely useful when refactoring the long intitialize method.
Best

**Comment by rhornig** [comment]
This is no longer relevant as the whole Ieee802.11 MAC was replaced with a new implementation which was split into smaller logical units.
