### ISSUE TITLE
Problem when defining new messages with INET 3.1.1

### ISSUE THREAD

**Issue by giovanninardini** [inet-framework/inet#178]
I'm having some issues with INET 3.1.1 (and OMNeT++ 4.6).
I created the following message (MyMessage.msg):

cplusplus {{
# include "L3Address.h"

}};

struct inet::L3Address;

message MyMessage {
        inet::L3Address clientAddr; 
        int clientPort;  
}

When compiling, I get the following errors:

ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘const char [15]’)
ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘const char [2]’)
ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘const char [3]’)
ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘const char [8]’)
ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘const char\* const’)
make: **\* [all] Error 2 
make[1]: **\* [../out/gcc-debug/src/MyMessage_m.o] Error 1

all of them located at:

line 522, external location: /home/giovanni/omnetpp-4.6/include/cenvir.h

The error seems to occur in file INETDefs.h, at function printElapsedTime(), shown below:

inline void printElapsedTime(const char *name, long startTime)
{
    EV_DEBUG << "Time spent in " << name << ": " << ((double)(clock() - startTime) / CLOCKS_PER_SEC) << "s" << endl;
}

The compiler cannot resolve the conflict between operator<< in class cEnvir and other redefinitions of the operator<<. 
In my code, operator<< has been redefined only in file MyMessage_m.cc (which is generated automatically by OMNeT).
Note that if I remove the inclusion of file L3Address.h from the message definition, everything works fine.

Giovanni

**Comment by ZoltanBojthe** [comment]
fixed, tested with omnetpp 5.1 and inet 3.5
