### ISSUE TITLE
INET 3.2.0 ratecontroltest example crashes

### ISSUE THREAD

**Issue by zvikom** [inet-framework/inet#181]
running this example, using the default configuration, crashes with the following error message:

<!> Error in module (inet::ieee80211::Rx) RateControlTest.sinkClient.wlan.mac.rx (id=35) at event 14, t=0.104337332805: check_and_cast(): cannot cast (inet::physicallayer::ReceptionIndication *) to type 'inet::physicallayer::Ieee80211ReceptionIndication *'.

The error occurs in "/inet/src/inet/linklayer/ieee80211/mac/BasicStatistics.cc" line 154 : 

void BasicStatistics::frameReceived(Ieee80211Frame *frame)
{
.......
    if (rateControl) {
       auto receptionIndication = check_and_cast<Ieee80211ReceptionIndication*>(frame->getControlInfo());  // BUG HERE, wrong casting
        rateControl->frameReceived(frame, receptionIndication);
    }
}

In addition, after opening the file in the IDE , a semantic error appeaser:
"Invalid arguments '
Candidates are:
void frameReceived(const inet::ieee80211::Ieee80211Frame *, const ? *)
'	BasicStatistics.cc	/inet/src/inet/linklayer/ieee80211/mac	line 155	Semantic Error"

It seems that no other module constructs an "Ieee80211ReceptionIndication" object (derived from ReceptionIndication) till this message bubbled up to the "BasicStatistics" instance during MAC frame RX procedures.

(tested on: UBUNTU 14.04, omnet 4.6, INET 3.2.0 release )

**Comment by rhornig** [comment]
fixed. in 3.2.1
