### ISSUE TITLE
Error in running INET 3.2 wireless tutorial, link weight problem

### ISSUE THREAD

**Issue by fayruzrahma** [inet-framework/inet#182]
Hi guys,

I run INET wireless tutorial without changing anything in the code. I have no problem in Wireless01-03 scenario.
But then I encountered a problem when trying to run Wireless04 scenario.

This is the log I got:
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR3.wlan0 -> WirelessB.hostA.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR1.wlan0 -> WirelessB.hostA.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR2.wlan0 -> WirelessB.hostA.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostB.wlan0 -> WirelessB.hostA.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR3.wlan0 -> WirelessB.hostB.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR1.wlan0 -> WirelessB.hostB.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR2.wlan0 -> WirelessB.hostB.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostA.wlan0 -> WirelessB.hostB.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR3.wlan0 -> WirelessB.hostR1.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR2.wlan0 -> WirelessB.hostR1.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostA.wlan0 -> WirelessB.hostR1.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostB.wlan0 -> WirelessB.hostR1.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR3.wlan0 -> WirelessB.hostR2.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR1.wlan0 -> WirelessB.hostR2.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostA.wlan0 -> WirelessB.hostR2.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostB.wlan0 -> WirelessB.hostR2.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR1.wlan0 -> WirelessB.hostR3.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR2.wlan0 -> WirelessB.hostR3.wlan0, weight = nan
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostA.wlan0 -> WirelessB.hostR3.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostB.wlan0 -> WirelessB.hostR3.wlan0, weight = nan
<!> Error in module (inet::IPv4NetworkConfigurator) WirelessB.configurator (id=2) during network initialization: Model error: ASSERT: condition linkWeight > 0.0 false in function calculateWeightedSingleShortestPathsTo, inet/common/Topology.cc line 452.

It seems that the static routing process is failed because of link weight problem.
Because of that, I couldn't run the scenario of Wireless04-07 and got the same error log.
Wireless08-13 is OK because those scenario use dynamic routing protocol.

I run INET 3.2 on OMNeT++ 4.6, Windows 8.1.

**I can run Wireless04-07 in INET 3.1**. The link weight was set properly.

WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostB.wlan0 -> WirelessB.hostA.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR2.wlan0 -> WirelessB.hostA.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR3.wlan0 -> WirelessB.hostA.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR1.wlan0 -> WirelessB.hostA.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostA.wlan0 -> WirelessB.hostB.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR2.wlan0 -> WirelessB.hostB.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR3.wlan0 -> WirelessB.hostB.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR1.wlan0 -> WirelessB.hostB.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostA.wlan0 -> WirelessB.hostR1.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostB.wlan0 -> WirelessB.hostR1.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR2.wlan0 -> WirelessB.hostR1.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR3.wlan0 -> WirelessB.hostR1.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostA.wlan0 -> WirelessB.hostR2.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostB.wlan0 -> WirelessB.hostR2.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR3.wlan0 -> WirelessB.hostR2.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR1.wlan0 -> WirelessB.hostR2.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostA.wlan0 -> WirelessB.hostR3.wlan0, weight = inf
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostB.wlan0 -> WirelessB.hostR3.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR2.wlan0 -> WirelessB.hostR3.wlan0, weight = 0.001
WirelessB.configurator: DEBUG: Setting link weight, link = WirelessB.hostR1.wlan0 -> WirelessB.hostR3.wlan0, weight = 0.001

So, maybe, is this problem because of INET 3.2 bug?

Thank you for your kind attention.

Regards,
Fayruz

**Comment by levy** [comment]
Thank you for reporting this bug. It will be fixed in the next INET release.
