### ISSUE TITLE
Issues with the python command

### ISSUE THREAD

**Issue by luisfnqoliveira** [inet-framework/inet#184]
When executing command 'make makefiles', there is an error due to line 1 of inet_featuretool.
It reads: "#! /usr/bin/env python"

While PEP394 [1] recommends that python should refer to python2, on Archlinux (and possibly others) it refers to python3. Therefore [1], refers that python should only be used when code is compatible with both versions, and in this case it is not therefore it should read "#! /usr/bin/env python2".

[1]  http://legacy.python.org/dev/peps/pep-0394/

Edit: Using v3.2.1.

**Comment by rhornig** [comment]
Thanks. Updated the command to be python 2 and 3 compatible.
