### ISSUE TITLE
INET wlan faulty power consumption 

### ISSUE THREAD

**Issue by ghostdog1979** [inet-framework/inet#195]
The power consumption calculation does not account correctly the distance between sender and receiver nor the energy level of the received signal. Unfortunately, I was not able to identify the bit of code that issues that bug. Thus i like to describe the wrong behaviour. 

Define a network with two WLAN access points and three mobile clients. the WLAN access points are located in a large distance from each other (outside the radio interference distance, e.g. 10 km). client_1 is located next to access point AP1, client_2 and client_3 are located next to access point AP2. 

During the simulation run, client_1 sends messages to client_2 and client_3 (application level multicast), each message is acked. 

In the omnet-ini file you have to define for each client a simple energy storage and a StateBasedEnergyConsumer. Afterwards, define the energy consumption as follows:
- offPowerConsumption = 0W
- sleepPowerConsumption= 0W 
- switchingPowerConsumption= 0W 
- receiverIdlePowerConsumption= 0W 
- receiverBusyPowerConsumption= 0W 
- receiverReceivingPowerConsumption = 0W 
- receiverReceivingPreamblePowerConsumption = 0W
- receiverReceivingHeaderPowerConsumption = 0W
- receiverReceivingDataPowerConsumption = 0W 
- transmitterIdlePowerConsumption= 0 W 
- transmitterTransmittingPowerConsumption= 2 W 
- transmitterTransmittingPreamblePowerConsumption = 2 W
- transmitterTransmittingHeaderPowerConsumption = 2 W 
- transmitterTransmittingDataPowerConsumption = 2 W 

In my test run, client_1 sends 98 messages on the application level, client_2 51 messages and client 3_46 messages. 

Due to the defined power consumption, it is assumed that the energy consumption of client_1 is larger than the one at client_2 and client_3. Further i has expected that the power consumption of client_1 is nearly the double of that of the client_2 and client_3. However, the state of charge of the clients is:
- client_1 85.4456 %
- client_2 85.4606 %
- client_3 85.424 %

I guess there are a number of issues that resulting in that bug. If access point 1 starting a transmission (outside the reception distance of client_2 and client_3), each client is called to handle this transmission. 

It seams that each transmission received by a client results in a power consumption, independent of its distance to the sending access point. Thus, even if the client several hundred of meters far away from the sending access point, it results in a receiving-power-consumption. The ramp up and down of the radio states seems to trigger a false power consumption at the state based energy consumer. This is noticeable with the power settings above. Despite the free of charge for receiving a message, client_2 and client_3 have more or less the same energy consumption as client_1.

If you are setting each power-consumption-value to zero, the results are as expected. 

I guess the bug is located in the point of time, emitting the radio-state-changed signals. From my point of view, there has to be a kind of energy consumption role back, if the reception is not possible due to the low energy level of the signal issued by the distance between sender. 

In my test case, the distance between client_1 and client_2/client_3 was larger than 80000 m, and the sending rate of client_1 was the double of client_2/client_3. however, all clients have the nearly the **same** energy consumption. IMHO, this can not be explained by a physical reason.  

PS: Inet 3.2.3

**Comment by levy** [comment]
The power consumption configuration that you use means that the radios don't consume power during reception. In fact, they don't consume power in receive mode independently of whether a signal is being received or not. Power consumption is entirely based on the transmissions, and thus it's not affected by the distance of the radios.

You also mention that the applications send multicast packets, and that they are acked. I think multicast  packets are not acked by default, so there's something fishy.

Finally, power consumption during transmission is also affected by transmitting acks. You should also check if there are any other protocols that are sending wireless packets, because it would also affect power consumption.

Without knowing more details, it's hard to tell if there's really a bug or not.

**Comment by ghostdog1979** [comment]
Hey levy,

thanks for your fast response. :) Indeed, the given power consumption configuration ignores the costs for receiving a message. But, this is just an test setup to illustrate the bug/faulty behavior. 

In my simulation, I use a more or less standard wireless host. The radio is an IEEE80211ScalarRadio, the medium is defined as IEEE80211ScalarRadioMedium. On top of IP is use UDP and my own application level multicast protocol, which offers the described behavior.The IP is statically configured and the useGlobalArp option is set to true. IMHO, where is no other protocol which is sending and receiving messages.  

Indeed, power consumption is entirely based on the transmissions, and thus it's not affected by the distance of the radios. In my test simulation run, client_1 is sending twice the number of messages from client_2/client_3. In addition, the distance between the client_1 and the clients_2/client_3 is at least 85000m (!). Independent of that fact, IMHO the power consumption of client_1 should differ significantly over the time from the one of client_2/client_3. Or not? 

Should I provide the ned and config file I used? The sending protocol is unfortunately not for a public audience ;).

Thanks in advance.

**Comment by levy** [comment]
There may be factors other than the number of packets sent by the application that affect the power consumption. Do each one of those packets have the same size? That would also affect power consumption.

**Comment by ghostdog1979** [comment]
Hallo Levy,

no, each packet type has its individual size. during my tests, the power consumption of all nodes (i have done simulation runs with up to 100 peers), all nodes within the network have the same power consumption (+/- 0.5%). Maybe for three or four peers this may happen, but i see the same effect in a large network with 100 peers at 25 access points and a individual number of lost and re-transmitted messages. In my opinion where have to be a significant difference in the peers power consumption (depending on the number of totally send message, which includes the acks and so one), but it isn't.  :(

**Comment by ghostdog1979** [comment]
Hallo Levy,

I have created a small test run, attached to this comment. In this test, I use the UDPBaseApp for illustrating the behaviour. To ease the power consumption observation, I enhance the INET SimpleEnergyStorage to signal the residual capacity. 

[WlanPowerConsumptionTest.tar.gz](https://github.com/inet-framework/inet/files/199659/WlanPowerConsumptionTest.tar.gz)

The network defines 2 wireless hosts and 2 access points. WirelessHost1 is connected to AccessPoint1, WirelessHost2 is connected to AccessPoint2. Both access points are isolated. If you run the simulation, WirelessHost1tries to ping WirelessHost2, but no message is ever delivered. During the simulation run,  WirelessHost1 tries to send almost 2000 messages.

If you run the Config Low, the radio is defined with a power consumption according to a Cisco spec sheet. Config High defines the power consumption with huge 100W per sending related parameter.  The distance between WirelessHost1 and WirelessHost2 is almost 90000m. Thus, they should not effect each other. 

However, if you observe the residualCapacity property of each wireless host, you can observe that the power consumption is the same on wireless host 1 and wireless host 2. Config High issues a very small residual capacity cap between the both nodes. From that perspective, it seams to be without any costs to send almost 2000 messages. IMHO is this a bug. Do you know what is my point?

best and thanks :)

**Comment by levy** [comment]
I will look at this issue more deeply in a few days and come back to you.

**Comment by ghostdog1979** [comment]
Thank you very much :)

**Comment by levy** [comment]
If you increase the power consumption of transmitting to 100kW, then there is a measurable difference between WirelessHost1 and WirelessHost2. Of course, that is entirely unrealistic, but I think the behavior you are experiencing is due to the following. Power consumption is dominated by the receiving states, because most of the time there's no transmission at all. Also, if you change the reception power consumption to 0W, then the difference shows up again. In the provided example, the application sends a 100 bytes packet every second, which is negligible to the receiving power consumption for the rest of the time (>99.9%). I hope this helps.

**Comment by ghostdog1979** [comment]
Hey levy,

indeed, due to the missing of power management, the host listens most of the time. however, if omnet hands over a packet to the wireless host, its switches its receiver into receiving, tests if the message receivable or not, and switches back to listen, if the power level not sufficient. in a close range to the sending ap is this correct, but in my example, messages beyond the theoretical communication range will cause a power consumption at each wireless node within the network. indeed, its possible to correct the faulty behaviour by significantly increasing the power consumption of the sending peer, but it is not a solution. from my point of view, the wireless node has to check before it receives a message, if the reception possible in terms of communication distance. if not, the reception should be skipped. A kind of energy consumption roleback may by another possible approach.

In my simulation, as a workaround i have set up the energy consumption for sending and receiving to the listen level and added an additional power consumption instance, that consumes for each message send and receive the appropriated portion of energy. By this, i lost the energy consumption from mac retries and so on. However, the resulting power consumption of the wireless nodes correlates direct to the number of send and received messages. That is for me the important point. The current omnet behaviour is unfortunately not realistic.

**Comment by levy** [comment]
I think you misunderstand how it works. In your simulation, WirelessHost2 never switches to RECEIVING state for any transmission from WirelessHost1 (they are far away). However, it does switch to RECEIVING state for Beacon frames from AccessPoint2 (they are close). You can see this in the log window or in the sequence chart. Also, you seem to confuse BUSY state with RECEIVING state, because you set the same power consumption for them. The receiver switches to BUSY state when it detects that the medium is not IDLE, but it's impossible to receive a signal correctly. I think the observed power consumption is not faulty, the explanation in my previous comment still stands. I think your current analysis is wrong.
