### ISSUE TITLE
Error in method void IPv6::handleMessageFromHL(cPacket *msg)

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#196]
Version of inet 2.x and 3.x

The method void IPv6::handleMessageFromHL(cPacket *msg) can throw and exception in the line
    IPv6Datagram *datagram = encapsulate(msg, controlInfo);
    delete controlInfo;

The method "encapsulate" can delete the controlInfo structure if not valid route is found, in this case the code will delete two times the structure controlInfo two times and the program will throw an exception.

A possible solution:

    IPv6Datagram *datagram = encapsulate(msg, controlInfo);
    if (!datagram) 
         delete controlInfo;

When the method encapsulate delete the structure controlInfo always it returns a null pointer, it is possible to check if the method has returned a valid pointer

**Comment by aarizaq** [comment]
Sorry it should be
if (datagram) 
     delete controlInfo;

**Comment by ZoltanBojthe** [comment]
Thank You!

The correct fix is: should not delete `controlInfo` in `IPv6::encapsulate()`:
 the `IPv6::handleMessageFromHL()` not changed, 
 and removed the line `delete controlInfo;` from `IPv6::encapsulate()` method.
