### ISSUE TITLE
Inconsistency in Ieee802.11 MAC

### ISSUE THREAD

**Issue by segmentation-fault** [inet-framework/inet#197]
Hello,
I would like to signal an inconsistency found in the current stack of the IEEE 802.11 implementation. In the mgmt layer, the destination MAC address is put into the address_3 field of the Ieee80211DataOrMgmtFrame class. Then in the utils class the method isSentByUs checks this field in order to discover whether the frame is sent by the node itself. Is in reality this method checking wether the frame is for us? In that case, is it a duplicate of the method isForUs?
Best

**Comment by Benmartin92** [comment]
Hi segmentation-fault,

The isForUs() function uses the isSentByUs() which is intended to check the case when our frame sent through an access point. Therefore it's not a duplicate method.

Regards,
Ben
