### ISSUE TITLE
Error with ned functions

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#199]
Tested in Win 7 64. Omnet 5.0, git version inet

When I try to run the examples I have an error with this message

Error in module (omnetpp::cModule) Net.hos[0] during network setup: Funtion 'firstAvailableOrEmpty' (with 3 args) not found (Define_NED_Funtion() or Define_NED_Math_Funtion() missing from C++ mode?

**Comment by rhornig** [comment]
Could you specify which message you've tried to run?

**Comment by rhornig** [comment]
Any news on this? Which example was this as I cannot reproduce locally.

**Comment by rhornig** [comment]
Is this still an issue? If yes, please re-open.

**Comment by fola-lana** [comment]
![omnet error](https://cloud.githubusercontent.com/assets/20494671/26789066/68f58430-4a0f-11e7-8caf-00503b4689d8.png)

Anyone with an idea how to fix this error?

**Comment by aarizaq** [comment]
Have you check if the libinet.dll file has been correctly created?
The size of this file should be about 400MB

De: Fola Lana [mailto:notifications@github.com]
Enviado el: lunes, 05 de junio de 2017 16:53
Para: inet-framework/inet <inet@noreply.github.com>
CC: Alfonso <aarizaq_m@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [inet-framework/inet] Error with ned functions (#199)


[omnet error]<https://cloud.githubusercontent.com/assets/20494671/26789066/68f58430-4a0f-11e7-8caf-00503b4689d8.png>

Anyone with an idea how to fix this error?

**Comment by fola-lana** [comment]
I've checked and my libINET.dll file is 341MB. Is that unusual? If so, any ideas how I could fix it or recompile it?

**Comment by aarizaq** [comment]
No, it depends of the option that you have included, the size is enough


De: Fola Lana [mailto:notifications@github.com]
Enviado el: martes, 06 de junio de 2017 15:13
Para: inet-framework/inet <inet@noreply.github.com>
CC: Alfonso <aarizaq_m@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [inet-framework/inet] Error with ned functions (#199)


I've checked and my libINET.dll file is 341MB. Is that unusual? If so, any ideas how I could fix it or recompile it?

**Comment by varunag18** [comment]
I have installed Omnet++ 5.1.0 on Win 7 64 bit machine. Samples are running correctly. Iv installed inet 3.5.0, getting no errors but 151 warnings all of type NED consistency problem. The examples are giving an error same as in this thread. For example, when i run adhoc, i get the following error:
"<!> Function hasVisualizer() not found (Define_NED_Function() or Define_NED_Math_Function() missing from C++ code?), at C:\omnetpp-5.1-src-windows\omnetpp-5.1\samples\inet\examples\adhoc\hostautoconf\Scenario.ned:29 -- in module (omnetpp::cModule) Scenario (id=1), during network setup".
Similarly, trying to run aodv gives the below error:
"<!> Class "inet::physicallayer::RadioMedium" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (omnetpp::cModule) AODVNetwork (id=1), during network setup
"
I have checked the size of libINET.dll in the inet/src folder and it is only 106 kb. 
Please suggest me a solution.
Thanks in advance.

**Comment by aarizaq** [comment]
The latest version of inet will need omnet 6

**Comment by Arya-LAY** [comment]
> The latest version of inet will need omnet 6

Thanks, but I use inet-4.2.10, not the latest version.

**Comment by aarizaq** [comment]
In this case, you will need to check if the library has been correctly created.

**Comment by adel0049** [comment]
I am trying to run a V2X project with Omnet++ 5.6.2 , Veins 5.2 and SUMO 1.14.1 to propagate CAM messages, i have defined CAM messages and solved some errors, but now i am facing with error : **Function vein_omnetpp_buildnum() (Define_NED_Function() or Define_NED_Math_Function() missing from C++ code?) -- in module (veins::BaseWorldUtility) RSUExampleScenarion.world (id=5), during network setup**. I appreciate if zou can help me to solve the issue. i have attached screenshot of the error.
![ERROR](https://github.com/inet-framework/inet/assets/75276986/72bc439a-6ac8-40b4-a3f9-111efc222105)
