### ISSUE TITLE
processing Delays sums up for all packets in the queue

### ISSUE THREAD

**Issue by Tcc100** [inet-framework/inet#201]
The AbstractQueue in the IPv4/IPv6 modules (IPv4 > QueueBase > AbstractQueue) seems to start the delay of a packet when the delay of the preceeding packet expired. This leads to an output rate of one packet per procDelay rather than a delay of procDelay per packet.

See comments: [AbstractQueue.cc.txt](https://github.com/inet-framework/inet/files/293390/AbstractQueue.cc.txt)

**Comment by ZoltanBojthe** [comment]
The procDelay parameter means the processing time on a single thread.
