### ISSUE TITLE
Error when building inet master

### ISSUE THREAD

**Issue by weinrank** [inet-framework/inet#203]
When compiling inet i get the following error.
OSX 10.11.5
Omnet 5.0

[error.txt](https://github.com/inet-framework/inet/files/307897/error.txt)

>weinrank@Idefix3 ➜  inet git:(master) ✗ git branch -v
* master 39689aa visualizer: added missing osg libraries when building with OSG support + removed a debug line

Any hints?

**Comment by rhornig** [comment]
Thanks. Indeed some additional libs were needed on Mac ans Windows. Fixed in master.

**Comment by weinrank** [comment]
Thx for the fast response - works for me! 👍
