### ISSUE TITLE
beginner help request

### ISSUE THREAD

**Issue by Abbode** [inet-framework/inet#204]
hello guys ... I'm a beginner in omnet .... not that good at all in programming ... and i need to make a 5G basic network and I have only 3 weeks left ..... I don't know how and start to lose hope ..... any one help me please.... How can I do that .... I tried hard to understand how omnet works for months but with no use .... I don't know how to do the ned nor the things after .... please help ... I'm completely down ..... please don't ignore

**Comment by rhornig** [comment]
No offense, but this is a bugtracker, not a public forum. You should try the omnet++ mailing list.
