### ISSUE TITLE
Ieee802.11 RTS/CTS desn't work.

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#206]
Ieee 802.11 RTS/CTS mechanism doesn't work

Tested with the example  aodv

Changes in the ini configuration

**.wlan[*].typename = "Ieee80211Nic"
**.wlan[*].mac.rtsThresholdBytes = 0B

Error message

“Error in module (inet::ieee80211::DcfUpperMac) AODVNetwork.host[12].wlan[0].mac.upperMac (id=535) at event #1670, t=3.52889273024: ASSERT: condition false false in function handleSelfMessage, inet/linklayer/ieee80211/mac/FrameExchange.cc line 306.”

**Comment by rhornig** [comment]
Fixed in INET 3.4
