### ISSUE TITLE
collisions on IdealWirelessNic

### ISSUE THREAD

**Issue by fastriker** [inet-framework/inet#210]
I did a simulation with IdealWirelessNic, IdealRadioMedium and activated ignoreInterference on the IdealReceiver. On the description of IdealWirelessNic it is mentioned that there are no collisions. However I got a few. I think this is an example of the relevant log from the radio:
> ** Event #32810  t=36.010667694001  RegularNetworks.node[6].wlan[0].radio (IdealRadio, id=275)  on 14 - UDPBasicAppData-0 (inet::physicallayer::RadioFrame, id=127452)
DEBUG (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Receiving IdealTransmission from medium by (inet::physicallayer::Radio)radio arrives as IdealReception
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Reception started: attempting (inet::physicallayer::RadioFrame)14 - UDPBasicAppData-0 WHOLE as IdealReception
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Changing radio reception state from IDLE to RECEIVING.
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Changing radio received signal part from NONE to WHOLE.
** Event #32846  t=36.010689897981  RegularNetworks.node[6].wlan[0].radio (IdealRadio, id=275)  on selfmsg receptionTimer (omnetpp::cMessage, id=127421)
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Reception ended: ignoring (inet::physicallayer::RadioFrame)17 - UDPBasicAppData-2 WHOLE as IdealReception
** Event #32858  t=36.010704097945  RegularNetworks.node[6].wlan[0].radio (IdealRadio, id=275)  on 19 - UDPBasicAppData-1 (inet::physicallayer::RadioFrame, id=127549)
DEBUG (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Receiving IdealTransmission from medium by (inet::physicallayer::Radio)radio arrives as IdealReception
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Reception started: attempting (inet::physicallayer::RadioFrame)19 - UDPBasicAppData-1 WHOLE as IdealReception
** Event #32877  t=36.010748879186  RegularNetworks.node[6].wlan[0].radio (IdealRadio, id=275)  on selfmsg receptionTimer (omnetpp::cMessage, id=127491)
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Reception ended: ignoring (inet::physicallayer::RadioFrame)14 - UDPBasicAppData-0 WHOLE as IdealReception
** Event #32900  t=36.01078528313  RegularNetworks.node[6].wlan[0].radio (IdealRadio, id=275)  on selfmsg receptionTimer (omnetpp::cMessage, id=127592)
DEBUG (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Receiving IdealTransmission from medium by (inet::physicallayer::Radio)radio arrives as IdealReception and results in ReceptionDecision
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Reception ended: successfully for (inet::physicallayer::RadioFrame)19 - UDPBasicAppData-1 WHOLE as IdealReception
DEBUG (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Receiving IdealTransmission from medium by (inet::physicallayer::Radio)radio arrives as IdealReception and results in ReceptionResult
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Sending up (inet::IdealMacFrame)19 - UDPBasicAppData-1
DEBUG (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Listening with IdealListening on medium by (inet::physicallayer::Radio)radio results in ListeningDecision
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Changing radio reception state from RECEIVING to IDLE.
INFO (IdealRadio)RegularNetworks.node[6].wlan[0].radio: Changing radio received signal part from WHOLE to NONE.

The radio attempted to receive 14 - UDPBasicAppData-0. Before the this is finished, the same happened to 19 - UDPBasicAppData-1. The consequence was that 14 - UDPBasicAppData-0 was ignored and 19 - UDPBasicAppData-1 was received.

I used Omnet++ 5.0 and INET 3.4.0

**Comment by fastriker** [comment]
Remove the condition `timer == receptionTimer` on function Radio:endReception in line 472 seems to solve the problem for this special case. Of course this isn't a solution in general for the Radio class. I hope this will not have side effects on my simulation I aren't able to see now.

**Comment by levy** [comment]
Thanks for reporting this. For me, this bug seems to be caused by IdealReceiver. It attempts to receive any received signal when ignoreInterference is true, but in general a radio is only capable to receive one signal at a time. So the radio just simply switches to the signal that comes later (often called capture). Interference is still ignored in the receiver though.

Do you have an example to reproduce this?

**Comment by fastriker** [comment]
I tried to write a small example but I'm not able to identify the error. In my project I write a module on top of inet::INetfilter::IHook to simulate a self designed protocol. The module only sends special messages. Is it possible that the module caused the error? Because of the different layers I didn’t think about this.

My small example:
Network.ned

	package idealwirelessnictest.simmulation;

	import inet.node.inet.WirelessHost;
	import inet.physicallayer.idealradio.IdealRadioMedium;
	import inet.networklayer.configurator.ipv4.HostAutoConfigurator;

	module Node extends WirelessHost
	{
		parameters:
			int communicationRadius @unit(m) = default(500m);
		    networkLayer.configurator.networkConfiguratorModule = "";
		    wlan[*].mgmtType = default("Ieee80211MgmtAdhoc");
		    wlan[*].typename = "IdealWirelessNic";
		    wlan[*].bitrate = 54Mbps;
		    wlan[*].radio.transmitter.communicationRange = communicationRadius;
		    wlan[*].radio.receiver.ignoreInterference = true;
		    autoConfigurator.interfaces = "wlan0";
		    @display("r0=$communicationRadius");
		            
		submodules:
			autoConfigurator: HostAutoConfigurator;
	}


	network Network
	{
		parameters:
		    int numHosts = default(10);
		    
		submodules:
		    node[numHosts]: Node;
		    radioMedium: IdealRadioMedium 
		    {
		        parameters:
		            @display("p=50,50");
		    }
	}

omnetpp.ini

	[General]
	network = Network
	seed-set = ${repetition}
	sim-time-limit = 150s

	**.node[*].numUdpApps = 2
	**.node[*].udpApp[*].typename = "UDPBasicApp"
	**.node[*].udpApp[*].destAddresses = moduleListByNedType("idealwirelessnictest.simmulation.Node")
	**.node[*].udpApp[*].destPort = 54321
	**.node[*].udpApp[*].messageLength = 512B
	**.node[*].udpApp[*].sendInterval = 3s
	**.node[*].udpApp[*].startTime = 1s
	**.node[*].udpApp[*].stopTime = 100s

	**.mobilityType = "StaticGridMobility"
	**.numHosts= 3
	**.columns = 3
	**.rows = 1
	**.communicationRadius = 750m
	**.separationX = 500m
	**.separationY = 500m
	**.constraintAreaMinX = 0m
	**.constraintAreaMinY = 0m
	**.constraintAreaMinZ = 0m
	**.constraintAreaMaxX = 1500m
	**.constraintAreaMaxY = 1000m
	**.constraintAreaMaxZ = 0m

In my project there is only one `UDPBasicApp` sending messages at random times. The error is very rare and I only identify it with the results of my module.

**Comment by levy** [comment]
Could you please try the above patch?

**Comment by fastriker** [comment]
I tried the patch. I still have missing packets, but I think there is an other issue or it is a correct behaviour I don't understand. I searched for the missing packets in the log and got this:

> ** Event #22015  t=22.59570938219  RegularNetworks.node[14].wlan[0].radio (IdealRadio, id=571)  on 11 - UDPBasicAppData-0 (inet::physicallayer::RadioFrame, id=453128)
DEBUG (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Receiving IdealTransmission, communicationRange = 500 m, interferenceRange = 500 m, detectionRange = 500 m, id = 3831, transmitterId = 67, startTime = 22.595697707447, endTime = 22.595778892632, startPosition = (3750, 100, 0), preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, endPosition = (3750, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0) from medium by (inet::physicallayer::Radio)radio, antenna = { IsotropicAntenna }, transmitter = { IdealTransmitter, communicationRange = 500 m }, receiver = { IdealReceiver, ignoring interference } arrives as IdealReception, power = UNDETECTABLE, transmissionId = 3831, receiverId = 74, startTime = 22.59570938219, endTime = 22.595790567375, preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0)
INFO (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Reception started: not attempting (inet::physicallayer::RadioFrame)11 - UDPBasicAppData-0 WHOLE as IdealReception, power = UNDETECTABLE, transmissionId = 3831, receiverId = 74, startTime = 22.59570938219, endTime = 22.595790567375, preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0)
DEBUG (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Listening with IdealListening, receiverId = 74, startTime = 22.59570938219, endTime = 22.595709382191, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0) on medium by (inet::physicallayer::Radio)radio, antenna = { IsotropicAntenna }, transmitter = { IdealTransmitter, communicationRange = 500 m }, receiver = { IdealReceiver, ignoring interference } results in ListeningDecision, impossible, listening = { IdealListening }
** Event #22039  t=22.595790567375  RegularNetworks.node[14].wlan[0].radio (IdealRadio, id=571)  on selfmsg receptionTimer (omnetpp::cMessage, id=453164)
INFO (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Reception ended: ignoring (inet::physicallayer::RadioFrame)11 - UDPBasicAppData-0 WHOLE as IdealReception, power = UNDETECTABLE, transmissionId = 3831, receiverId = 74, startTime = 22.59570938219, endTime = 22.595790567375, preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0)
DEBUG (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Listening with IdealListening, receiverId = 74, startTime = 22.595790567375, endTime = 22.595790567376, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0) on medium by (inet::physicallayer::Radio)radio, antenna = { IsotropicAntenna }, transmitter = { IdealTransmitter, communicationRange = 500 m }, receiver = { IdealReceiver, ignoring interference } results in ListeningDecision, impossible, listening = { IdealListening }

I think this is normal and it happened a few times. My guess is, that the following log shows the error:

> ** Event #21307  t=22.096806461254  RegularNetworks.node[14].wlan[0].radio (IdealRadio, id=571)  on 11 - UDPBasicAppData-0 (inet::physicallayer::RadioFrame, id=451688)
DEBUG (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Receiving IdealTransmission, communicationRange = 500 m, interferenceRange = 500 m, detectionRange = 500 m, id = 3817, transmitterId = 73, startTime = 22.096804793434, endTime = 22.096885978619, startPosition = (6750, 100, 0), preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, endPosition = (6750, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0) from medium by (inet::physicallayer::Radio)radio, antenna = { IsotropicAntenna }, transmitter = { IdealTransmitter, communicationRange = 500 m }, receiver = { IdealReceiver, ignoring interference } arrives as IdealReception, power = RECEIVABLE, transmissionId = 3817, receiverId = 74, startTime = 22.096806461254, endTime = 22.096887646439, preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0)
INFO (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Reception started: not attempting (inet::physicallayer::RadioFrame)11 - UDPBasicAppData-0 WHOLE as IdealReception, power = RECEIVABLE, transmissionId = 3817, receiverId = 74, startTime = 22.096806461254, endTime = 22.096887646439, preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0)
** Event #21326  t=22.096845805772  RegularNetworks.node[14].wlan[0].radio (IdealRadio, id=571)  on selfmsg receptionTimer (omnetpp::cMessage, id=451624)
DEBUG (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Receiving IdealTransmission, communicationRange = 500 m, interferenceRange = 500 m, detectionRange = 500 m, id = 3816, transmitterId = 75, startTime = 22.096762952767, endTime = 22.096844137952, startPosition = (7750, 100, 0), preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, endPosition = (7750, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0) from medium by (inet::physicallayer::Radio)radio, antenna = { IsotropicAntenna }, transmitter = { IdealTransmitter, communicationRange = 500 m }, receiver = { IdealReceiver, ignoring interference } arrives as IdealReception, power = RECEIVABLE, transmissionId = 3816, receiverId = 74, startTime = 22.096764620587, endTime = 22.096845805772, preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0) and results in ReceptionDecision, possible, attempted, successful
INFO (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Reception ended: successfully for (inet::physicallayer::RadioFrame)8 - UDPBasicAppData-1 WHOLE as IdealReception, power = RECEIVABLE, transmissionId = 3816, receiverId = 74, startTime = 22.096764620587, endTime = 22.096845805772, preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0)
DEBUG (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Receiving IdealTransmission, communicationRange = 500 m, interferenceRange = 500 m, detectionRange = 500 m, id = 3816, transmitterId = 75, startTime = 22.096762952767, endTime = 22.096844137952, startPosition = (7750, 100, 0), preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, endPosition = (7750, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0) from medium by (inet::physicallayer::Radio)radio, antenna = { IsotropicAntenna }, transmitter = { IdealTransmitter, communicationRange = 500 m }, receiver = { IdealReceiver, ignoring interference } arrives as IdealReception, power = RECEIVABLE, transmissionId = 3816, receiverId = 74, startTime = 22.096764620587, endTime = 22.096845805772, preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0) and results in ReceptionResult, indication = 0x5f77550
INFO (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Sending up (inet::IdealMacFrame)8 - UDPBasicAppData-1
DEBUG (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Listening with IdealListening, receiverId = 74, startTime = 22.096845805772, endTime = 22.096845805773, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0) on medium by (inet::physicallayer::Radio)radio, antenna = { IsotropicAntenna }, transmitter = { IdealTransmitter, communicationRange = 500 m }, receiver = { IdealReceiver, ignoring interference } results in ListeningDecision, possible, listening = { IdealListening }
INFO (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Changing radio reception state from RECEIVING to BUSY.
INFO (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Changing radio received signal part from WHOLE to NONE.
** Event #21328  t=22.096845805772  RegularNetworks.node[14].wlan[0].mac (IdealMac, id=570)  on 8 - UDPBasicAppData-1 (inet::IdealMacFrame, id=451731)
INFO (IdealMac)RegularNetworks.node[14].wlan[0].mac: Passing up contained packet `8 - UDPBasicAppData-1' to higher layer
** Event #21351  t=22.096887646439  RegularNetworks.node[14].wlan[0].radio (IdealRadio, id=571)  on selfmsg receptionTimer (omnetpp::cMessage, id=451712)
INFO (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Reception ended: ignoring (inet::physicallayer::RadioFrame)11 - UDPBasicAppData-0 WHOLE as IdealReception, power = RECEIVABLE, transmissionId = 3817, receiverId = 74, startTime = 22.096806461254, endTime = 22.096887646439, preambleDuration = 0, headerPosition = 0, dataPosition = 0.000081185185, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0), startOrientation = (0, 0, 0), endOrientation = (0, 0, 0)
DEBUG (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Listening with IdealListening, receiverId = 74, startTime = 22.096887646439, endTime = 22.09688764644, startPosition = (7250, 100, 0), endPosition = (7250, 100, 0) on medium by (inet::physicallayer::Radio)radio, antenna = { IsotropicAntenna }, transmitter = { IdealTransmitter, communicationRange = 500 m }, receiver = { IdealReceiver, ignoring interference } results in ListeningDecision, impossible, listening = { IdealListening }
INFO (IdealRadio)RegularNetworks.node[14].wlan[0].radio: Changing radio reception state from BUSY to IDLE.

**Comment by levy** [comment]
I don't see the bug there, search for "Reception started:" and "Reception ended:" and look for 'attempting', 'ignoring' or 'successfully'. AFAICT, there's only 1 packet which is received correctly, it's the '8 - UDPBasicAppData-1', but the reception start is missing from the log.

**Comment by fastriker** [comment]
You are right. The mac layer don't get the packet 11 - UDPBasicAppData-0, so I searched for this packet in the log. The first copied piece is typical in the log and appear a few times. The second is unique. The successful reception of 8 - UDPBasicAppData-1 between the other logs is noticeable. (I found the piece of log in my first comment the same way.) I can't say if this is correct or not - my knowledge about the code is not deep enough. However the reception of 11 - UDPBasicAppData-0 is never successful in the log. Is this a valid behaviour in IdealWirelessNic?

**Comment by levy** [comment]
The radio is only capable of receiving one signal at a time. The ignoreInterference parameter only tells that interfering signals should be ignored, and collision is impossible. But event if ignoreInterference is true, it might happen that some signal is not received. This is the case for all signals that arrive at a moment when the radio is already receiving another signal. In that moment, there are two things we can do, we either switch to the new signal (capture) or stick with the old one (ignore). Does it explain the behavior for you?

**Comment by fastriker** [comment]
Yes, that make it clear for me - thank you for the support. My expectation was different  because of the following comment in the IdealWirelessNic.ned:

> There are no collisions -- a radio can simultaneously receive any number of frames, and also transmit a single frame at the same time.

**Comment by levy** [comment]
That's a false statement, thanks for pointing out.
