### ISSUE TITLE
Can't compile INET 3.4 without Omnet++ 5.0 GUI

### ISSUE THREAD

**Issue by fastriker** [inet-framework/inet#211]
I can't compile INET 3.4 without Omnet++ 5.0 GUI. I deactivate the GUIs with deleting `WITH_TKENV=yes` and `WITH_QTENV=yes` in the configure.user file of Omnet++ (the machine has no GUI). I think the problem is caused in the new visualization features of INET. It would be nice if there is a similar switch to turn of this features to run a INET simulation on machines without GUI possibility’s. 

> Creating shared library: ../out/gcc-debug//src/libINET.so
/usr/bin/ld: cannot find -lOpenThreads
/usr/bin/ld: cannot find -losg
/usr/bin/ld: cannot find -losgText
/usr/bin/ld: cannot find -losgDB
/usr/bin/ld: cannot find -losgEarth
/usr/bin/ld: cannot find -losgEarthUtil

**Comment by rhornig** [comment]
Setting WITH_OSG=no in OMNeT's conigure.user file and reconfiguring/building omnet should work.
