### ISSUE TITLE
Compile error with i686-w64-mingw32: #define interface struct

### ISSUE THREAD

**Issue by Jonny007-MKD** [inet-framework/inet#214]
Hi,
today I upgraded OMNeT++ on my 64bit Windows machine to 5.0. Now I'm trying to compile inet 3.4.0 (actually current master: aa629c4c9f181044c1579eebf052aa5f7037d44c) using the MingWEnv . This is the error I get:

```
make[1]: Entering directory '/c/workspace/inet/src'
*** COMPILING with:
clang++ -c -std=c++11 -DWITH_QTENV -DWITH_OSG -DWITH_TKENV -DHAVE_PCAP -DXMLPARSER=libxml -DWITH_PARSIM -DWITH_NETBUILDER  -g -Wall   -isystem /usr/include -isystem /mingw32/include -Wno-deprecated-register -fno-stack-protector  -Wno-overloaded-virtual -include inet/common/precompiled.h -DWITH_TCP_COMMON -DWITH_TCP_INET -DWITH_IPv4 -DWITH_UDP -DWITH_RTP -DWITH_DHCP -DWITH_ETHERNET -I. -IC:/OMNeT/include
*** LINKING with:
clang++ -shared  -Wl,--whole-archive  -Wl,--no-whole-archive -L"C:/OMNeT/lib/gcc" -L"C:/OMNeT/lib" -loppenvird -loppsimd -lwsock32 -lstdc++  -losg -losgGA -losgViewer -losgQt -lOpenThreads -losgEarth -losgEarthUtil -Wl,--enable-auto-import -L/usr/bin -L/usr/lib -L/mingw32/lib -Wl,-rpath,C:/OMNeT/lib -Wl,-rpath,C:/OMNeT/tools/win32/lib -Wl,-rpath,.
Compiling...
inet/networklayer/configurator/ipv4/IPv4NetworkConfigurator.cc
inet/networklayer/configurator/ipv4/IPv4NetworkConfigurator.cc:335:17: error: expected unqualified-id
    for (auto & interface : interfaces) {
                ^
C:\OMNeT\tools\win32\mingw32\i686-w64-mingw32\include\rpc.h:12:19: note: expanded from macro 'interface'
#define interface struct
                  ^
```

mingw is using `interface` so it cannot be used as variable name. The same is true for other files. Here is a list for all files where I renamed the `interface` variable:
- inet/networklayer/configurator/ipv4/IPv4NetworkConfigurator.cc
- inet/networklayer/ipv4/IGMPv2.cc
- inet/networklayer/ipv4/IGMPv3.h and .cc
- inet/networklayer/generic/GenericRoute.h
- inet/physicallayer/common/packetlevel/RadioMedium.cc
- inet/routing/pim/modes/PIMSM.h and .cc
- inet/routing/ospfv2/router/OSPFArea.cc

**Comment by rhornig** [comment]
This is already fixed in master so it will be part of INET 3.5
