### ISSUE TITLE
HttpBrowserBase bug

### ISSUE THREAD

**Issue by Jackal93** [inet-framework/inet#219]
This component of httptools has the following bug:
in method handleSelfActivityStart(), the pointer rdActivityLength is used without first checking for nullptr.

Also, the following code appears twice:
86400.0 - rdActivityLength->draw()
and its value used as a time delta to schedule a new event. The problem is that this value can turn out to be negative, as draw() can return a number > 86400.0 with non zero probability, so this would cause attempting to schedule an event in the past.
This is true even using the default parameters suggested in the config file, i.e.:
<activityPeriod type='normal' mean='43200' sd='10800' min='7200') />

**Comment by ZoltanBojthe** [comment]
fixed
