### ISSUE TITLE
Linker error with latest INET Github version under OMNeT 5 on Windows

### ISSUE THREAD

**Issue by michaelkirsche** [inet-framework/inet#223]
Compiling (and linking) the INET 3.4 release (taken from the zip-file from the Website) works fine under Windows with OMNeT 5.

But the Github Version does not link successfully under Windows.
The linker process exists with errors during the linking of libINET.dll.

Here's the last part of the compilation log with the errors:

> Creating shared library: ../out/gcc-debug/src/libINET.dll
.tmplib10928(OSGUtils.o): In function `ZN4inet3osg10createTextEPKcRKNS_5CoordERKN7omnetpp7cFigure5ColorE':
D:\Repositories\inet-git\src/inet/common/OSGUtils.cc:214: undefined reference to `_imp___ZN7osgText4TextC1Ev'
D:\Repositories\inet-git\src/inet/common/OSGUtils.cc:215: undefined reference to `_imp___ZN7osgText8TextBase8setColorERKN3osg5Vec4fE'
D:\Repositories\inet-git\src/inet/common/OSGUtils.cc:216: undefined reference to `_imp___ZN7osgText8TextBase16setCharacterSizeEf'
D:\Repositories\inet-git\src/inet/common/OSGUtils.cc:217: undefined reference to `_imp___ZN7osgText8TextBase7setTextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
D:\Repositories\inet-git\src/inet/common/OSGUtils.cc:218: undefined reference to `_imp___ZN7osgText8TextBase11setPositionERKN3osg5Vec3fE'
.tmplib10928(OSGUtils.o): In function `ZN5osgDB13readImageFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
D:/omnetpp-5.0/tools/win32/mingw32/include\osgDB/ReadFile:82: undefined reference to `_imp___ZN5osgDB8Registry8instanceEb'
D:/omnetpp-5.0/tools/win32/mingw32/include\osgDB/ReadFile:82: undefined reference to `_imp___ZN5osgDB13readImageFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_7OptionsE'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:803: recipe for target '../out/gcc-debug/src/libINET.dll' failed
make[1]: *** [../out/gcc-debug/src/libINET.dll] Error 1

It doesn't matter which INET Project features are enabled, linking error always occurs in the Github version from the master branch.

Best,
Michael

**Comment by rhornig** [comment]
Hmm. Just tried to build inet master with omnetpp-5.0 and it was successful. Make sure that your path does not contain any installation of open scene graph. The mingw linker can pick up a dll file from the path and link against it unintentionally.

**Comment by michaelkirsche** [comment]
No OpenSceneGraph installation on my system. I'll try it with a completely fresh OMNeT / INET installation once again to see if I can reproduce it.

**Comment by rhornig** [comment]
Make sure that other omnet installation is not in the path either. (especially not the 5.1tp version)

**Comment by michaelkirsche** [comment]
Fresh installation on a different drive, nothing OMNeT related in the $PATH, no OpenSceneGraph installation on the system. Same error.

Here's the linker invocation with some extra infos (-v):

> Creating shared library: ../out/gcc-debug//src/libINET.dll
> clang version 3.7.0 (tags/RELEASE_370/final)
> Target: i686-w64-windows-gnu
> Thread model: posix
>  "V:\\omnetpp-5.0\\tools\\win32\\mingw32\\bin\\ld.exe" -m i386pe --shared -Bdynamic -e _DllMainCRTStartup@12 --enable-auto-image-base -o ../out/gcc-debug//src/libINET.dll "V:\\omnetpp-5.0\\tools\\win32\\mingw32\\i686-w64-mingw32\\lib\\dllcrt2.o" "V:\\omnetpp-5.0\\tools\\win32\\mingw32\\lib\\gcc\\i686-w64-mingw32\\5.2.0\\crtbegin.o" -LV:/omnetpp-5.0/lib/gcc -LV:/omnetpp-5.0/lib -LV:/omnetpp-5.0/tools/win32/usr/bin -LV:/omnetpp-5.0/tools/win32/usr/lib -LV:/omnetpp-5.0/tools/win32/mingw32/lib "-LV:\\omnetpp-5.0\\tools\\win32\\mingw32\\lib\\gcc\\i686-w64-mingw32\\5.2.0" "-LV:\\omnetpp-5.0\\tools\\win32\\mingw32\\i686-w64-mingw32\\lib" "-LV:\\omnetpp-5.0\\tools\\win32\\mingw32\\lib" "-LV:\\omnetpp-5.0\\tools\\win32\\mingw32\\i686-w64-mingw32/sys-root/mingw/lib" --no-as-needed --whole-archive .tmplib11236 --no-whole-archive -loppenvird -loppsimd -lwsock32 -lstdc++ -losg -losgGA -losgViewer -losgQt -lOpenThreads -losgEarth -losgEarthUtil --enable-auto-import -rpath V:/omnetpp-5.0/lib -rpath V:/omnetpp-5.0/tools/win32/lib -rpath . -lstdc++ -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt "V:\\omnetpp-5.0\\tools\\win32\\mingw32\\lib\\gcc\\i686-w64-mingw32\\5.2.0\\crtend.o"
> .tmplib11236(OSGUtils.o): In function `ZN4inet3osg10createTextEPKcRKNS_5CoordERKN7omnetpp7cFigure5ColorE':
> V:\omnetpp-5.0\git\inet\src/inet/common/OSGUtils.cc:214: undefined reference to `_imp___ZN7osgText4TextC1Ev'
> V:\omnetpp-5.0\git\inet\src/inet/common/OSGUtils.cc:215: undefined reference to `_imp___ZN7osgText8TextBase8setColorERKN3osg5Vec4fE'
> V:\omnetpp-5.0\git\inet\src/inet/common/OSGUtils.cc:216: undefined reference to `_imp___ZN7osgText8TextBase16setCharacterSizeEf'
> V:\omnetpp-5.0\git\inet\src/inet/common/OSGUtils.cc:217: undefined reference to `_imp___ZN7osgText8TextBase7setTextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
> V:\omnetpp-5.0\git\inet\src/inet/common/OSGUtils.cc:218: undefined reference to `_imp___ZN7osgText8TextBase11setPositionERKN3osg5Vec3fE'
> .tmplib11236(OSGUtils.o): In function `ZN5osgDB13readImageFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
> V:/omnetpp-5.0/tools/win32/mingw32/include\osgDB/ReadFile:82: undefined reference to `_imp___ZN5osgDB8Registry8instanceEb'
> V:/omnetpp-5.0/tools/win32/mingw32/include\osgDB/ReadFile:82: undefined reference to `_imp___ZN5osgDB13readImageFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_7OptionsE'
> clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
> Makefile:409: recipe for target '../out/gcc-debug//src/libINET.dll' failed
> make[1]: *** [../out/gcc-debug//src/libINET.dll] Error 1
> make[1]: Leaving directory '/v/omnetpp-5.0/git/inet/src'
> Makefile:4: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by michaelkirsche** [comment]
Another follow up on this topic.
The error that I pointed out occurs as long as the visualizer project feature is not enabled (and thus not compiled). It actually has nothing to do with the OMNeT or INET version.
The undefined references in OSGUtils.cc disappear as soon as the "Visualization" project feature gets enabled.

So my issue can be closed, but the dependencies of the INET project features should be rechecked again.
There seem to be many dependencies to "Visualization", which are not marked under "requires" in the .oppfeatures file.
Another example of a missing project feature dependency is the ASPK radio feature that is required for IEEE 802.15.4, but not listed under "requires", just like "Visualization".

Shall I open a new issue for the missing .oppfeatures dependencies?

Best, 
Michael

**Comment by michaelkirsche** [comment]
On a side note, it still does only occur on Windows. Under Linux, the "Visualization" project feature can be left disabled and INET still compiles (for example) the 802.15.4 code with necessary requirements (APSK radio included).

**Comment by tillsteinbach** [comment]
I can confirm the problem with the dependencies for macOS as well. I opened #234 as I was not aware that this bug may be somehow related.

**Comment by rhornig** [comment]
Added some extra ifdefs so OSGUtils and OSGScene classes are not compiled when Visualizer is disabled.

**Comment by tienthanh0505** [comment]
@michaelkirsche hello sir, i'm having the same problems as you was. Can you tell me how to enable he visualizer folder. I'm struggling finding it. thank you!

**Comment by michaelkirsche** [comment]
Simply by going into the INET project properties (right click on your INET project and then select properties or use the Shortcut ALT+ENTER), then select OMNET++ and Project Features and then scroll down, select the features that you require (for example visualization) and then apply and close. Then "clean" and "make" your INET project.
