### ISSUE TITLE
Class Ieee80211HTMCSTable wrong modulation parameters

### ISSUE THREAD

**Issue by gutipeon** [inet-framework/inet#227]
The modulation on streams belonging to MCS 13, 21 and 29 in both 20 MHz and 40 MHz band is, as far as I understand, wrong. Some of them were set to QAM16, while in reality they should be QAM64. More info https://en.wikipedia.org/wiki/IEEE_802.11n-2009

A possible patch is as follows: https://github.com/gutipeon/inet/pull/1/files#diff-2966c7e71873b37a2288ce12ab8a727f

**Comment by Benmartin92** [comment]
You are right, please open a pull request.

Thanks,
Ben

**Comment by levy** [comment]
I reopen this issue until the pull request is merged so that it won't get lost.

**Comment by levy** [comment]
Merged.
