### ISSUE TITLE
PacketDrill doesn't compile in windows

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#230]
The feature Packet drill doesn't compile in windows.
Tested with omnet 5.1 pre2 and the latest version of inet master branch download from github

Error Messages.

inet/applications/packetdrill/parser.cc:204:6: error: redefinition of 'SID'
     SID = 393,
     ^
C:\omnetpp-5.1pre2\tools\win64\mingw64\x86_64-w64-mingw32\include\winnt.h:2609:7: note: previous definition is here
    } SID,*PISID;
      ^
inet/applications/rtpapp/RTPApplication.cc
inet/applications/packetdrill/PacketDrillUtils.cc:78:7: error: use of undeclared identifier 'F_GETFL'
    { F_GETFL,                          "F_GETFL"                         },
      ^
inet/applications/packetdrill/PacketDrillUtils.cc:79:7: error: use of undeclared identifier 'F_SETFL'
    { F_SETFL,                          "F_SETFL"                         },
      ^
In file included from lexer.l:58:
inet/applications/packetdrill/parser.h:177:6: error: redefinition of 'SID'
     SID = 393,
     ^
C:\omnetpp-5.1pre2\tools\win64\mingw64\x86_64-w64-mingw32\include\winnt.h:2609:7: note: previous definition is here
    } SID,*PISID;
      ^

**Comment by rhornig** [comment]
Thanks for reporting. It should be fixed now.
