### ISSUE TITLE
Error with the linker in windows

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#231]
Inet framework doesn't have the socket library included in the directives.
Possible solution 
In makefrag, include this

ifeq ($(OS),Windows_NT)
    LIBS += -lws2_32
endif

**Comment by rhornig** [comment]
Yes, indeed. OMNeT++ 5.1 no longer adds winsock2 to the opp libraries. Each model should add that library on it's own if needed.

The proper way is to test for the PLATFORM variable so coross compiling will work too.

```
ifeq ($(PLATFORM),win32.x86_64)
  OMNETPP_LIBS += -lwsock32
endif
```
