### ISSUE TITLE
INET feature dependencies

### ISSUE THREAD

**Issue by tillsteinbach** [inet-framework/inet#234]
As the 3.5 version is about to get released it would be really great to get the feature dependencies right. I guess there are a lot of combinations that cause trouble, I experience linker errors with only these enabled in the current master: 
- Ethernet
- IEEE 802.1d
- IPv4
- IPv6
- TCP
- UDP
- SCTP

I don't have an idea how to reliably test that all dependencies are ok, but maybe we can define some sets of common feature configurations that get tested.

**Comment by rhornig** [comment]
There is a test script in tests/features which builds inet with all features enabled and then disabling every feature one by one and also by disabling everything and the enabling features one by one. We run the test on Linux and it seems to pass so maybe this is somehow platform related?

**Comment by rhornig** [comment]
Would you mind to try this:

https://github.com/inet-framework/inet/tree/topic/visualization-fix

I had to move around some code to make it work when OSG was present but VISUALIZATION feature was turned off. If it works I will merge it.

**Comment by rhornig** [comment]
I have updated the OSG specific code to be excluded if Visualizer is disabled. On long term we have to factor out the OsgCoordinate... class into a separate feature, but for now we just make it a part of the Visualization feature.

**Comment by tillsteinbach** [comment]
fixed my problem! Thanks!
