### ISSUE TITLE
ExternalInterfce is not compiling on Windows

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#241]
The ExternalInterface feature does not compile on Windows even if the PCAP library is detected. Several APIs are used that are not present in the windows version of pcap.

**Comment by michaelkirsche** [comment]
Seems like it is connected to the newer OMNeT 5.1 releases.
The 64-Bit MinGW version does not provide the pcap.h in its include path and the ./configure script does not search for it in the include paths anymore, thus it is not linked against the INET files.

**Comment by rhornig** [comment]
I have already added the necessary libs/headers to the omnet master and it already does detect the pcap library, but even after that the API difference will not allow to compile this with winpcap.

**Comment by michaelkirsche** [comment]
Ah okay, I only tested it with the released 5.1pre versions, which do not have the necessary libs and headers yet. Which pcap libraries did you add specifically? 
The main problem is hence that WinPCAP has still not been extended with the latest API version and features of libpcap, correct?

I saw a [Windows 10 PCAP port](http://www.win10pcap.org/) some time ago, but I am not sure, if they extended the API any further.

**Comment by michaelkirsche** [comment]
Or instead of Winpcap, this project might help out: https://github.com/nmap/npcap

**Comment by hsluoyz** [comment]
Welcome to use [Npcap](https://github.com/nmap/npcap)!

Any issues in usage please report it to: https://github.com/nmap/nmap/issues. Thanks!

**Comment by rhornig** [comment]
Thanks a lot for the tip. I will definitely check this next week.

**Comment by rhornig** [comment]
Thanks @hsluoyz 
I have taken a look at the npcap package and unfortunately it seems that the licensing does not allow us to bundle the package with the OMNeT++ toolchain. On the other hand, the winpcap win10pcap package is too old and does not support the necessary API so at the moment it seems that we cannot support the ExternalInterface feature on Windows out of box...

Users can install npcap manually and tweak the build process to detect/use it, but we can't make this automatic. Any idea?

**Comment by hsluoyz** [comment]
Nmap mailing list is: dev@nmap.org, you can ask about the licensing there.Since OMNeT++ is also an open-source project, I think the process will be easy:)

**Comment by michaelkirsche** [comment]
What about changing the manual to recommend using NPCAP in "WinPCAP" compilation mode (where the DLLs of WinPCAP are mimicked) and keep the detection part and simply use the external interface code that works with the newest API (from NPCAP)?

**Comment by hsluoyz** [comment]
I recommend you to support the native Npcap mode like here: https://github.com/chmorgan/sharppcap/issues/15. So OMNeT++ can use Npcap no matter whether the WinPcap Compatible Mode option is checked. Adding the support is very easy, just call ``SetDllDirectory()`` to add the ``C:\Windows\System32\Npcap`` path to the DLL search paths.

**Comment by rhornig** [comment]
Thanks. Unfortunately OMNeT++ also have a commercial version (OMNEST) so the case is not so clear cut. I'm thinking about removing all the pcap dependencies from OMNET and put the detection/configuration into the INET project. If we cannot distribute a proper pcap library with the OMNeT++ version anyway and the user have to install it manually, it would be probably better to configure that in INET (i.e. in makefrag, just like NSC ot ffmpeg). @michaelkirsche what do you think?

**Comment by michaelkirsche** [comment]
@rhornig That's probably the best idea. The example with the NSC is fitting, I'd say it's the best compromise to support things like external interfaces in INET under both Windows and Linux.
If the API from NPCAP under Windows mirrors the libpcap API under Linux closely, this might reduce the need for OS-depending (Windows/Linux) code for PCAP/externalInterfaces.

**Comment by rhornig** [comment]
Ok. I will go ahead and remove the PCAP dependency in OMNeT++. I still leave this issue open until INET properly handles the ExternalInterface feature on Windows, too.

**Comment by rhornig** [comment]
I still keep this issue open until we document how the NPCAP library should be installed on windows.

**Comment by rhornig** [comment]
In INET 4.x the emulation support has been rewritten to use Linux network namespaces. This is now a Linux ONLY feature, so all PCAP usage have been removed.
