### ISSUE TITLE
NetworkLayer and TestApplication for 802154A from MiXiM Missing

### ISSUE THREAD

**Issue by mridolfi** [inet-framework/inet#242]
Since MiXiM is now deprecated, I am trying to use INET to simulate a netwrok with 802.15.4a (UWB) nodes. MiXiM had a simple example from which it was easy to build and extend anything.

I don't find the equivalent 'networkLayer' and 'applicationLayer' here in INET.
I cannot define an application module to have to nodes communicating.

For example, it would be nice to have a similar example with two UWB hosts just TX/RX messages.

**Comment by mridolfi** [comment]
I followed tutorial Wireless A of INET and I've managed to have things working. Just using the right NIC and RadioMedium

**Comment by rhornig** [comment]
Yep. We would love to have something similar to the Wireless tutorial, but geared towards sensor networks. We just don't have the expertise (domain knowledge of sensor networks). We could find some student to actually do the work, but we would need a good and detailed step by step 'screenplay' what it should contain.
