### ISSUE TITLE
Class not found Error

### ISSUE THREAD

**Issue by mridolfi** [inet-framework/inet#247]
`<!> Error in module (inet::physicallayer::RadioMedium) Wireless.radioMedium (id=4) during network setup: Class "inet::physicallayer::UWBIRStochasticPathLoss" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel().`

And if I use Define_Module(UWBIRStochasticPathLoss) in _UWBIRStochasticPathLoss.cc_ I get the following error:
`invalid new-expression of abstract class type ‘inet::physicallayer::UWBIRStochasticPathLoss`

How can I use this class?

**Comment by mridolfi** [comment]
From `IPathLoss.h`, it was missing the implementation of `virtual double computePathLoss(const ITransmission *transmission, const IArrival *arrival) const override;`

**Comment by levy** [comment]
It seems that this is not yet fixed in master.

**Comment by levy** [comment]
Fixed in master by changing base class.
