### ISSUE TITLE
TCPEchoApp never sends back actual input

### ISSUE THREAD

**Issue by LongHairedHacker** [inet-framework/inet#263]
I've been using the the TCPEchoApp in one of my simulations and I've noticed some rather odd behaviour.
The simulation contains a simple network, two StandardHosts connected via a EtherSwitch,
running the TCPEchoApp and the TCPSessionApp to generate some traffic.
With an echoFactor > 1 the echoed packets have the correct length (input length times echo factor),
but instead of being filled with a 'stretched out' version of the input data,
they only contain the letter 't' repeated until the desired length is reached.

https://github.com/inet-framework/inet/blob/48f864cbe5ee4a6879fa7083eedb4e799a280ead/src/inet/applications/tcpapp/TCPEchoApp.cc#L134

Looking at this code I'd expect something like this for echoFactor = 2:
Incoming packet: "Hello World"
Outgoing packet: "HHeelloo  Woorrlldd"
In reality I get "tttttttttttttttttttttt"

After poking around in the code for a while, I noticed that the dynamic_cast in line 125
`RawPacket *baMsg = dynamic_cast<RawPacket *>(pkt);`
always fails (at least for my simulation) and thus returns a nullpointer.

Is this the expected behaviour or a bug?

**Comment by levy** [comment]
Did you set dataTransferMode to bytestream?

**Comment by LongHairedHacker** [comment]
Thank you.

I didn't know about that particular setting, but now my simulation works as expected.
Also the cast returning null makes perfect sense now.

Not a bug, I was holding it wrong.
