### ISSUE TITLE
CSMA.cc MAC registers Interfaces in the wrong initstage.

### ISSUE THREAD

**Issue by ApolloLV** [inet-framework/inet#267]
/**
* Initialization of link-layer protocols. Automatic MAC addresses are
* assigned; interfaces are registered in InterfaceTable.
*/
INITSTAGE_LINK_LAYER = 4,

However, CSMA.cc calls the functions initializeMACAddress() and registerInterface() in INITSTAGE_LOCAL.

**Comment by levy** [comment]
It seems that many other MAC protocols do the same, they the assign MAC address and register the interface in INITSTAGE_LOCAL.

**Comment by ZoltanBojthe** [comment]
fixed, close
