### ISSUE TITLE
Showcase wireless-pathloss doesn't generate data

### ISSUE THREAD

**Issue by GitNorb** [inet-framework/inet#273]
After running the simulation the charts in Field.anf stay empty. The data which is needed does not seem to be collected. If I type in the filter expression "module(PathLossShowcase.destination.wlan[0].radio.receiver) AND name(receptionPower:vector)"  I get no data.

![bild1](https://user-images.githubusercontent.com/23292768/32538614-dc556662-c466-11e7-9291-5d3ef8a56ce5.png)

Inet 3.6.2
Omnet 5.2

**Comment by adamgeorge309** [comment]
It's been fixed. It should work now, if you use the inet master and showcases master branches. Thanks for reporting this issue!

**Comment by GitNorb** [comment]
-> solved
