### ISSUE TITLE
INET is beeing built in release version by default

### ISSUE THREAD

**Issue by jensdrenhaus** [inet-framework/inet#279]
In contrast to the explanation in the INSTALL file, the framework is beening build in release version.
I think it is due to the default definition in omnets's Makefile.inc (omnet 5.2).
Depending on your intentinon, you should edit INET's Makefile or bring INSTALL file into line.

**Comment by torokati44** [comment]
You are right, thank you. The default MODE indeed changed from debug to release in OMNeT++ 5.2. The INSTALL file should be updated in my opinion.

**Comment by levy** [comment]
I updated the INSTALL file. Thank you!
