### ISSUE TITLE
Ieee80211: confusion about difsTime's unit

### ISSUE THREAD

**Issue by avarga** [inet-framework/inet#280]
In inet/linklayer/ieee80211/mac/channelaccess/Dcaf.ned, difsTime is defined with @unit(s):
double difsTime @unit("s") = default(-1s);

Then it is read into an int in inet/linklayer/ieee80211/mac/channelaccess/Dcaf.cc as:
int difs = par("difsTime");

One of the two needs to be changed...

**Comment by avarga** [comment]
Looks like it needs to be simtime_t instead of int in the C++ code.

**Comment by levy** [comment]
It seems you have fixed this, so I'm closing it.
