### ISSUE TITLE
An issue in AODV

### ISSUE THREAD

**Issue by h-hosseini** [inet-framework/inet#293]
When we (Dr. Elisa Rojas and I) worked on AODV, we notice the unusual removal of a RREQ packet in AODV. 
In lines 789-799 of this file: AODVRouting.cc
https://github.com/inet-framework/inet/blob/master/src/inet/routing/aodv/AODVRouting.cc
Two variables "Originator IP Address" and "RREQ ID" should be considered for deleting a message. But according to line 66 of this file: AODVRouting.h
https://github.com/inet-framework/inet/blob/master/src/inet/routing/aodv/AODVRouting.h
Only the variable of "RREQ ID" is compared as the key of the map. So if two different nodes send messages with the same "RREQ ID", one of them is stored as the key and the rest are not saved. Then, in lines 794 and 795 of this file:

https://github.com/inet-framework/inet/blob/master/src/inet/routing/aodv/AODVRouting.cc

The comparison is only based on the identifiers and the message by the same "RREQ ID" was deleted(without checking "Originator IP Address")!
Our solution to this problem is as follows:
           if (lhs.originatorAddr < rhs.originatorAddr)
              return true;
            else if (lhs.originatorAddr > rhs.originatorAddr)
              return false;
            else
              if (lhs.rreqID < rhs.rreqID)
                  return true;
              else return false;
Instead of:
 return lhs.rreqID < rhs.rreqID;
line 66 of this file: AODVRouting.h
Is this an issue in AODV really? and, is our solution ok or it affects something else?

**Comment by levy** [comment]
Thank you for reporting this issue. I will look into this before INET 4.0 is released.

**Comment by h-hosseini** [comment]
Dear Levente,
Thank you very much for your response.

**Comment by ManiAm** [comment]
I also confirm this bug.

According to RFC 3561, each RREQ message is uniquely identified using the <PREQ ID, Originator IP Address> tuple. The PREQ ID is a number that is maintained locally by each originating node and is incremented by one from the last used RREQ ID. So both PREQ ID and the originator IP address should be considered in the 'RREQIdentifierCompare' predicate.

**Comment by levy** [comment]
This bug has been fixed by merging a pull request. Thank you!
