### ISSUE TITLE
Online documentation is missing the default doxygen style.

### ISSUE THREAD

**Issue by DarkDrek** [inet-framework/inet#294]
The documentation at https://omnetpp.org/doc/inet/api-current/doxy/index.html is missing the default doxygen style. Console error `Failed to load resource: the server responded with a status of 404 () doxygen.css`. Locally build documentation is similarly affected.

You should use the doxygen option `HTML_EXTRA_STYLESHEET` to provide stylesheet overrides and remove `HTML_STYLESHEET`.

**Comment by rhornig** [comment]
The online doc is now using a unified material stile along with the tutorials and showcases.
