### ISSUE TITLE
Dumping routes in the IPv4 configurator

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#299]
This is a minor issue in the configurator, but I decided to share it here:

When dumpRoutes is set to 'true', the routing table of hosts and routers are printed in the output log,

`*.configurator.dumpRoutes = true`

But the last column (metric) does not have proper spacing:

![2018-03-14_10-57-38](https://user-images.githubusercontent.com/5473998/37421687-2a63b58e-2777-11e8-9c7f-20679b02da73.png)

**Comment by levy** [comment]
Thanks for the bug report!

**Comment by ZoltanBojthe** [comment]
Fixed, closed
