### ISSUE TITLE
Name for IEEE 802.15.4's Radio

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#302]
Narrowband is redundant in `Ieee802154NarrowbandScalarRadio` name based on the naming convention for other wireless radios. For example,

Ieee80211UnitDiskRadio
Ieee80211ScalarRadio
Ieee80211DimensionalRadio

So I guess for IEEE 802.15.4 it should be Ieee802154ScalarRadio.

**Comment by adamgeorge309** [comment]
There is also a wide-band version of IEEE 802.15.4, Ieee802154UwbIrRadio.

**Comment by ManiAm** [comment]
oops. I missed that module!

**Comment by levy** [comment]
In fact, you've got a point in the sense that in an ideal world there should be one IEEE 802.11 radio and one IEEE 802.15.4 radio despite all the different features that the standards provide. Unfortunately, the IEEE 802.15.4 implementation for the UWB-IR and narrowband variants are completely separate both in terms of C++ classes and NED types. However, this isn't true for the IEEE 802.11 implementation, where we have one big pile of C++ classes and NED types supporting all the different PHY and MAC features. To summarize, you are right in theory, but in practice I think it's better to leave things as they are now.
