### ISSUE TITLE
Using Slash notation for interface netmask

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#303]
Trivial Suggestion:

In the 'Interface' attribute of the IPv4 configurator, the network mask is specified using the dot-decimal notation like 255.255.255.x. One suggestion is to allow the user to use the slash notation too like /24 or /29. 

P.S. The network interface visualizer uses the slash notation in the GUI.

**Comment by levy** [comment]
This is a good idea, thank you! I leave this issue open to remind us to implement it one day.
