### ISSUE TITLE
Confusion in UnitDiskRadio

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#304]
The description of the UnitDiskRadio at the integration branch at [here ](https://github.com/inet-framework/inet/blob/integration/src/inet/physicallayer/unitdisk/UnitDiskRadio.ned) say:

>> // The idea behind this radio model is to describe transmissions with a few
>> // distance based parameters: communication range, interference range, and
>> // detection range. Whether the reception is successful or not, depends on the
>> // distance between the transmitter and the receiver. This model is similar to
>> // the **unit disk radio**, but it's also more general than that. The ideal model
>> // also supports an ideal communication channel where all transmissions are
>> // received sucessfully independent of distance and interfering transmissions.

What do you mean by 'this module is similar to the unit disk radio'?

**Comment by ManiAm** [comment]
Never mind. The new name of this module got me confused.

**Comment by levy** [comment]
This comment was written when this radio was called IdealRadio. The unit disk radio reference was talking about the widely known concept in the literature. We should update the documentation though. Thanks!
