### ISSUE TITLE
AODV 'Destination only' flag

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#307]
According to RFC 3561 (AODV):

    // A node generates a RREP if either:
    //
    // (i)       it is itself the destination, or
    //
    // (ii)      it has an active route to the destination, the destination
    //           sequence number in the node's existing route table entry
    //           for the destination is valid and greater than or equal to
    //           the Destination Sequence Number of the RREQ (comparison
    //           using signed 32-bit arithmetic), and the "destination only"
    //           ('D') flag is NOT set.

Checking the D flag is missing in the if statement:

https://github.com/inet-framework/inet/blob/0621c5e67fec4a514e18703344145cb0a5ef23c0/src/inet/routing/aodv/Aodv.cc#L896

Edit: if the D flag is set, the node should forward the RREQ message as before.

@Benmartin92

**Comment by levy** [comment]
This has been fixed by merging a pull request.
