### ISSUE TITLE
AODV / DYMO message name

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#308]
During simulation, AODV message names are shown like:

aodv::Rreq, aodv::Rrep, ...

Whereas, DYMO message names are shown like:

inet::dymo::Rreq, inet::dymo::Rrep, ...

The INET namespace is missing in AODV messages.

![2018-04-07_23-24-14](https://user-images.githubusercontent.com/5473998/38464011-259e1704-3abb-11e8-9b08-7c714562e1eb.png)

**Comment by ZoltanBojthe** [comment]
fixed. removed "inet::" from dymo packet name
