### ISSUE TITLE
DYMO-related information in a routing table entry

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#309]
The routing table that is populated by the AODV protocol shows the AODV-related fields as highlighted below:

![2018-04-05_23-46-19](https://user-images.githubusercontent.com/5473998/38407055-dccfbb7a-392c-11e8-9cb0-94acd8803af6.png)

But the routing table that is populated by the DYMO protocol lacks DYMO-related fields:

![2018-04-05_23-50-15](https://user-images.githubusercontent.com/5473998/38407167-4633412c-392d-11e8-965b-63881003528b.png)

Apparently overriding the << operator in the `src/inet/routing/dymo/DymoRouteData.cc` is missing.

**Comment by ZoltanBojthe** [comment]
fixed
