### ISSUE TITLE
INET3.6.4 compiling failure in Ubuntu 18.04

### ISSUE THREAD

**Issue by jasonj99** [inet-framework/inet#321]
I have problem compiling INET-3.6.4 within OMNET++5.3 in Ubuntu 18.04 box. It looks that INET could not found osgEarthUtil/ObjectLocator, but there is no such file in osgEarth 2.9 which comes from Ubuntu 18.04.
Will this issue be fixed in future, or should I install osgEarth 2.8 or earlier by hand in Ubuntu 18.04?

> inet/common/geometry/common/CoordinateSystem.cc:21:10: fatal error: osgEarthUtil/ObjectLocator: No such file or directory
>  #include <osgEarthUtil/ObjectLocator>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> Makefile:1330: recipe for target '../out/gcc-release/src/inet/common/geometry/common/CoordinateSystem.o' failed
> make[1]: *** [../out/gcc-release/src/inet/common/geometry/common/CoordinateSystem.o] Error 1
> make[1]: *** Waiting for unfinished jobs....

**Comment by torokati44** [comment]
The exact same problem was reported just a couple days ago in #314. Have you found that? Was it useful?

**Comment by jasonj99** [comment]
I'm sorry. I just searched the opened issue, not found the #314.
How can I close or delete the issue?
