### ISSUE TITLE
Display interface status

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#330]
[feature request]

Displaying the interface's status for a device would be a great time saver especially in debugging. For example, in the Cisco packet tracer software, a small green circle is shown for interfaces that are up.

![2018-05-11_19-27-58](https://user-images.githubusercontent.com/5473998/39952775-de804f56-5552-11e8-86b7-1de7fb397789.png)

I guess this would fit into visualizing interface status that monitors the status (up/down) of an interface and changes the color of the circle from green (up), gray (down), etc.

**Comment by levy** [comment]
I added a new string format directive (%t) to the visualizer which allows displaying the interface state (up/down) as text. This is not as nice as you suggested but it was easy to do and it also works for wireless interfaces. I hope this is good enough, so I'll close this.
