### ISSUE TITLE
No IPv4 address/route after link re-connect

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#332]
Consider a scenario where a link between two network nodes gets disconnected (using the scenario manager module) and then it is re-connected as shown below.

![2018-05-18_23-46-47](https://user-images.githubusercontent.com/5473998/40265962-10027f0a-5af7-11e8-8c54-7f5fcee93e7f.png)

issue 1: the IP address is not shown by the visualizer.
issue 2: Router2 does not add a new route (DIRECT IFACENETMASK) corresponding to the re-connected link into the routing table:

![2018-05-18_23-50-14](https://user-images.githubusercontent.com/5473998/40265980-79aa9ef6-5af7-11e8-8089-ebf18fdae9e4.png)

**Comment by levy** [comment]
Thanks for the bug report!

**Comment by ZoltanBojthe** [comment]
issue1 fixed

**Comment by ZoltanBojthe** [comment]
issue2 also fixed

**Comment by ZoltanBojthe** [comment]
issue2 also fixed
