### ISSUE TITLE
Segmentation Fault in IEEE 802.11 Visualizer

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#333]
IEEE 802.11 Visualizer causes a segmentation fault during disassociation. The segmentation fault occurs at this line:

https://github.com/inet-framework/inet/blob/6551c8079a70621986d51f7e2c43fa57979d8b19/src/inet/visualizer/base/Ieee80211VisualizerBase.cc#L167

To reproduce the error, you can use my scenario attached here:

[gettingStarted.tar.gz](https://github.com/inet-framework/inet/files/2028545/gettingStarted.tar.gz)

The SEGFAULT happens around event: 146,038

P.S. Probably the TODO: comment in that method is explaining why this error happens :)

**Comment by levy** [comment]
Fixed in integration.

**Comment by levy** [comment]
This and several other memory leaks have been fixed in master.
