### ISSUE TITLE
Strange Behavior in ScenarioManager

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#334]
I noticed another bug, this time in the scenarioManager module (I guess). In the same example scenario that I attached in my previous post (#333), change this line:

`*.scenarioManager.script = xmldoc("params_scenario.xml")`

To

`*.scenarioManager.script = xmldoc("params_scenario2.xml")`

And see what happens :)

**Comment by levy** [comment]
I've got an error: <!> Cannot evaluate parameter 'script': Cannot load 'params_scenario2.xml': File not found -- in module (inet::ScenarioManager) Network.scenarioManager (id=5), during network setup

This seems to be ok for me. What else am I supposed to get?

**Comment by ManiAm** [comment]
Please check this video I have uploaded into my drop box:

https://www.dropbox.com/s/7wjxp8lj7ssb16e/screen.mp4?dl=0

Check the animation pane after clicking 'ok' on the error window,

**Comment by levy** [comment]
It looks like 'Show layout process' is enabled in Qtenv's configuration dialog. I don't know how this is related to changing that parameter. Probably the error causes to skip the initalization phase (@torokati44 ?), so network nodes don't get positions assigned. This might be the reason why the automatic layouting kicks in. I don't know why the configuration option is enabled though, unless you actually enabled it.

**Comment by torokati44** [comment]
Yeah, this seems reasonable, @levy . The configuration error causes an exception that most likely interrupts / terminates the initialization process, so the submodule positions are never assigned.
