### ISSUE TITLE
Runtime error in general/pcaprecording Showcase

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#336]
The pcaprecording scenario assumes that a `results` folder is already created so that PCAP files can be saved in that folder. Since this assumption is not true (especially when you run the scenario for the first time), error is thrown.

Solution: Something like this?

https://github.com/inet-framework/inet/blob/7a17270421393182433815140c140f85694c3353/src/inet/networklayer/ipv4/RoutingTableRecorder.cc#L260

**Comment by levy** [comment]
Thanks for reporting this bug. I fixed this in the integration branch.
