### ISSUE TITLE
Initial Radio State in wlan interface

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#342]
I remember in the old MiXim [code](https://github.com/omnetpp/mixim/blob/22ee696cfeb2f195c81f8d41e69fbd77f0a20d12/src/base/phyLayer/BasePhyLayer.cc), the physical layer had a 'initialRadioState' parameter. There is no such parameter in the equivalent INET code. So apparently the radio always starts in the off state and it is the job of the mac module to set the initial state of the radio. For example, here is the line that IEEE 802.11 mac set the initial state of the radio to receiving mode.

https://github.com/inet-framework/inet/blob/f05777af4716dad7a404104018e4bd130b29bd35/src/inet/linklayer/ieee80211/mac/Ieee80211Mac.cc#L93

Do you think, defining a new parameter like `initialRadioState` in the [ieee80211Mac ](https://github.com/inet-framework/inet/blob/integration/src/inet/linklayer/ieee80211/mac/Ieee80211Mac.ned)is a good idea instead of hard-wiring it in the code? The default radio state is receiving as before, but the user might want to start the radio in the off state and switch to the receiving mode later on in the simulation.

**Comment by levy** [comment]
Yes, I think it would be a useful parameter in general, but we should call it initialRadioMode instead to be consistent with the rest of the API.

**Comment by ManiAm** [comment]
pull request #344
