### ISSUE TITLE
NED errors in the latest update to integration

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#345]
I noticed numerous NED errors in the latest commits to the integration branch regarding `nan` and `typename`. Do we need a new version of OMNET++ that is used internally?

![2018-06-05_9-24-13](https://user-images.githubusercontent.com/5473998/40991720-88ea12ba-68a9-11e8-8611-f49c22753207.png)

![2018-06-05_9-34-23](https://user-images.githubusercontent.com/5473998/40991725-8b3b29aa-68a9-11e8-941b-373040a0b43e.png)

**Comment by levy** [comment]
Unfortunately, yes, the latest INET needs the not yet released OMNeT++ 5.4
version.

**Comment by ManiAm** [comment]
Ok. Thanks for the quick reply. 
Looking forward to download OMNET++ 5.4p1 :)
