### ISSUE TITLE
Qtenv segmentation fault

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#351]
I updated OMNET++ and INET to the latest version today, but I get segmentation fault on simulation end.

To reproduce the error, you can run [this ](https://github.com/ManiAm/inet/tree/INETex/examples_INETex/gettingStarted/example1)scenario to like 1s and then close the Qtenv.

Edit: apparently any simulation scenario generates this SIGSEGV at the end.

![2018-06-15_1-07-57](https://user-images.githubusercontent.com/5473998/41457465-93bf6b36-7038-11e8-9294-9001a2d17c2c.png)

**Comment by torokati44** [comment]
Thanks for reporting, we have also come across this crash just now, identified the change that introduced it, and fixed it in Qtenv.

**Comment by torokati44** [comment]
Ah, you were two milliseconds faster, @levy! :smile:

**Comment by torokati44** [comment]
Until then, you can apply the fix manually, which is just adding

    && messageAnimator

as a third term in the `if` conditions in `Qtenv::componentMethodBegin` and `Qtenv::componentMethodEnd`.
