### ISSUE TITLE
Compilation and linking error if OSGEARTH is disabled

### ISSUE THREAD

**Issue by bourou01** [inet-framework/inet#353]
**1) Compilation error**
------------------------------------------

[abdullatif@HOUDA-LINUX c1]$ git clone --recursive https://github.com/inet-framework/inet
[abdullatif@HOUDA-LINUX c1]$ cd inet/
[abdullatif@HOUDA-LINUX inet]$ make makefiles
[abdullatif@HOUDA-LINUX inet]$ make

inet/visualizer/physicallayer/TracingObstacleLossOsgVisualizer.cc
inet/visualizer/power/EnergyStorageCanvasVisualizer.cc
inet/visualizer/power/EnergyStorageOsgVisualizer.cc
inet/visualizer/scene/NetworkConnectionCanvasVisualizer.cc
inet/visualizer/scene/NetworkConnectionOsgVisualizer.cc
inet/visualizer/scene/NetworkNodeCanvasVisualization.cc
inet/visualizer/scene/NetworkNodeCanvasVisualizer.cc
inet/visualizer/scene/NetworkNodeOsgVisualization.cc
inet/visualizer/scene/NetworkNodeOsgVisualizer.cc
inet/visualizer/scene/SceneCanvasVisualizer.cc
inet/visualizer/scene/SceneOsgEarthVisualizer.cc
In file included from inet/visualizer/scene/SceneOsgEarthVisualizer.cc:24:
./inet/visualizer/scene/SceneOsgEarthVisualizer.h:25:10: fatal error: 
      'osgEarth/MapNode' file not found
#include <osgEarth/MapNode>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [Makefile:1332: ../out/clang-release/src/inet/visualizer/scene/SceneOsgEarthVisualizer.o] Error 1
make[1] : on quitte le répertoire « /home/abdullatif/Bureau/crash/c1/inet/src »
make: *** [Makefile:6: all] Error 2
[abdullatif@HOUDA-LINUX inet]$ 

**2) Linking error** 
------------------------------------------

[abdullatif@HOUDA-LINUX c2]$ git clone --recursive https://github.com/inet-framework/inet
[abdullatif@HOUDA-LINUX c2]$ cd inet/
[abdullatif@HOUDA-LINUX inet]$ make makefiles
[abdullatif@HOUDA-LINUX inet]$ make

inet/transportlayer/tcp_common/TCPSegment_m.cc
inet/transportlayer/udp/UDPPacket_m.cc
Creating shared library: ../out/clang-release/src/libINET.so
make[1] : on quitte le répertoire « /home/abdullatif/Bureau/crash/c2/inet/src »
[abdullatif@HOUDA-LINUX inet]$ cd tutorials/wireless/
[abdullatif@HOUDA-LINUX wireless]$ ./run
OMNeT++ Discrete Event Simulation  (C) 1992-2017 Andras Varga, OpenSim Ltd.
Version: 5.4, build: 180611-572210e, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

<!> Error: Cannot load library '../../src//libINET.so': ../../src//libINET.so: undefined symbol: _ZTIN3osg5GroupE

End.
[abdullatif@HOUDA-LINUX wireless]$ 

**3) Patch to solve the issue**
------------------------------------------

Please refer to the patch file to understand how I solve the issue.

[disable_osgearth_patch.txt](https://github.com/inet-framework/inet/files/2151350/disable_osgearth_patch.txt)

**Comment by torokati44** [comment]
Thank you for the patch!
LGTM for the most part, except for the first change in `src/makefrag`:

    -#
    +CFLAGS += -U WITH_OSGEARTH#

Why is this necessary?

**Comment by bourou01** [comment]
I had osgEarth installed in my linux distribution but disabled during Omnet++ compilation. So I think the flag 'WITH_OSGEARTH' was defined since osgearth was installed.To make sure the flag is undefined I use the parameter '-U' to undefine the flag 'WITH_OSGEARTH'.

Now I uninstalled osgEarth from my distribution, so inet compilation worked well without the line:
+CFLAGS += -U WITH_OSGEARTH#

So I think this will be useful to add a parameter in the file src/makefrag file to enable or disable OSG_EARTH.


In this example from :  #include "inet/visualizer/base/SceneOsgVisualizerBase.h" : 
#ifdef WITH_OSG
 #include <osgEarth/MapNode>
 #include <osgEarthAnnotation/RectangleNode>
 #include <osgEarthUtil/ObjectLocator>
#endif // ifdef WITH_OSGEARTH

even if 'WITH_OSGEARTH = no', the flag WITH_OSGEARTH keep being defined and the compiler try to include <osgEarth>.

I hope my english is understandable.

**Comment by torokati44** [comment]
Your patch has been merged into master as part of #354. Let us know if it's not a proper solution. Thanks!

**Comment by bourou01** [comment]
I've just tested it and it work like a charm, thanks

**Comment by lionyouko** [comment]
Is is not working for me. As far as I know, this was included in the next releases, right? Somebody knows why is it not working that straight forward? 
Thank you.

By the time I installed omnetpp, I had WITH_OSG and WITH_OSGEARTH set to yes in configure.user. But no lib was put manually in configure.user. It was yes, but maybe by default, I didn't bother with that because I dont need it in my projects. 

But now, it fails to build INET from the own omnetpp eclipse IDE. What should I do to make it work and preserve my projects in omnetpp?
thanks
