### ISSUE TITLE
Wrong center frequencies for Ieee80211ArithmeticalBand "5.9 GHz"

### ISSUE THREAD

**Issue by riebl** [inet-framework/inet#356]
In Europe, the 5.9 GHz band ranges from 5.855 to 5.925 GHz with center frequencies at 5.860 + n * 10 MHz (see EN 302 571 V2.1.1). The US band starts at 5.850 GHz but the first 5 MHz are unused. Hence, the channels in Europe and the US have equal center frequencies.

https://github.com/inet-framework/inet/blob/b89cf742b39f0a46702089ba77aa953084e05a80/src/inet/physicallayer/ieee80211/mode/Ieee80211Band.cc#L85
in combination with
https://github.com/inet-framework/inet/blob/b89cf742b39f0a46702089ba77aa953084e05a80/src/inet/physicallayer/ieee80211/mode/Ieee80211Band.cc#L54
causes erroneous 5 MHz offsets for each channel's center frequency.

Since the definitions of all other 5 GHz bands start at exactly 5.0 GHz I suppose you want to keep calculating the center frequency in `Ieee80211ArithmeticalBand::getCenterFrequency`. Thus, the 5.9 GHz band should start at `GHz(5.855)` instead of `GHz(5.86)`.

**Comment by levy** [comment]
Pushed fix to master.
