### ISSUE TITLE
No bitrates works for Ieee80211 p in 5.9 GHz band

### ISSUE THREAD

**Issue by eseglo** [inet-framework/inet#361]
Using Ieee80211 with opMode="p" and bandName="5.9 GHz" results in an 'Unknown bitrate: (1.195e+07 - 1.205e+07) in operation mode: 'p' -- in module (inet::physicallayer::Ieee80211ScalarTransmitter)' 
for all the bitrates of the mode (3,4.5,6,9, ...) Mbps.
The problem seems to be that the channel spacing is set to 10 MHz but the bandwidth is set to 20 MHz. I am not sure why the bandwidth has been set to 20 MHz. According to IEEE 802.11-16, table 17-16 the occupied bandwidth for OFDM PHY at 10 MHz channel spacing is 8.3 MHz. 
It is set to 20MHz in Ieee80211OfdmModulation.cc:
``const Ieee80211OfdmMode Ieee80211OfdmCompliantModes::ofdmMode6MbpsCS10MHz("ofdmMode6MbpsCS10MHz", &Ieee80211OfdmCompliantModes::ofdmPreambleModeCS10MHz, &Ieee80211OfdmCompliantModes::ofdmHeaderMode3MbpsRate5, &Ieee80211OfdmCompliantModes::ofdmDataMode6MbpsCS10MHz, MHz(10), MHz(20));``

The problem  appears in ``in void Ieee80211TransmitterBase::initialize(int stage)``
 at 
`` setMode(modeSet != nullptr ? (bitrate != bps(-1) ? modeSet->getMode(bitrate, band->getSpacing()) : modeSet->getFastestMode()) : nullptr);`` 

it passes to the band spacing to getMode ` band->getSpacing()`, which is 10 MHz but in 
``Ieee80211ModeSet::findMode(bps minBitrate, bps maxBitrate, Hz bandwidth, int numSpatialStreams) ``
it expects the bandwidth (so it seems) and it compares the channel spacing  (10MHz) to the dataMode::bandwidth in ``
 if (minBitrate <= bitrate && bitrate <= maxBitrate &&
            (std::isnan(bandwidth.get()) || dataMode->getBandwidth() == bandwidth) &&
            (numSpatialStreams == -1 || dataMode->getNumberOfSpatialStreams() == numSpatialStreams))``
which is 20 MHz for all the modes. It works, however, for other bands such as 2.4 GHz.

**Comment by riebl** [comment]
I can confirm this issue. My current workaround is leaving `Ieee80211Interface`'s bitrate at its default (-1) and setting bitrates at mac.hcf.rateSelection.*Bitrate instead.

**Comment by levy** [comment]
Unfortunately, this issue is more tricky than it seems to be. This is more of a note than a solution for future reference.

The default bandwidth parameter in Ieee80211Radio is clearly wrong (2MHz). Lucklily, this doesn't affect Ieee80211 error models, because they use the bandwidth of the actual Ieee80211Mode carried by the signal.

I wanted to set the parameter to NaN, which would mean that it depends on the actual mode selected by the MAC. This often results in different bandwidhs (which is right BTW) for different bitrates. Unfortunately, the receiver interface requires the receiver to specify the bandwidth how it is listening on the medium. This requirement cannot be fulfilled correctly, so I'm kind of stucked here right now.

**Comment by levy** [comment]
This has been fixed meanwhile in INET 4.1.

**Comment by rnderk** [comment]
im using INET 4.2 and found exactly same issue.

**Comment by kenog** [comment]
I seem to be having the same issue currently with INET 4.3.8, using the same configuration as @eriko-h. Are we doing something wrong @levy?

**Comment by nicoostendorf** [comment]
Found also the same error in INET 4.3.8.. 
`
*.node[*].wlan[0].bitrate =  6 Mbps`

Error is: 
`Unknown bitrate: (1.195e+07 - 1.205e+07) in operation mode: 'p' -- in module (inet::physicallayer::Ieee80211DimensionalTransmitter)`

Choosing value between 1.195e+07 - 1.205e+07 also leeds to an error for me.

**Comment by levy** [comment]
For @eriko-h , there's no 1Mbps mode in the 'p' modeset, so it won't work. I've just checked INET 4.5.2 and it works with 6Mbps.  @nicoostendorf could you please check with the latest version?

**Comment by arahman33** [comment]
So is it not possible to set different bitrates for the hosts in Ieee80211ac? I have a project where the data transmission rates of different hosts are different, i.e., 21Mbps, 23Mbps, etc., but I am not able to do this. I have also tried what @riebl suggested by setting the bitrate through mac.hcf.rateSelection.*Bitrate. But it still automatically sets it to 78Mbps, for all the hosts. I am using Ieee80211Interface in "ac" opMode with Ieee80211ScalarRadio for AdhocHosts. Any suggestions would be appreciated.

**Comment by levy** [comment]
Yes, it's possible to have different bitrates in different hosts. You should set the bitrate on the wireless interface. The data rate and bit rate names are often used interchangeably.

**Comment by arahman33** [comment]
@levy  thanks for your response. But is it possible to set any bitrate out of the standard bitrate set in different opModes? For example in g(mixed) instead of 54Mbps, can I set 50Mbps? or for ac mode, instead of 78Mbps, can I set 70Mbps?
