### ISSUE TITLE
Wrong IP option codes for STREAM_ID and RECORD_ROUTE

### ISSUE THREAD

**Issue by screw** [inet-framework/inet#376]
https://github.com/inet-framework/inet/blob/a817ccda8db4c89c14f1a3d04b9c36c8926cd831/src/inet/networklayer/ipv4/Ipv4Header.msg#L67
Based on [IANA IP options](https://www.iana.org/assignments/ip-parameters/ip-parameters.xhtml) some of the IP option codes in Ipv4Header.msg are wrong.
The STREAM_ID uses just the "Number" without the "Class" and "Copy" bits, and the RECORD_ROUTE has assigned value 136 which actually belongs to STREAM_ID.

Currently:
enum Ipv4OptionType
{
    IPOPTION_END_OF_OPTIONS = 0;
    IPOPTION_NO_OPTION = 1;
    IPOPTION_STREAM_ID = 8;

    IPOPTION_TIMESTAMP = 68;

    IPOPTION_SECURITY = 130;
    IPOPTION_LOOSE_SOURCE_ROUTING = 131;
    IPOPTION_RECORD_ROUTE = 136;
    IPOPTION_STRICT_SOURCE_ROUTING = 137;
    IPOPTION_ROUTER_ALERT = 148;

    IPOPTION_TLV_GPSR = 47;
};

Should be:
enum Ipv4OptionType
{
    IPOPTION_END_OF_OPTIONS = 0;
    IPOPTION_NO_OPTION = 1;
    IPOPTION_STREAM_ID = 136;

    IPOPTION_TIMESTAMP = 68;

    IPOPTION_SECURITY = 130;
    IPOPTION_LOOSE_SOURCE_ROUTING = 131;
    IPOPTION_RECORD_ROUTE = 7;
    IPOPTION_STRICT_SOURCE_ROUTING = 137;
    IPOPTION_ROUTER_ALERT = 148;

    IPOPTION_TLV_GPSR = 47;
};

**Comment by levy** [comment]
Fixed in master branch, thanks!
