### ISSUE TITLE
IdealMac's signal called "dropPkNotForUs" has invalid type

### ISSUE THREAD

**Issue by goofacz** [inet-framework/inet#380]
### Description
In file `IdealMac.ned` line:
`@signal[dropPkNotForUs](type=IdealMacFrame);`
should be changed to
`@signal[dropPkNotForUs](type=inet::IdealMacFrame);`

Otherwise user gets following exception:
`<!> Error: Wrong type "IdealMacFrame" in the @signal[dropPkNotForUs] property in the "smile.IdealRangingMac" NED type, should be one of: long, unsigned long, double, simtime_t, string, or a registered class name optionally followed by a question mark -- in module (smile::IdealRangingMac) basic_area.anchorNodes[1].nic.mac (id=81), at t=0.000010171713s, event #16
undisposed object: (inet::IdealMacFrame) basic_area.anchorNodes[1].nic.mac.POLL -- check module destructor`

### Version
3.6.4

**Comment by torokati44** [comment]
Thanks for reporting, we are already aware of this issue (see https://github.com/inet-framework/inet/commit/bfa37126b7617c97aba4f7917ccf3c47c502d5ef), and working on a fix.

**Comment by goofacz** [comment]
Can we expect to see 3.6.5 or 3.6.4 was the final release for 3.6?

**Comment by torokati44** [comment]
Yes, we plan to release maintenance revisions of the 3.6 branch, until a number of projects have enough time to migrate to 4.0, at least to fix this issue.
