### ISSUE TITLE
Emulation examples in Inet not working

### ISSUE THREAD

**Issue by alexander989** [inet-framework/inet#385]
Hello 
I am running omnet Version: 5.1, and Inet version -3.5.0. I am trying to run emulation examples, but they do not work. I removed the exclusion from the proprieties of inet->Ned sources folder. However when running the example I get ((inet::cSocketRTScheduler" not found)). Can someone plz explain the problem for me. 
Thanks

**Comment by rhornig** [comment]
Emulation is a feature that is disabled by default. Simply adding back the NED files are not enough to enable as it requires also some C++ code. You should properly enable the feature in the project properties dialog or using the inet_featuretool.
