### ISSUE TITLE
Assign the same IPv4 to multiple interfaces

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#387]
I am trying to assign the same IPv4 address to multiple interfaces. More specifically, I am trying to assign 1.1.1.1/24 to the eth0 interface of R2, R3, R4 and R5:

![2018-10-01_15-03-58](https://user-images.githubusercontent.com/5473998/46318491-8ce8e780-c58b-11e8-9c60-e9048aa9fe4e.png)

I am expecting a configuration like the following does the trick:

```
*.configurator.config = xml("<config> \
                            <interface hosts='R2' names='eth0' address='1.1.1.1' netmask='255.255.255.0' /> \
                            <interface hosts='R3' names='eth0' address='1.1.1.1' netmask='255.255.255.0' /> \
                            <interface hosts='R4' names='eth0' address='1.1.1.1' netmask='255.255.255.0' /> \
                            <interface hosts='R5' names='eth0' address='1.1.1.1' netmask='255.255.255.0' /> \
                            <interface hosts='**' address='10.x.x.x' netmask='255.x.x.x' /> \
                             </config>")

*.configurator.assignDisjunctSubnetAddresses = false
```
But I am getting this error:

![2018-10-01_15-09-05](https://user-images.githubusercontent.com/5473998/46318616-ff59c780-c58b-11e8-9eaa-d37a3dc6bf84.png)

This line is throwing the error:

https://github.com/inet-framework/inet/blob/1ff26646690c6742dc765b2873462c49669d3854/src/inet/networklayer/configurator/ipv4/Ipv4NetworkConfigurator.cc#L536

Shouldn't we check if `assignDisjunctSubnetAddressesParameter` parameter is true in the `if` condition?

**Comment by levy** [comment]
This feature has been added to INET master branch recently using assignUniqueAddresses parameter.
