### ISSUE TITLE
EtherMAC swallows frames when PAUSE is engaged

### ISSUE THREAD

**Issue by danushkam** [inet-framework/inet#391]
If a link (interface) is PAUSE'ed just before a frame is transmitted, the tx operation gets suspended. Anyway when the link is UNPAUSE'ed, the MAC fetches a new frame from the queue before flushing the suspended frame out causing a packet loss. This can be fixed with a simple change to EtherMAC and EtherMACFullDuplex classes. I am happy to submit a patch.

**Comment by danushkam** [comment]
Here's my patch for this issue.

Thanks!

[Patch.391.zip](https://github.com/inet-framework/inet/files/2456195/Patch.391.zip)

**Comment by avarga** [comment]
Thanks for the patch, merged into both 3.x and 4.x (=master)

**Comment by danushkam** [comment]
Thanks for applying the patch!
