### ISSUE TITLE
Probelm with building INET 3.4.0 in OMNET 5.0

### ISSUE THREAD

**Issue by happyqiaomai** [inet-framework/inet#394]
13:08:04 **** Incremental Build of configuration gcc-debug for project inet ****
make MODE=debug CONFIGNAME=gcc-debug -j1 all 
cd src && make all
make[1]: Entering directory `/home/kelsey/omnetpp-5.0/samples/inet/src'
Creating shared library: ../out/gcc-debug/src/libINET.so
make[1]: Leaving directory `/home/kelsey/omnetpp-5.0/samples/inet/src'
/usr/bin/ld: cannot find -lOpenThreads
/usr/bin/ld: cannot find -losg
/usr/bin/ld: cannot find -losgText
/usr/bin/ld: cannot find -losgDB
/usr/bin/ld: cannot find -losgEarth
/usr/bin/ld: cannot find -losgEarthUtil
collect2: error: ld returned 1 exit status
make[1]: *** [../out/gcc-debug/src/libINET.so] Error 1
make: *** [all] Error 2

13:08:15 Build Finished (took 10s.918ms)

**Comment by levy** [comment]
I think you didn't have OSG installed on your system, so the linker couldn't link INET.
