### ISSUE TITLE
Direct and limited broadcast do not work as expected

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#396]
Consider the following network:

![2018-11-18_22-23-29](https://user-images.githubusercontent.com/5473998/48689822-f6937400-eb80-11e8-96c0-1894622c2492.png)

oops! I calculated the broadcast address wrong! the broadcast address is 20.0.0.7 and the direct broadcast scenario works correctly.

~~hostA0 on the left sends a direct broadcast packet to the network on the far right. The destination IPv4 address is set to 20.0.0.5 that is the broadcast address of the target network. The packet is forwarded correctly until it reaches R2. However, R2 invokes ARP on eth1 interface that is wrong! looking for the host corresponding to the broadcast address of 20.0.0.5. Of course nobody responds! The correct behavior is that R2 recognize that the destination IPv4 address is broadcast and broadcast the packet into the attached network.~~

An even better solution is to define a parameter to turn on/off direct broadcast per interface. In most of the implementations, forwarding of IPv4 packets with direct broadcast is off.

Similarly, if hostA0 sends a packet with limited broadcast address (255.255.255.255), nothing is sent! The expected behavior is that the packet is boadcasted into the local network and all hosts receive it. Router R1 blocks all limited broadcast and stop them from being forwarded any further.

Here is an example that shows both scenarios:

https://github.com/ManiAm/inet/blob/INETex/examples_INETex/multicasting/omnetpp.ini

**Comment by ManiAm** [comment]
>> So this bug report is reduced to a feature request then?

Limited broadcast does not work; however direct broadcast works as expected (although it is nice to have a parameter to turn on/off direct broadcast per interface)

**Comment by ZoltanBojthe** [comment]
I think, the correct direct broadcast address is 20.0.0.*7*

Mani Amoozadeh <notifications@github.com> ezt írta (időpont: 2018. nov.
20., K, 5:04):

**Comment by ManiAm** [comment]
>> I think, the correct direct broadcast address is 20.0.0.7

Yes, I noticed my mistake right after I posted the question and updated it. 

The direct broadcast scenario is working fine, however, the limited broadcast is not working. When the application sends a message to 255.255.255.255, I am expecting the msg to get broadcasted between all hosts in the current LAN. However, no message is sent out from the host. I did not have time to check the code to see what is going on under the hood.

**Comment by levy** [comment]
I looked into this problem and found a separate flag for enabling/disabling IPv4 limited broadcast, which is off by default. You can enable it with the following:

`**.ip.forceBroadcast = true`

I'm not sure why is it disabled by default, and I also think the parameter name is weird. Why is it called forceBroadcast and not simply enableBroadcast?

**Comment by ManiAm** [comment]
I had not noticed that parameter before! Going through the code, apparently the `forceBroadcast` parameter is only relevant when a message is received from higher layer. When a packet is received from the network, this parameter has no effect. 

After googling, I found out that in many TCP/IP stacks, a socket can not send packets to the limited broadcast address. Your socket must have broadcast permissions by setting the SO_BROADCAST option.

```
bcast_sock = socket(AF_INET, SOCK_DGRAM, 0);
int broadcastEnable=1;
int ret=setsockopt(bcast_sock, SOL_SOCKET, SO_BROADCAST, &broadcastEnable, sizeof(broadcastEnable));
```

So probably, `forceBroadcast` parameter is a very naive way of enabling broadcast on a host when no socket is involved (I am just guessing). In my own INET example, I enabled this parameter for hostA0:

*.hostA0.ipv4.ip.forceBroadcast = true

And the scenario is working as expected. HostA0 sends a limited broadcast message. All nodes inside the
LAN receive it and the local router blocks the message from being broadcasted even further. So if we assume that `forceBroadcast` might be a useful parameter for some scenarios and gives more control to the user, why the default value is `false`?

**Comment by ManiAm** [comment]
Coming back to my feature request:

>>  ... although it is nice to have a parameter to turn on/off direct broadcast per interface

I guess it is easy to implement since the ipv4 code is very nicely organized. I will sent a pull request and then close this issue.

**Comment by ManiAm** [comment]
As promised:

PL #400
