### ISSUE TITLE
Error referencing Nic property is outdated

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#413]
Nic property error no longer makes sense as Nic was changed to Interface and it should instead refer to "not having an InterfaceEntry as a parent module"
https://github.com/inet-framework/inet/blob/b89cf742b39f0a46702089ba77aa953084e05a80/src/inet/common/ModuleAccess.cc#L102

The reason for writing this issue is the debugging I went through in this SO question: https://stackoverflow.com/q/54597785

**Comment by ZoltanBojthe** [comment]
fixed in inet v4.1.1
