### ISSUE TITLE
RealTimeScheduler time little bug

### ISSUE THREAD

**Issue by swiru95** [inet-framework/inet#420]
Hello, look in RealTimeScheduler.cc:
...

    int64_t curTime = opp_get_monotonic_clock_nsecs();

    if (targetTime > curTime)
    {
        int status = receiveUntil(targetTime);
        if (status == -1)
            return nullptr; // interrupted by user
        if (status == 1)
            event = sim->getFES()->peekFirst(); // received something
    }
    else {
        // we're behind -- customized versions of this class may
        // alert if we're too much behind, whatever that means
        int64_t diffTime = curTime - targetTime;
        EV << "We are behind: " << diffTime * 1e-6 << " seconds\n";
    }
...

curTime is in nanosecs as int  so this is 1e-9 sec
So why you show it as seconds in EV stream?;-)
There should be miliseconds or 
diffTime*1e-9 seconds.
Am I right?

**Comment by levy** [comment]
Absolutely. The time used to be in microseconds, but now it's in nanoseconds. Thanks!
