### ISSUE TITLE
Emulation examples have been broken with recent changes in INET 4.1

### ISSUE THREAD

**Issue by levy** [inet-framework/inet#421]
See examples/emulation/extserver for example.

**Comment by craftyang** [comment]
When I run any of the emulation examples, this error is reported:

Gate 'Traceroute.extRouter.ext[0].upperLayerIn' is not connected to a submodule (or internally to another gate of the same module) -- in module (inet::ExtInterface) Traceroute.extRouter.ext[0] (id=761), during network setup

![image](https://user-images.githubusercontent.com/8406360/60733188-bac9e500-9f7e-11e9-9395-77a9b2a5dd9a.png)

**Comment by craftyang** [comment]
Is there any walk through about inet emulation? I have tried inet version 2.6,4.1, but with no luck, the example all report problems.

**Comment by levy** [comment]
This is the latest basic emulation showcase: https://github.com/inet-framework/inet/blob/showcases-wip/showcases/emulation/basic/doc/index.rst

It's not yet released though.

**Comment by levy** [comment]
Indeed, the emulation examples in the examples folder were broken. I've just updated them in the master branch for the upcoming INET 4.2 release.
