### ISSUE TITLE
error in importing inet

### ISSUE THREAD

**Issue by mounika21297** [inet-framework/inet#423]
![image](https://user-images.githubusercontent.com/40383068/54552459-1ecb9c00-49d6-11e9-9603-349d6065f5ef.png)
I am facing the following issues when importing inet to omnet here i m using inet 4.0 and omnet 5.4.1 please do help me how to overcome these

**Comment by rhornig** [comment]
Well, these are warnings, not errors. The IDE is not always able to follow and figure out various dynamic module types, so false positive warnings are to be expected.
