### ISSUE TITLE
handle incoming messages with custom coding

### ISSUE THREAD

**Issue by BrainBanana** [inet-framework/inet#429]
Is it possible to use a Inet Host like e.g. the WirelessHost from inet and apply custom coding for handling the message when received? I have only seen inet tutorials using the ini and ned files. 

When checking basic Tutorials without inet, like tictoc, there was the possibility to use the handleMessage function when a message has been received. Is there a similar possibility when using Inet?

**Comment by levy** [comment]
This is not an INET issue.
