### ISSUE TITLE
Module not found on path 'interfaceTable' defined by par ***

### ISSUE THREAD

**Issue by Marconi666** [inet-framework/inet#433]
in the .ini file:       *.interfaceTableModule = ""
the error occured when I run the simulation.

ps:win7+omnet++5.0+inet3.4

**Comment by Marconi666** [comment]
![image](https://user-images.githubusercontent.com/27673304/56268016-fe9d1300-6122-11e9-9325-1c1b236774cf.png)
  
thanks!!

**Comment by levy** [comment]
I'm sorry but this forum is not for questions or discussion.
