### ISSUE TITLE
__imp__ZTIN4inet13IRoutingTableE

### ISSUE THREAD

**Issue by Milad321** [inet-framework/inet#434]
hi 
whats the problem ? when i add - msg6 !!! (omnet5.4.1 inet 4.1)
it shown this error !!!
please help me !!!

![Capture](https://user-images.githubusercontent.com/40688358/56471846-6ed1ce80-646c-11e9-9ff0-877a8df44f42.PNG)

**Comment by ZoltanBojthe** [comment]
This is typeinfo problem on Windows systems (undefined reference to '_typeinfo for inet::IRoutingTable')

**Comment by rhornig** [comment]
This is a bug of clang on windows when it does not properly export the typinfo symbols. There is a workaround for this already in the latest INET 3 and 4 versions. Other way to avoid this is to use gcc instead of clang.
