### ISSUE TITLE
802.11: Interference on independent channels if "sample-hold" interpolation is used on dimensional radio medium

### ISSUE THREAD

**Issue by dstolpmann** [inet-framework/inet#440]
Hi,
i have created a scenario with three pairs of adhoc hosts with each pair communicating on a different WiFi channel. I use the channels 1,6 and 11 in the 2.4 GHz band as they should not interfere with each other. The simulation uses dimensional transmission with the dimensions set to time and frequency. To measure the throughput of the links, I simulate a TCP file download between each adhoc pair with the expectation that the throughput should be equal for all pairs.

However, may simulation results show a decreased throughput for the pair on channel 6. I have figured out that this behavior can only be observed if the interpolation mode of the radio medium is set to "sample-hold". If it is set to "linear", the throughput is equal for all channels.

The following screenshot shows the number of received bytes for the receiving hosts for both cases:
![](https://user-images.githubusercontent.com/7644267/56967680-fa7ce680-6b61-11e9-975d-e838b23e7cb0.png)

I have uploaded my simulation model at:
https://gist.github.com/dstolpmann/d2e496919e4776f8fa1c102efa9e9618

I am using OMNet++ 5.4.1 and INET 4.1 with 1a8a69a09f3253cba0cc20c1ae9417086a651cd9 applied.

Best regards,
dstolpmann

**Comment by dstolpmann** [comment]
This issue might be related to: #427

**Comment by levy** [comment]
The upcoming INET 4.2 version will replace the old dimensional representation of the signal analog model inherited from MiXiM with a completely rewritten more flexible and more efficient version. The new code is already present in the master branch. You can try it now if you want to. The old code is not maintained anymore, there were some issues with. The NED interface is pretty much the same.

[Presentation from the 2019 Summit](https://summit.omnetpp.org/2019/assets/pdf/math.pdf)
