### ISSUE TITLE
Infinite loop in TlvOptions::findByType

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#441]
int TlvOptions::findByType(short int type, int firstPos) const
{
    for (size_t i = firstPos; i < tlvOption_arraysize; )
        if (tlvOption[i] && tlvOption[i]->getType() == type)
            return i;
    return -1;
}
should be 
int TlvOptions::findByType(short int type, int firstPos) const
{
    for (size_t i = firstPos; i < tlvOption_arraysize; i++)
        if (tlvOption[i] && tlvOption[i]->getType() == type)
            return i;
    return -1;
}

**Comment by ZoltanBojthe** [comment]
thanks, fixed in master
