### ISSUE TITLE
Problems with the latest CsmaCa code

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#442]
The changes in the queue in the CsmaCa code raises an error if you try to execute in run mode (not in Fast or express) . The error is :

ASSERT: Condition 'holding && operation->isHolding()' does not hold in function 'addOperation' at messageanimations.cc:388 -- in module (inet::CsmaCaMac) CorruptionModeExample.sourceHost.wlan[0].mac (id=27), at t=0.00029502s, event #9

**Comment by torokati44** [comment]
Can you please check if applying this patch to INET fixes it? https://github.com/inet-framework/inet/commit/3debee79ee95c48cac56ba8a8db07750c2206c79

**Comment by aarizaq** [comment]
I have the same modification in inetmanet and to code runs without problem.

**Comment by levy** [comment]
Ok, then I close this.
