### ISSUE TITLE
Segmentation fault at inet/linklayer/ieee80211/mac/queue/InProgressFrames.cc:178

### ISSUE THREAD

**Issue by j-licht** [inet-framework/inet#443]
#0  0x00005555568bed80 in ?? ()
#1  0x00007fffeaa37c16 in inet::ieee80211::InProgressFrames::clearDroppedFrames (this=0x555556769f60) at inet/linklayer/ieee80211/mac/queue/InProgressFrames.cc:178
#2  0x00007fffeaa1b6ce in inet::ieee80211::FrameSequenceContext::~FrameSequenceContext (this=0x5555568aaec0, __in_chrg=<optimized out>) at inet/linklayer/ieee80211/mac/framesequence/FrameSequenceContext.cc:73
#3  0x00007fffeaa1b6f9 in inet::ieee80211::FrameSequenceContext::~FrameSequenceContext (this=0x5555568aaec0, __in_chrg=<optimized out>) at inet/linklayer/ieee80211/mac/framesequence/FrameSequenceContext.cc:67
#4  0x00007fffeaa1c8a4 in inet::ieee80211::FrameSequenceHandler::abortFrameSequence() () at inet/linklayer/ieee80211/mac/framesequence/FrameSequenceHandler.cc:169
#5  0x00007fffeaa0c34e in non-virtual thunk to inet::ieee80211::Hcf::handleMessage(omnetpp::cMessage*) () at ./inet/common/IntrusivePtr.h:60
#6  0x00007ffff6f3030a in omnetpp::cSimulation::executeEvent(omnetpp::cEvent*) () from /home/licht/Downloads/omnetpp-5.4.1/lib/liboppsim.so
#7  0x00007ffff7bce80b in omnetpp::cmdenv::Cmdenv::simulate() () from /home/licht/Downloads/omnetpp-5.4.1/lib/liboppcmdenv.so
#8  0x00007ffff7bcec49 in omnetpp::cmdenv::Cmdenv::doRun() () from /home/licht/Downloads/omnetpp-5.4.1/lib/liboppcmdenv.so
#9  0x00007ffff794974e in omnetpp::envir::EnvirBase::run(int, char**, omnetpp::cConfiguration*) () from /home/licht/Downloads/omnetpp-5.4.1/lib/liboppenvir.so
#10 0x00007ffff793fae2 in omnetpp::envir::setupUserInterface(int, char**) () from /home/licht/Downloads/omnetpp-5.4.1/lib/liboppenvir.so
#11 0x00007ffff7940e10 in evMain () from /home/licht/Downloads/omnetpp-5.4.1/lib/liboppenvir.so
#12 0x00007ffff5412e77 in __libc_start_main () from /lib/libc.so.6
#13 0x000055555555486a in _start ()

running in Cmdenv

**Comment by levy** [comment]
You should provide more information, because this bug cannot be reproduced from the above.
