### ISSUE TITLE
Replace IpV4NodeConfigurator with HostAutoConfigurator from an INI file

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#447]
Sometimes, especially when you dynamically create/destroy hosts, you have to use HostAutoConfigurator to set up IP addresses. Sadly this requires that you subclass  StandardHost and add the configurator there. It would be great to have the AutoConfogurator either built into the IpV4NetworkLayer, or have the address configurator module replacable.

Requirement: allow dynamically created modules with IP addresses without subclassing.

**Comment by levy** [comment]
Changed HostAutoConfigurator and Ipv4NodeConfigurator to implement IIpv4NodeConfigurator. They are replacable from INI files.
