### ISSUE TITLE
Trouble with different INET versions

### ISSUE THREAD

**Issue by stealson** [inet-framework/inet#449]
Hello,

I am trying to update a project that was developed with OMNeT++ 5.3 and INET 3.6 to be 
usable with OMNeT++ 5.5.1 and INET 4.1.0.

This is my first time developing with INET and OMNeT and I have trouble with several code changes. Some functions or classes were just deleted or moved and I cannot find any documentation that describes what exactly was changed or an explanation how one should adjust his code. Am I missing an official change log that gives more information beside a simple listing of what has changed but also further information about how it was changed or where it was moved?

I already could fix a lot of code by reading the code by myself, but there are still some issues I cannot resolve at this moment. For instance:

1. I cannot find an appropriate way to update these deprecated function calls: 
```c++
inet::InterfaceEntry->getInterfaceModule()->getSubmodule("radio")
```
Now `getInterfaceModule()` does not exist anymore and I don't know where it was moved.

2. Furthermore, the IP address and the net mask could be set like this:
```c++
inet::InterfaceEntry->ipv4Data()->setIPAddress(cmd->getIp0());
inet::InterfaceEntry->ipv4Data()->setNetmask(cmd->getSubnet0());
// where cmd->getIp0() and cmd->getSubnet0() are of type inet::Ipv4Address&
```
How would it be done now?

**Edit:** 
Can `ipv4Data()` be replaced with `getProtocolData<inet::Ipv4InterfaceData>()`?

3. Before, this was a valid way to set the socket id:
```c++
inet::UdpSendCommand *ctrl = new inet::UdpSendCommand();
ctrl->setDestAddr(destAddr);
ctrl->setDestPort(destPort);
ctrl->setSockId(socketID);
```
Beside an appropriate replacement for UdpSendCommand, how do I set the socket id now?

I hope my questions are not too obvious ;-)

Thank you for your feedback!

**Comment by ZoltanBojthe** [comment]
1. the inet::InterfaceEntry  is the descendant of the omnetpp::cModule, you can use the
`interfaceEntry->getSubmodule("radio")`

2. IPv4 address setting on InterfaceEntry:
`interfaceEntry->getProtocolData<Ipv4InterfaceData>()->setIPAddress(newAddress);`
see also `InterfaceEntry::findProtocolData<>()` and `InterfaceEntry::addProtocolData<>()`

3. The preferred way for UDP communication is `UdpSocket` usage. See the UdpSocket.h and UdpSocket.cc for details.

**Comment by stealson** [comment]
Dear Zoltan,

thank you very much for your answer. I solved the first two problems with your help, but I am still stuck with the third issue. 

Before the upgrade, the following code was correct, where `msg` is of type `omnetpp::cPacket`:
```cpp
auto *ctrl = new inet::UdpSendCommand();
ctrl->setDestAddr(destAddr);
ctrl->setDestPort(destPort);
ctrl->setSockId(socketId);
msg->setControlInfo(ctrl);
```
Now `inet::UdpSendCommand` does not exist anymore. But in [UdpControlInfo.msg](https://github.com/inet-framework/inet/blob/master/src/inet/transportlayer/contract/udp/UdpControlInfo.msg) you can find comments describing this class without any definition. Could it be, that the definition is missing?

**Comment by levy** [comment]
If you look into UdpSocket::send() and UdpSocket::sendToUDP then you will see how to send a packet without using a socket.
