### ISSUE TITLE
Feature Request: INetFilter support for IPv6

### ISSUE THREAD

**Issue by yol** [inet-framework/inet#45]
The NetFilter hooks in IPv4 currently allow the interception and possibly reinjection of IP packets in routers. For IPv6, no such interface currently exists. It would be very helpful for a number of use cases to have this interface in IPv6, too, or possibly a general interface that supports both procols.

As debated in #27, implementation of this feature is currently stalled because of a pending major refactoring of the IPv6 code. I'm creating this ticket nevertheless so we don't forget about it.

**Comment by ZoltanBojthe** [comment]
The most INetfilter hook supported by Ipv6
