### ISSUE TITLE
Inet compilation error in windows 10 (Omnet 5.4.1 and inet 4.1.0)

### ISSUE THREAD

**Issue by ngatran2018** [inet-framework/inet#450]
inet/common/queue/PacketQueue.cc:23:31: error: call of overloaded 'cPacketQueue(const char*&, std::nullptr_t)' is ambiguous
     cPacketQueue(name, nullptr)
                               ^
In file included from C:/Users/THO1O3/Desktop/omnetpp-5.5.1/include/omnetpp.h:92:0,
                 from inet/common/precompiled.h:28,
                 from inet/common/precompiled_debug.h:1:
C:/Users/THO1O3/Desktop/omnetpp-5.5.1/include/omnetpp/cpacketqueue.h:62:5: note: candidate: omnetpp::cPacketQueue::cPacketQueue(const char*, omnetpp::cQueue::CompareFunc)
C:/Users/THO1O3/Desktop/omnetpp-5.5.1/include/omnetpp/cpacketqueue.h:57:5: note: candidate: omnetpp::cPacketQueue::cPacketQueue(const char*, omnetpp::cQueue::Comparator*)
make[1]: *** [Makefile:1091: ../out/gcc-debug/src/inet/common/queue/PacketQueue.o] Error 1
make[1]: *** Waiting for unfinished jobs....
inet/common/queue/PriorityScheduler.cc
make[1]: Leaving directory '/c/Users/THO1O3/Desktop/omnetpp-5.4.1/inet4/src'
make: *** [Makefile:6: all] Error 2

**Comment by Buddahbrot1** [comment]
I experienced the same issue on ubuntu, using OMNeT 5.5.1 and INET 4.1.0.
Using the INET 4.1.1 [release](https://github.com/inet-framework/inet/releases/tag/v4.1.1) instead solved the problem for me.

**Comment by levy** [comment]
Indeed, the INET 4.1.0 and the OMNeT 5.5.1 versions are incompatible. Please use the INET 4.1.1 version.
