### ISSUE TITLE
Why UDPDataIndication is removed from UdpControlInfo.msg?

### ISSUE THREAD

**Issue by LLipter** [inet-framework/inet#454]
Hi,

Recently, I'm working on a project that developed with INET3.0. I try to update it to the newest version.  I came across code like this.

~~~cpp
inet::UDPDataIndication *ctrl = omnetpp::check_and_cast<inet::UDPDataIndication *>(pk->getControlInfo());
inet::L3Address srcAddress = ctrl->getSrcAddr(); 
~~~

How should I modify it? UDPDataIndication no longer exists anymore.

**Comment by ZoltanBojthe** [comment]
The contents of old UDPDataIndication class moved to Tags.
See 'Tag related functions' in inet/common/Packet.h and Message.h files

sender address of incoming UDP data:
`L3Address srcAddress = pk->getTag<L3AddressInd>()->getSrcAddress();`

Available Tags  on incoming packets: `L3AddressInd` (IP addresses), `L4PortInd` (UDP ports), `InterfaceInd`, `HopLimitInd`.
