### ISSUE TITLE
UDP Datagram size

### ISSUE THREAD

**Issue by ManiAm** [inet-framework/inet#461]
Looking into the UDP code, we do not check the size of data coming from application.

https://github.com/inet-framework/inet/blob/efa6b2363947c8b88423fb591a9a8683b9f7922b/src/inet/transportlayer/udp/Udp.cc#L397

The UDP length field is only 2 bytes, which means that the payload (data comming from the application) can be 65,535 bytes max! We never check for this.

This means that if I change the message size to 1000MB, then UDP happily accepts it and sets the length filed as 1000000008 (1000000000 payload + 8 header):

https://github.com/inet-framework/inet/blob/4461edad59f0bb85349261415e13e9953d9d7fcf/examples/inet/udpclientserver/omnetpp.ini#L12

![2019-09-21_16-00-30](https://user-images.githubusercontent.com/5473998/65380136-49e6bf00-dc89-11e9-945d-156fdcc86771.png)

Moreover, when you run the sim, the window freezes for a while. Because IPv4 has received a huge datagram from UDP and is busy fragmenting it into many fragments. 224821 fragments to be exact!

_DETAIL (Ipv4)UdpClientServer.client1.ipv4.ip: Breaking datagram into 224821 fragments_

This is also a very good example that shows students why fragmentation is a cpu-intensive task and IPv6-routers will not fragment received packets any more. 

Solved in PL #462

**Comment by arahman33** [comment]
The example says in the text that the message size is 1000MB and in the code it says  **.client*.app[0].messageLength = 1000B 

Is the messageLength in the unit of MB?
