### ISSUE TITLE
I am going to work on RTP/RTCP in next few months

### ISSUE THREAD

**Issue by qeef** [inet-framework/inet#463]
This is not a real issue, it's more like a question.

I am going to work on the RTP/RTCP protocol in the next few months, and I would like to ask for roadmap suggestions and possible pitfalls.

I have already played with RTP/RTCP a little bit, at least I did:
- MPEG to gdf script (https://gitlab.com/snippets/1857511),
- enable and run (somehow) simulations with Payload10 for INET 3.5.0.

The goal is:
1. Enable Payload10 for RTP/RTCP in INET 4.1.1+.
2. Implement IPv6 support for RTP/RTCP in INET 4.1.1+.

Thanks for your suggestions!

(And yes, I wrote this as the email to INET Contributors mailing list but with no feedback there.)

**Comment by avarga** [comment]
Hi Jiri,
Great news, please go ahead. You can use the INET master as starting point.
