### ISSUE TITLE
Facing issue in running inet extclient and extServer application

### ISSUE THREAD

**Issue by ShilpiPhadnis** [inet-framework/inet#464]
<!> Class "inet::Ext" not found -- perhaps its code was not linked in, or the class wasn't registered with Register_Class(), or in the case of modules and channels, with Define_Module()/Define_Channel() -- in module (inet::InterfaceEntry) ExtClient.peer.ext[0] (id=5), during network setup

**Comment by torokati44** [comment]
Do you have the `ExternalInterface` feature enabled in INET?
You can check it by running `opp_featuretool list` in the INET project root.
There should be a `+` sign in front of it. I think it's not enabled by default.
To enable it, you can run `opp_featuretool enable ExternalInterface`, then rebuild INET.

**Comment by ShilpiPhadnis** [comment]
Hi Thanks Issue is solved but I am facing different issue now :
<!> Cannot create pcap device, error = en0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: No such device -- in module (inet::Ext) ExtClient.peer.ext[0].ext (id=17),

**Comment by torokati44** [comment]
You probably have to adjust the configuration so it uses an interface that actually exist on your particular machine (like `eth0` or `enp2s1` or similar) instead of the `en0` mentioned above.

**Comment by ShilpiPhadnis** [comment]
Thanks .. Actually just checked the read me document, updated the same and fixed that issue. Now new issue came 
<!> Cannot activate pcap device -- in module (inet::Ext) ExtClient.peer.ext[0].ext (id=17), during network initialization.
Seems this issue will be solved after doing below steps:
- Set IP address of the external server to: 192.168.0.111/24 and add a route
  to routers external interface 192.168.0.100/24 and set the gateway to the
  IP address of the computer, on which the simulation is running
  or adjust the omnetpp.ini and mrt files to your networks setup.
- For uplink traffic use e.g. FileZilla and setup your external server to
  listen on port 10021.
- For downlink traffic use e.g. Iperf with following command line:
  iperf -c 172.0.1.111 -P 1 -i 1 -m -p 10021 -M 1452.0B -l 100.0M -f m -t 0
Kindly confirm

**Comment by torokati44** [comment]
Thanks for sharing the steps that worked for you!
