### ISSUE TITLE
Building requires Python 2

### ISSUE THREAD

**Issue by torokati44** [inet-framework/inet#465]
INET cannot be built on new Linux installations where Python 2 is no longer installed by default.

 > $ make makefiles
 > /usr/bin/env: ‘python’: No such file or directory
 > make: *** [Makefile:50: src/inet/features.h] Error 127

Yes, it's really easy to install, and it still works, but since [Python 2 is nearing its end of life](https://pythonclock.org/), we should move on to using Python 3 everywhere.

**Comment by rhornig** [comment]
Fixed on both the 4.x and 3.x branch.
