### ISSUE TITLE
Cannot activate pcap devied during network initialization after executing ExtClient and ExtServer application

### ISSUE THREAD

**Issue by ShilpiPhadnis** [inet-framework/inet#466]
I am facing issue in compilation after did all configuration in ExtClient and ExtServer application.
Error 
<!> Cannot activate pcap device -- in module (inet::Ext) ExtClient.peer.ext[0].ext (id=17), during network initialization

I have attached all files and configuration of my system.

Kindly confirm what is wrong in ip configuration.

ifconfig
ens33 Link encap:Ethernet HWaddr 00:0c:29:f4:b5:8c
inet addr:172.29.209.7 Bcast:172.29.223.255 Mask:255.255.240.0
inet6 addr: fe80::6d7a:5ad2:e407:c75c/64 Scope:Link
UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
RX packets:27983 errors:0 dropped:0 overruns:0 frame:0
TX packets:315 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:2409721 (2.4 MB) TX bytes:64781 (64.7 KB)
lo Link encap:Local Loopback

inet addr:127.0.0.1 Mask:255.0.0.0
inet6 addr: ::1/128 Scope:Host
UP LOOPBACK RUNNING MTU:65536 Metric:1
RX packets:248 errors:0 dropped:0 overruns:0 frame:0
TX packets:248 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:1000
RX bytes:18526 (18.5 KB) TX bytes:18526 (18.5 KB)

ip r
default via 172.29.208.1 dev ens33 proto static metric 100
169.254.0.0/16 dev ens33 scope link metric 1000
172.29.132.30 via 172.29.208.1 dev ens33 proto dhcp metric 100
172.29.208.0/20 dev ens33 proto kernel scope link src 172.29.209.7 metric 100

netstat -r -n
Kernel IP routing table
Destination Gateway Genmask Flags MSS Window irtt Iface
0.0.0.0 172.29.208.1 0.0.0.0 UG 0 0 0 ens33
169.254.0.0 0.0.0.0 255.255.0.0 U 0 0 0 ens33
172.29.132.30 172.29.208.1 255.255.255.255 UGH 0 0 0 ens33
172.29.208.0 0.0.0.0 255.255.240.0 U 0 0 0 ens33
[Changes_in_mrt_ompnet.tar.gz](https://github.com/inet-framework/inet/files/3695540/Changes_in_mrt_ompnet.tar.gz)

**Comment by torokati44** [comment]
Have you tried adding the `cap_net_raw,cap_net_admin` capabilities to the OMNeT++ binaries (since INET is built as a shared library) using `setcap`, as shown in the `examples/emulation/README` file?
(I do not recommend running even the runtime as root. It might cause other issues later with some configuration files that may be created with different permissions.)

**Comment by ShilpiPhadnis** [comment]
Yes  I have executed below commands
$ sudo setcap cap_net_raw,cap_net_admin=eip opp_run_dbg
$ sudo setcap cap_net_raw,cap_net_admin=eip opp_run_release 

problem what  I feel is configuration only. I have shared my configuration file as well. Kindly check and confirm the same.

**Comment by levy** [comment]
The emulation examples are updated in the master branch. They no longer use PCAP so this issue became obsolete.

**Comment by Artemideds** [comment]
Hi, I trie to lunch the example on inet: inet/example/emuletion/extserver/omnet.ini but i have the same problem with the socket raw esthabilishment connection, it catch this exception:
 if (setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, (void *)&ifr, sizeof(ifr)) < 0)
        throw cRuntimeError("Cannot bind raw socket to '%s' interface", device);
I follow the guide, but nothing, please
Can you hel me?

**Comment by zhangteng0526** [comment]
> Hi, I trie to lunch the example on inet: inet/example/emuletion/extserver/omnet.ini but i have the same problem with the socket raw esthabilishment connection, it catch this exception: if (setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE, (void *)&ifr, sizeof(ifr)) < 0) throw cRuntimeError("Cannot bind raw socket to '%s' interface", device); I follow the guide, but nothing, please Can you hel me?

I have also encountered such a problem, may I ask if you can solve it? I am eager to get your help
