### ISSUE TITLE
I found many warning after build inet4.1.1 on OMNeT++5.4.1

### ISSUE THREAD

**Issue by aekzaba123** [inet-framework/inet#469]
Like this picture

![image](https://user-images.githubusercontent.com/54108689/66771264-ff510f00-eee3-11e9-80ad-edc8bd123e66.png)

It's crazy or me.
I think I had install it correctly and import inet framework and then it showed that way.
Did I do something wrong ?
Can you guys help me ? pls.
oh, another thing is I used omnet++ on win7 64bits

**Comment by levy** [comment]
It's ok, those are just 'No such parameter' warnings.
