### ISSUE TITLE
Issue: <!> Root privileges needed -- in module (inet::TcpSessionSocketApp) Socketethernet.client.app0, during network initialization

### ISSUE THREAD

**Issue by ShilpiPhadnis** [inet-framework/inet#471]
I am trying to create raw socket communication between two host. I have taken two standard host and connected both with Eth100M. I created two application TcpSessionSocketApp and TcpEchoSocketApp with base class a cSimpleModule and added configuration related to application in omnet.ini file.
During initialization of process it is failed to create socket communication:
<!> Root privileges needed -- in module (inet::TcpSessionSocketApp) Socketethernet.client.app0, during network initialization.

I tried to provide admin privileges to  omnetpp, opp_run_dbg, opp_run_release, myapplication , TcpSessionSocketApp and TcpEchoSocketApp.
1. sudo setcap cap_net_admin,cap_net_raw=eip <application name>
(Not working)
after that I tried to give root access to all applications:
1. sudo chown root:root <application name>
(Not working)
afte that I provide admin privileges to my account:
 useradd -m -G root <user>
Still issue persist.

**Comment by levy** [comment]
There are no TcpSessionSocketApp and TcpEchoSocketApp applications in INET. These are probably added in your project by a 3rd party.
