### ISSUE TITLE
Gate 'World.physicallayer.phys$i' is not connected to sibling or parent module

### ISSUE THREAD

**Issue by SrilekhaPavuluri** [inet-framework/inet#472]
Hi
I am new to simulator and exploring to send CAM/DENM message using ethernet.
In Storyboard example, CAM/DENM message are using Inet.linklayer.ieee80211, instead of wifi I used EthernetInterface in link layer and EtherPhy in physical layer. I changed World.ned and omnet.ini file of Storyboard correspondingly, but it is asking for some confirmation like - 
" **Gate 'World.physicallayer.phys$i' is not connected to sibling or parent module -- in module (omnetpp::cModule) World (id=1), during network setup** ". 
If I use " **@loose** " property for all the gates to make control not to check for connections, and when i launch Storyboard, application is not launching at all. I want to know how INET is connecting to its upper and lower layers. I am attaching you World.ned and omnet.ini files. Please help me to proceed further.
[omnetpp.ini.tar.gz](https://github.com/inet-framework/inet/files/3742709/omnetpp.ini.tar.gz)
[World.ned.tar.gz](https://github.com/inet-framework/inet/files/3742710/World.ned.tar.gz)

Thank You

**Comment by levy** [comment]
I'm sorry but this is not a forum for questions and discussion. Please use the mailing list for that purpose.

**Comment by SrilekhaPavuluri** [comment]
Hi 
As you mentioned to use mailing list, I mailed you and other people of INET forum, thrice.
I request you to kindly check them and reply as soon as possible. Please provide me a way to proceed further.
Thank You
