### ISSUE TITLE
How to use PacketDelayer/Hooks

### ISSUE THREAD

**Issue by weinrank** [inet-framework/inet#474]
Hi all, I need some help! :)

I'm looking for an elegant way to add an artificial delay for packets from the SCTP model.
I've found the `PacketDelayer` module, it looks like a good start for my issue.

How can I use it?
I've followed the [Documentation](https://inet.omnetpp.org/docs/users-guide/ch-network-interfaces.html#hooks) but it seems the settings are getting ignored.
```
**.ppp[*].numOutputHooks = 2
**.ppp[*].outputHook[0].typename = "Delayer"
**.ppp[*].outputHook[1].typename = "ThruputMeter"
**.ppp[*].outputHook[0].delay = 3ms
```

**Comment by weinrank** [comment]
@tuexen for CC

**Comment by weinrank** [comment]
bump

**Comment by weinrank** [comment]
Current master.

Im finding some examples regarding the PacketDelayer.
But I have no clue how to use it in an IP/PPP scenario?

Let's assume we have the UDP example:
https://github.com/inet-framework/inet/tree/master/examples/inet/udpapp

How can I delay the UDP packet from the client?

Thanks!

**Comment by levy** [comment]
The next omnetpp version introduces a new NED property on connections (called reconnect) which allows overriding a connection in derived modules. This feature makes it easy to insert a new module into the connection between two already existing and connected submodules.

For now, your only option is to copy the NED file of the compound module where you want to insert the new submodule, and connect the submodules differently. Unfortunately, you will also have to copy all used derived modules. So, it's easier to do this at some places than at others. For example, it's easier to create a new source which contains a PacketProducer and a PacketDelayer than creating a new host which contains a PacketDelayer before the interface. I think, it's also pretty easy to create a new PPPInterface which contains a PacketDelayer, if that's what you want.

**Comment by levy** [comment]
No, I'm sorry, I would prefer not to do this. Hooks are generally a bad idea, because we could easily end up having hooks all over the place.

**Comment by levy** [comment]
This issue becomes obsolete with the upcoming INET 4.2 and OMNeT 5.6 versions.
