### ISSUE TITLE
Problem while executing the CR simulator- omnet.ini file

### ISSUE THREAD

**Issue by jessmathew55** [inet-framework/inet#476]
While executing the omnetpp.ini file the following error gets generated

Exception occurred executing command line.
Cannot run program "C:/Users/HP/Desktop/omnetpp-5.5.1/samples/crSimulator-master/src/crSimulator-master.exe" (in directory "C:\Users\HP\Desktop\omnetpp-5.5.1\samples\crSimulator-master\simulations"): CreateProcess error=2, The system cannot find the file specified

Kindly help me with this

**Comment by levy** [comment]
I'm sorry but this issue is not related to INET.
