### ISSUE TITLE
MultiFieldClassifier is not working with fragmented IP packets

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#478]
On INET 4.1 when IP fragmentation happens, the UDP/TCP port data is not available in subsequent fragments so the classifier on the link layer cannot make a decision based on port numbers. There could be two possible solutions:

- In the TCP and UDP layer, add port number indications and those indications should be copied on IP fragmentation. In the classifier, if port number is not available (not the first segment) use the port indicator as a fallback.
- a proper solution: do not rely on port number for classification, instead use the ToS field and prepare all applications to be able to set the ToS field, so you could specify the type of service per application.

**Comment by ZoltanBojthe** [comment]
Added tos and dscp NED parameters for many applications
