### ISSUE TITLE
ofdmDataMode27Mbps configuration is erroneous

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#481]
const Ieee80211OfdmDataMode Ieee80211OfdmCompliantModes::ofdmDataMode27Mbps(&Ieee80211OfdmCompliantCodes::ofdmCC2_3QAM64Interleaving, &Ieee80211OfdmCompliantModulations::qam64Modulation, MHz(20), MHz(20));

It set a bandwidth of 20 instead of 10 and the computed bit rate is 48Mb instead if 10

**Comment by aarizaq** [comment]
The data mode is also incorrect, is set to CC2_3QAM64Interleaving instead of CC3_4QAM64Interleaving (Table 17.4)

https://github.com/aarizaq/inetmanet-4.x/commit/22ede603fdc101f373bfe0d82e58829b132ccb4b

**Comment by levy** [comment]
Thanks for reporting! I checked the standard and indeed this was wrong. Could you please verify?

**Comment by aarizaq** [comment]
I have checked it with the debug and now the net bit rate y correct.
