### ISSUE TITLE
Memory leak in VectorCommunicationCache::removeNonInterferingTransmissions

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#482]
The method removeNonInterferingTransmissions() never removes finished transmissions 

size_t transmissionIndex = 0;
for (auto it = transmissionCache.cbegin(); it != transmissionCache.cbegin() + transmissionIndex; it++) {

Never enters inside the loop
Solution:
https://github.com/aarizaq/inetmanet-4.x/commit/a26169b12590af4c03413bdb82b24bd1fe89cae1

**Comment by levy** [comment]
Thank you! This is fixed as suggested in master.
