### ISSUE TITLE
Can not visualize module information of Ieee802154Mac.

### ISSUE THREAD

**Issue by ababila** [inet-framework/inet#485]
`refreshDisplay()` method not implemented yet.

**Comment by levy** [comment]
This issue is too generic in its current form. What are you actually suggesting?

**Comment by ababila** [comment]
It is just a tiny nice missing feature that may be patched with [this](https://gist.github.com/ababila/2dac1fd3d9438bf8fc1ba2b09c401074).

**Comment by levy** [comment]
A pull request would be nice! Also, you could add a displayStringTextFormat parameter and potentially include other state information. You can find many examples in INET.
