### ISSUE TITLE
Bug when running Mars Rover showcase in Qtenv

### ISSUE THREAD

**Issue by ajp1871** [inet-framework/inet#489]
Using OMNEST Evaluation package version 5.5.1 with inet-master_2019-11-21 download of master branch.

When running the Mars Rover example (showcase\mobility\combining --> AntennaOrientation infile config) in Qtenv, the antennas on the Mars Rover do not orient themselves properly/accurately.
- I observe that the antenna that is supposed to follow the drone never faces the drone, but rather seems to be offset. The antenna however is steering at what seems to be the speed of the drone.
- Further I observe that the other rover antenna, which is supposed to aim at the base, never faces the base. It also seems to be offset, yet steers it's beam as the rover moves along.

**Comment by adamgeorge309** [comment]
Thanks for pointing this out. This issue is now fixed in INET master.

A parameter name change was not followed in the ini file, so the rover was not moving at 0 degrees as it was supposed to. Also, the rover's mobility was set to face forward, and this created the offset of the antenna mobilities.

**Comment by ajp1871** [comment]
Thanks @adamgeorge309 for the fix!
