### ISSUE TITLE
NED Consistency problem

### ISSUE THREAD

**Issue by Vasudhashri** [inet-framework/inet#491]
Hi, I am running examples in Omnet++ and while running the example IEEE8021dradio.ned file has NED consistency problem. Please help me on how to resolve this as i have the same issue while running an Example Erlangen scenario from VEINS. 
Please find attached image for your reference. 

![image](https://user-images.githubusercontent.com/58476723/70061767-28894400-15e5-11ea-9fe7-330aad6468bd.png)

**Comment by avarga** [comment]
They are bogus warnings because the IDE does not fully understand parameter assignments, but otherwise they are completely harmless. You can ignore them.

**Comment by shriyaBhat1** [comment]
Have you solved this issue? Even I'm also getting the same warnings so please let me know.

**Comment by Vasudhashri** [comment]
Hi Shriya,

This project was dropped due to a discrepancy in implementing UWB and the
sensor fusion didn't prove efficient enough.

**Comment by shriyaBhat1** [comment]
Okay Thank you
