### ISSUE TITLE
No such NED type *ini*file Validation Problem

### ISSUE THREAD

**Issue by Vasudhashri** [inet-framework/inet#493]
I am using the versions of Omnet++ 5.5 and Veins 5.0. I tried running the scenario once again and i am getting the error message as below.
**No such NED type: RSUExampleScenario | Line 10 | Inifile Validation Problem.**

Attached screenshot for your reference. 
![image](https://user-images.githubusercontent.com/58476723/70227369-c64e5180-1752-11ea-8233-653b04f0b67c.png)

**Comment by Vasudhashri** [comment]
![image](https://user-images.githubusercontent.com/58476723/70230338-65c21300-1758-11ea-8d3f-e94a1d79aa01.png)

**Comment by levy** [comment]
This issue is related to the Veins project and not INET as you can see from Path column in the screenshots.

**Comment by safiIbrahim** [comment]
I want to know how to solve this problem
