### ISSUE TITLE
arraysize in copyDataFromBuffer() of ByteArray.cc seems incorrect

### ISSUE THREAD

**Issue by dodo5407** [inet-framework/inet#496]
Hi, 
I find a problem of raw-packet length when serializing/deserializing the IPv4 packet fragment. 

In copyDataFromBuffer function,  if nlength > data_arraysize, it will new a array of nlength size to replace the original one.

But it doesn't change the data_arraysize varible.

It seems need to add one line:`data_arraysize = nlength;`  below line 39 ?

https://github.com/inet-framework/inet/blob/e22ab63c0841641e24f8e4700a6e778a51fba0dc/src/inet/common/ByteArray.cc#L31-L42

**Comment by ZoltanBojthe** [comment]
The ByteArray class removed from inet master. Available alternatives: BytesChunk, BitsChunk, MemoryInputStream, MemoryOutputStream, std::vector<uint8_t>, std::vector<bool>
