### ISSUE TITLE
Methods that should be overloaded

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#499]
The methods getMaxCommunicationRange and getMaxInterferenceRange should be overloaded in Unit Disk Transmitter models, now returns NaN even if this is a valid parameter in the model

    virtual m getMaxCommunicationRange() const override { return communicationRange; }
    virtual m getMaxInterferenceRange() const override { return interferenceRange; }

**Comment by aarizaq** [comment]
The methods are overloaded in UnitDiskTransmitter but not in Ieee80211UnitDiskTransmitter

**Comment by aarizaq** [comment]
https://github.com/aarizaq/inetmanet-4.x/commit/7a3f28bd47611b6f7b4723ae26a2b2417ae836c8

**Comment by levy** [comment]
I cherry picked your patch, thanks!
