### ISSUE TITLE
618aaf7 breaks build on windows

### ISSUE THREAD

**Issue by tillsteinbach** [inet-framework/inet#50]
This commit breaks windows builds as windows does not know netif/in.h used in SerializerUtil.cc. I think on windows you can use Winsock2.h instead. But do we really want platform dependent stuff here?

See also my comment here:
https://github.com/inet-framework/inet/commit/618aaf7c535e59faf36bf3376496ab94eed2b215

**Comment by aarizaq** [comment]
Possible solution 

Replace 
#if !defined(_WIN32) && !defined(__WIN32__) && !defined(WIN32) && !defined(__CYGWIN__) && !defined(_WIN64)
#include <netinet/in.h>  // htonl, ntohl, ...
#endif

by
#if !defined(_WIN32) && !defined(__WIN32__) && !defined(WIN32) && !defined(__CYGWIN__) && !defined(_WIN64)
#include <netinet/in.h>  // htonl, ntohl, ...
#endif
#else
#ifndef _INC_WINDOWS
#include <windows.h>
#endif
#ifndef WINSOCK_API_LINKAGE
#define UNDEF_WINSOCK_API_LINKAGE
#ifdef  DECLSPEC_IMPORT
#define WINSOCK_API_LINKAGE DECLSPEC_IMPORT
#else
#define WINSOCK_API_LINKAGE
#endif
#endif /* WINSOCK_API_LINKAGE */
#define WSAAPI          WINAPI
WINSOCK_API_LINKAGE unsigned long WSAAPI htonl(unsigned long hostlong);
WINSOCK_API_LINKAGE unsigned short WSAAPI htons(unsigned short hostshort);
WINSOCK_API_LINKAGE unsigned long  WSAAPI ntohl(unsigned long  netlong);
WINSOCK_API_LINKAGE unsigned short WSAAPI ntohs(unsigned short netshort);
#endif

**Comment by avarga** [comment]
Fixed, INET compiles for me on Windows (OMNeT++ 5.0b1). Please reopen if there's more related issues.  commit: 0028c2f3a24107fe48cf70c953309e4ea3487647

**Comment by aarizaq** [comment]
Reopen with the last actualization
