### ISSUE TITLE
[Request] Use encrypted email in Travis-CI notification to avoid spam from forks

### ISSUE THREAD

**Issue by screw** [inet-framework/inet#505]
Would you consider to use encrypted email in Travis-CI settings for notifications to avoid getting spam from forked repositories?

Reference:
[https://github.com/travis-ci/travis-ci/issues/5063#issue-115477841](https://github.com/travis-ci/travis-ci/issues/5063#issue-115477841)
[https://github.com/facebook/flow/pull/1822](https://github.com/facebook/flow/pull/1822)

**Comment by torokati44** [comment]
Nice find, thanks! A bit hacky, but if it works...
Then again, our Travis config is exceedingly cursed already.

**Comment by torokati44** [comment]
Let's wait for an e-mail notification to arrive before closing this issue (this will most likely only happen next when some tests fail), just to confirm that decryption works, and I haven't made a mistake in the glorious YAML syntax.

**Comment by torokati44** [comment]
This change has been in the mainline master for quite some time now, and also in @screw's fork a couple times, but not in all branches yet.
If a build is triggered in a fork, on a branch/tag/hash that does not include this change, we will still get the notification about it.

**Comment by screw** [comment]
Did I do that again?!?

**Comment by torokati44** [comment]
Yep, a couple times, last week, on the `topic/ipsec` branch. No problem though! :)

**Comment by torokati44** [comment]
Yes, as we don't even use Travis CI for INET anymore.
