### ISSUE TITLE
Reception Power in dBm

### ISSUE THREAD

**Issue by gokseninarikan** [inet-framework/inet#506]
Maybe it is not a bug, but ı could not solve my problem.

Is there a way to genarate a report with showing reception power strength in unit of dBm.
I am using the following code when the save reception power. But it is saving in unit of mW.

@statistic[receptionPower](source="receptionMinSignalPower(radioMedium.signalArrivalStarted)"; record=last);

I try the following method. But it is giving a error. 
 @statistic[receptionPower(source="db2mW(receptionMinSignalPower(radioMedium.signalArrivalStarted))"; record=last);

Thanks

**Comment by levy** [comment]
This is not the right forum to ask questions. Please use the mailing list instead.
