### ISSUE TITLE
Bug: Dynamically creating modules in a vector crashes simulation

### ISSUE THREAD

**Issue by RedFu01** [inet-framework/inet#508]
While trying to implement a network where a lot of nodes appear and disappear I encountered a bug that the simulation crashes when I dynamically create more than two nodes. This behaviour can be reproduced by changing the scenario file in the wireless/dynamic example (https://github.com/inet-framework/inet/blob/master/examples/wireless/dynamic/scenario.xml) to
```xml
<scenario>
    <at t="10">
        <create-module type="inet.node.inet.AdhocHost" parent="." submodule="sourceNode" vector="true"/>
    </at>
    <at t="15">
        <create-module type="inet.node.inet.AdhocHost" parent="." submodule="sourceNode"/>
    </at>
    <at t="16">
        <create-module type="inet.node.inet.AdhocHost" parent="." submodule="sourceNode"/>
    </at>
    <at t="20">
        <delete-module module="sourceNode[0]"/>
    </at>
    <at t="25">
        <delete-module module="sourceNode[1]"/>
    </at>
</scenario>
```
The error thrown loosk like that
<img width="433" alt="Screenshot 2020-01-21 at 18 29 37" src="https://user-images.githubusercontent.com/6030114/72828399-d11a6280-3c7c-11ea-81d9-c7846c5c86a9.png">
and it seems like the problemn is that the index of the newly created module isnt correct (sourceNode[1] appears twice)
<img width="376" alt="Screenshot 2020-01-21 at 18 29 44" src="https://user-images.githubusercontent.com/6030114/72828397-d11a6280-3c7c-11ea-8a32-d3d76acc95a0.png">

Digging deeper I found that the index is determined at this place https://github.com/inet-framework/inet/blob/master/src/inet/common/scenario/ScenarioManager.cc#L316 and I could confirm that this value doesn't change during runtime and is only correct the first time. 

I'd really like to help out here but I can't figure out the problem. Does anybody have an idea? Is it maybe a bug in the omnet core?

Cheers!

**Comment by ZoltanBojthe** [comment]
Thank you for reporting issue.
I fixed it in inet master.
