### ISSUE TITLE
Error: NED package was not found.

### ISSUE THREAD

**Issue by shengun567** [inet-framework/inet#511]
when I change to the INET directory. then type "make makefiles"：
Then appear:
Then appear Error: NED package 'inet.tutorials.visualization' in feature 'visualizationtutorial' was not found.
Error: NED package 'inet.tutorials.configurator' in feature 'configuratortutorial' was not found.
Error: NED package 'inet.showcases.visualizer' in feature 'visualizershowcases' was not found.
Error: NED package 'inet.showcases.wireless' in feature 'wirelessshowcases' was not found.
Creating Makefile in /media/w1314520/_dde_data/package/inet-3.6.6/src... 
Who can tell me the reason?

**Comment by levy** [comment]
This is not the right forum to ask questions. Please use the mailing list instead.
