### ISSUE TITLE
Error compiling about osgEarth

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [inet-framework/inet#521]
I've installed osgEarth.But there is a error:
inet/visualizer/scene/SceneOsgEarthVisualizer.cc: In member function ‘virtual void inet::visualizer::SceneOsgEarthVisualizer::initializeScene()’:
inet/visualizer/scene/SceneOsgEarthVisualizer.cc:79:5: error: ‘geoTransform’ was not declared in this scope
     geoTransform = new osgEarth::GeoTransform();
     ^
inet/visualizer/scene/SceneOsgEarthVisualizer.cc:79:24: error: expected type-specifier
     geoTransform = new osgEarth::GeoTransform();
                        ^
inet/visualizer/scene/SceneOsgEarthVisualizer.cc: In member function ‘virtual void inet::visualizer::SceneOsgEarthVisualizer::initializeLocator()’:
inet/visualizer/scene/SceneOsgEarthVisualizer.cc:89:5: error: ‘geoTransform’ was not declared in this scope
     geoTransform->setPosition(osgEarth::GeoPoint(mapNode->getMapSRS()->getGeogr
     ^

**Comment by torokati44** [comment]
Which version of osgEarth do you have installed? On what kind of system?
Also, the error message might be incomplete...
Seeing that this issue is a couple months old already, can you still reproduce it on the latest releases (or current master)?
And is it still relevant?
