### ISSUE TITLE
Regarding Mobility concept- Anti clockwise direction 

### ISSUE THREAD

**Issue by Grushika** [inet-framework/inet#524]
In INET framework, in RectangleMobility.cc , only clockwise direction of a node is defined. Can I also get the code in anti clockwise direction. I have 2 nodes in ini file. One node is moving in clockwise direction and other node should move in anti clockwise direction. So, please anyone provide me the code.

**Comment by levy** [comment]
This is not the right forum to ask for modifications. Please use the mailing list.

**Comment by Grushika** [comment]
Hallo,

     Where can I find the email to send the issue ?
