### ISSUE TITLE
Inappropriate olsr version

### ISSUE THREAD

**Issue by tamarbuterman** [inet-framework/inet#525]
Hi,
I'm tring to use olsr with inet 4 and it faild to run because it's use unexisting files. (like UDPPakcet.h)
I would like to know how can I update olsr so I csn use it.
Thanks

**Comment by aarizaq** [comment]
The code of OLSR for inet 4 is available in inetmanet 4.

**Comment by tamarbuterman** [comment]
Thanks for the reply,

**Comment by levy** [comment]
Closing because it's not an INET issue.
