### ISSUE TITLE
UdpSocket socketState remains connected even after close()

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#526]
https://github.com/inet-framework/inet/blob/76f495bca447551d7528c0dd5c153ecdebf94147/src/inet/transportlayer/contract/udp/UdpSocket.cc#L97-L104

The final line should be `socketState = CLOSED;`

Happy to create pull request but seems pointless for such a trivial fix

**Comment by levy** [comment]
Hmm, that indeed looks weird at a first glance but the sockState is set to CLOSED when the UDP_I_SOCKET_CLOSED indication is received. So I'm not sure what to do.

**Comment by edlongman** [comment]
I looked through the Tcp module and that appears to set `sockState` in close and `processMessage`

https://github.com/inet-framework/inet/blob/013ca0574c07307b7ca26398ab5b68a4a57e63bf/src/inet/transportlayer/contract/tcp/TcpSocket.cc#L170-L182

`TcpSocket::processMessage` 
https://github.com/inet-framework/inet/blob/013ca0574c07307b7ca26398ab5b68a4a57e63bf/src/inet/transportlayer/contract/tcp/TcpSocket.cc#L346-L351

**Comment by levy** [comment]
Indeed, but it sets a separate LOCALLY_CLOSED state until the indication arrives when it sets to state to CLOSED. Maybe the UdpSocket should do the same?

**Comment by edlongman** [comment]
Although drawing more comparisons perhaps States `BOUND` and `NOT_BOUND` need to be added too.

I don't know where to find a simple description of  a socket standard that would describe any others we are missing

**Comment by levy** [comment]
I would be reluctant to add states which are not read anywhere. But if you can come up with additional checks for the new states here and there, then it would be desirable.

**Comment by ZoltanBojthe** [comment]
fixed in commit 6e1e4928c49e79754505219666488888f3627094
