### ISSUE TITLE
Error in AODV

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#53]
There is an error in the method 
void AODVRouting::handleBlackListTimer()
if (it->second <= simTime()) {
should be
if (current->second <= simTime()) {

**Comment by Benmartin92** [comment]
Thanks for your reporting, thix bug has been already fixed in the integration branch.

https://github.com/inet-framework/inet/commit/9620327ebc6c7fbf881a8725ff90ca3f5f0f0b65.
