### ISSUE TITLE
Printing routing table to a file in omnet++

### ISSUE THREAD

**Issue by hasti1993** [inet-framework/inet#530]
Hi,
I use inet/omnet++. I want to print each nodes routing table to a file and see the path/nexthop that ospf chooses for each packet from src to dst. how can i create such that file for each node?
i used **configure.dumproutes = true. it says that "dumpRoutes: if true, then the module prints configured and optimized routing tables for all nodes to the module output" according to inet/user-manual. so where can i find the output module? where does it mean?
I also used the module routingTableRecorder "Records changes in the routing tables (~Ipv4RoutingTable) and interface tables (~InterfaceTable) of all hosts and routers. The filename has to be specified in the routinglog-file configuration option that this module registers.". how to specify the file name in routinglog-file configuration? 
any body knows this?

**Comment by levy** [comment]
Look which word did you not understand in this sentence?

"This is not the right forum to ask questions. Please use the mailing list for this purpose."

Please stop this.

**Comment by hasti1993** [comment]
please give me the link to mailing list

**Comment by levy** [comment]
Come on, you can do better than this.

https://www.google.com/search?q=omnet%2B%2B+inet+mailing+list&spell=1&sa=X&ved=2ahUKEwjEkL6hjtTpAhXExIsKHf8kDoIQBSgAegQICxAp&biw=1422&bih=733&dpr=1.3
