### ISSUE TITLE
some classes and methods are not accesible in windows

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#535]
https://github.com/aarizaq/inetmanet-4.x/commit/8b9fa85117f11a10bb1d1afb0d5b16e553e052c5

This remove some unnecessary INET_API exports
https://github.com/aarizaq/inetmanet-4.x/commit/e1a85bb166b106998cf975217ae067ca67127edb

**Comment by levy** [comment]
Could you please send a pull request with these two patches against master?

That would be nice!

**Comment by aarizaq** [comment]
Ok, I will create a temporal branch, in other case you could receive unnecesary code from inetmanet :).

**Comment by levy** [comment]
Thanks! That's very kind of you.

**Comment by aarizaq** [comment]
I have sent the request of merge, I have included several patchs
1.- fix problem in windows with export classes.
2.- Problem with thugmeter
3.- Problem with the bandwith in 802.11
4.- Broadcast storm problem in Dymo.
Every one of them are in a different commit.

**Comment by levy** [comment]
This has been fixed in master by patches provided by @aarizaq
