### ISSUE TITLE
Compilation fails on Ubuntu 18 again

### ISSUE THREAD

**Issue by keithbriggs** [inet-framework/inet#541]
inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.cc
In file included from ./inet/environment/common/PhysicalEnvironment.h:23:0,
                 from ./inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.h:21,
                 from inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.cc:25:
./inet/common/geometry/common/GeographicCoordinateSystem.h:84:10: error: ‘Matrixd’ in namespace ‘inet::osg’ does not name a type
     osg::Matrixd locatorMatrix;
          ^~~~~~~
./inet/common/geometry/common/GeographicCoordinateSystem.h:85:10: error: ‘Matrixd’ in namespace ‘inet::osg’ does not name a type
     osg::Matrixd inverseLocatorMatrix;
          ^~~~~~~
Makefile:1754: recipe for target '../out/gcc-release/src/inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.o' failed
make[1]: *** [../out/gcc-release/src/inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.o] Error 1
make[1]: Leaving directory '/home/kbriggs/Downloads/inet4/src'
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lakshmikrish-97** [comment]
I also have the same error on using Mac OS Catalina 10.15.7 
OMNeT++ 5.62 and INET4.2.1

In file included from ./inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.h:21:
In file included from ./inet/environment/common/PhysicalEnvironment.h:23:
./inet/common/geometry/common/GeographicCoordinateSystem.h:84:5: error: no type named 'Matrixd' in namespace 'inet::osg'; did you mean '::osg::Matrixd'?
    osg::Matrixd locatorMatrix;
    ^~~~~~~~~~~~
    ::osg::Matrixd
/Users/lakshmikrish/omnetpp-5.6.2/tools/macosx/include/osg/Matrixd:26:18: note: '::osg::Matrixd' declared here
class OSG_EXPORT Matrixd
                 ^
In file included from inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.cc:25:
In file included from ./inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.h:21:
In file included from ./inet/environment/common/PhysicalEnvironment.h:23:
./inet/common/geometry/common/GeographicCoordinateSystem.h:85:5: error: no type named 'Matrixd' in namespace 'inet::osg'; did you mean '::osg::Matrixd'?
    osg::Matrixd inverseLocatorMatrix;
    ^~~~~~~~~~~~
    ::osg::Matrixd
/Users/lakshmikrish/omnetpp-5.6.2/tools/macosx/include/osg/Matrixd:26:18: note: '::osg::Matrixd' declared here
class OSG_EXPORT Matrixd
                 ^
2 errors generated.
make[1]: *** [../out/clang-release/src/inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.o] Error 1
make: *** [all] Error 2
