### ISSUE TITLE
INSTALL file is unclear

### ISSUE THREAD

**Issue by keithbriggs** [inet-framework/inet#542]
INSTALL says:

    Make sure your OMNeT++ installation works OK (e.g. try running the samples)
    and it is in the path (to test, try the command "which nedtool")

When I do this, nothing is reported.   INSTALL doesn't say whether this is good or bad, and it doesn't say what nedtool is.  On the other hand, if I do "which omnetpp" I get the full path to the executable.   Does this mean it is ok?

**Comment by levy** [comment]
Thanks!

I have changed those lines to:

```
Make sure your OMNeT++ installation works OK (e.g. try running the samples)
and it is in the path (to test, try the command "which omnetpp", it should print
the path of the executable).
```
