### ISSUE TITLE
QosClassifier does not work on wireless interface of access point

### ISSUE THREAD

**Issue by dstolpmann** [inet-framework/inet#548]
Hi,
we are currently looking into QoS in IEEE 802.11. We have a simple simulation model where UDP packets are exchanged between a wired and a wireless host via an access point.
![Screenshot from 2020-07-13 14-48-05](https://user-images.githubusercontent.com/7644267/87307972-d0230900-c51a-11ea-81aa-8172c5c6575a.png)

We want to prioritize some of the traffic on the wireless network. For this, we enabled QoS and use the QosClassifier to classify the traffic. However, based on our simulation results, the classification and prioritization does only work for the wireless host and not for the access point. This can be seen in this screenshot:
![Screenshot from 2020-07-13 15-20-00](https://user-images.githubusercontent.com/7644267/87309652-2c872800-c51d-11ea-8ee2-de102685ddae.png)

Looking into details, we found out that packets on the access point have an Ethernet header when they hit the QosClassifier. However, the QosClassifier cannot handle the Ethernet header and thus classifies all traffic as AC_BE. For the wireless host, the packets do not have an Ethernet header and the classifier works like expected.

We modified the QosClassifier to handle the Ethernet header properly, which gives us the expected results, as shown in the screenshot below. Our modified version of the QosClassifier for INET 4.2.0 can be found in the attached archive together with our simulation model. The explained behavior has not changed with the current master version of INET. We are not sure if this is a bug or intended behavior, but are happy to provide a pull request with our fix for the current master version of INET.
![Screenshot from 2020-07-13 15-24-29](https://user-images.githubusercontent.com/7644267/87309710-3f016180-c51d-11ea-8469-a8ec3862f226.png)

Archive with simulation model and fixed QosClassifier:
[wiredandwirelesshostswithapqos.zip](https://github.com/inet-framework/inet/files/4912757/wiredandwirelesshostswithapqos.zip)

**Comment by levy** [comment]
It seems to be a reasonable extension, so please send a PR against the master branch. Also, if you are at it, ethernet is an optional feature, so checking WITH_ETHERNET is necessary. Thank you!
