### ISSUE TITLE
ERROR in build INET, thereis  no "rescheduleAfter" function declaration in OscillatorBasedClock.cc 

### ISSUE THREAD

**Issue by weiyuxingkong** [inet-framework/inet#552]
inet/clock/model/OscillatorBasedClock.cc
inet/clock/model/OscillatorBasedClock.cc: In member function ‘virtual void inet::OscillatorBasedClock::receiveSignal(omnetpp::cComponent*, int, omnetpp::cObject*, omnetpp::cObject*)’:
inet/clock/model/OscillatorBasedClock.cc:142:31: error: ‘class omnetpp::cSimpleModule’ has no member named ‘rescheduleAfter’
                 targetModule->rescheduleAfter(simTimeDelay, event);   
                               ^
inet/clock/model/OscillatorBasedClock.cc:150:31: error: ‘class omnetpp::cSimpleModule’ has no member named ‘rescheduleAt’
                 targetModule->rescheduleAt(arrivalSimTime, event);    
                               ^
Makefile:1805: recipe for target '../out/gcc-release/src/inet/clock/model/OscillatorBasedClock.o' failed
make[1]: Leaving directory '/home/zw/Nesting/inet-master/src'
make[1]: *** [../out/gcc-release/src/inet/clock/model/OscillatorBasedClock.o] Error 1
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2

I find there is no "rescheduleAfter" function declaration  in OscillatorBasedClock.cc

**Comment by levy** [comment]
Thanks for the bug report!

The upcoming INET 4.3 version will most likely require the latest OMNeT 6.0 preview release.
Anyway, I fixed all compilation errors in the INET master branch for the OMNeT 5.x branch.
