### ISSUE TITLE
MobilityCanvasVisualizer drawings not deleted when deleting a module at runtime

### ISSUE THREAD

**Issue by sommer** [inet-framework/inet#555]
Platform: OMNeT++ 5.6.1 Qtenv

In INET 4.2.0, when visualizing mobility using the `MobilityCanvasVisualizer`, deleting a module at runtime does not delete the mobility module position, trail, etc.

Sample screenshot (from `examples/wireless/dynamic`) before deletion:

<img width="349" alt="before" src="https://user-images.githubusercontent.com/29601/89733710-bad8c600-da57-11ea-910f-f058567e382e.png">

after deletion:

<img width="326" alt="after" src="https://user-images.githubusercontent.com/29601/89733709-b9a79900-da57-11ea-8d8f-9d09ae17164c.png">

Steps to reproduce:

...change to directory
```
cd inet
cd examples/wireless/dynamic
```
...then add the following to `omnetpp.ini`...
```
**.mobilityVisualizer.displayPositions = true
**.mobilityVisualizer.displayOrientations = true
**.mobilityVisualizer.displayVelocities = true
**.mobilityVisualizer.displayMovementTrails = true
```
...then run the simulation, express run to t=19.9s, and execute one more event.

**Comment by sommer** [comment]
I should add that other visualizers might also need looking after - they really don't like nodes being deleted while they are visualizing something for the node.

Similarly, the INET framework tends to crash when nodes are being deleted while they are transmitting, evident when moving the `delete-module` event of `sourceNode[0]` in the above-mentioned example simulation to `10.000240` seconds into the simulation (i.e., while it's transmitting)

```
    <at t="10.000240">
        <delete-module module="sourceNode[0]"/>
    </at>
```

**Comment by levy** [comment]
This bug is fixed in the master branch now, thanks for reporting it!
