### ISSUE TITLE
inet aodv browse data question 

### ISSUE THREAD

**Issue by tao593430453** [inet-framework/inet#559]
![image](https://user-images.githubusercontent.com/69671193/91788683-6633ff80-ec3f-11ea-8deb-222dccd81c71.png)

why only host[0] put out 'pingRxSeq:count , pingTxSeq:count'.
I want know all host about'pingRxSeq:count, pingTxSaq:count' 

please help me.

use inet aodv

**Comment by levy** [comment]
This is not the right forum to ask questions, please use the mailing list.
