### ISSUE TITLE
Doesn't compile with pre8 

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#560]
The latest version doesn't compile with omnetpp 6-pre8 due to the method rescheduleAfter, new pre version should be necessary

**Comment by aarizaq** [comment]
The latest changes in EtherBus, also, doesn't compile with 5.6.2

**Comment by levy** [comment]
I'm sorry for the inconvenience, but the INET master branch only compiles with the latest OMNeT master branch at the moment.

**Comment by aarizaq** [comment]
Ok, I have removed the latest commits that produce the problems,

**Comment by sanaz-afzali** [comment]
I have installed latest version of Omnetpp (currently 5.6.2 is the latest release) and latest version of inet (4.2) but it doesn't compile. Neither on linux, nor on windows. 

 **** Incremental Build of configuration debug for project inet ****
make MODE=debug -j8 all 
make[1]: Entering directory '/d/programs/omnetpp-5.6.2-src-windows/omnetpp-5.6.2/git/inet/src'
*** COMPILING with:
clang++ -c -std=c++11 -g -Wall -MMD -MP -MF .d    -isystem /usr/include -isystem /mingw64/include -Wno-deprecated-register -Wno-unused-function -fno-omit-frame-pointer  -DXMLPARSER=libxml -DPREFER_QTENV -DWITH_QTENV -DWITH_PARSIM -DWITH_NETBUILDER -DWITH_OSG -DWITH_OSGEARTH -DINET_EXPORT -Wno-overloaded-virtual -include inet/common/precompiled_debug.h  -DINET_EXPORT -I. -ID:/programs/omnetpp-5.6.2-src-windows/omnetpp-5.6.2/include
*** LINKING with:
clang++ -shared  -o ../out/clang-debug/src/libINET_dbg.dll -Wl,--no-as-needed -Wl,--whole-archive  -lws2_32 -Wl,--no-whole-archive -loppenvir_dbg -loppsim_dbg -lstdc++  -losg -losgText -losgDB -losgGA -losgViewer -losgUtil -lOpenThreads  -losgEarth -losgEarthUtil  -Wl,-rpath,D:/programs/omnetpp-5.6.2-src-windows/omnetpp-5.6.2/lib -Wl,-rpath,D:/programs/omnetpp-5.6.2-src-windows/omnetpp-5.6.2/tools/win64/lib -Wl,-rpath,. -L/usr/bin -L/usr/lib -L/mingw64/lib -LD:/programs/omnetpp-5.6.2-src-windows/omnetpp-5.6.2/lib ../out/clang-debug/src/typeinfo.def
Building...
inet/applications/base/ApplicationBase.cc
inet/applications/base/ApplicationPacketSerializer.cc
inet/applications/dhcp/DhcpClient.cc
In file included from inet/applications/base/ApplicationBase.cc:18:
In file included from .\inet/applications/base/ApplicationBase.h:21:
In file included from .\inet/common/lifecycle/ModuleOperations.h:23:
In file included from .\inet/common/lifecycle/LifecycleOperation.h:20:
.\inet/common/INETDefs.h:45:4: error: At least OMNeT++/OMNEST version 6.0pre9 required
#  error At least OMNeT++/OMNEST version 6.0pre9 required
   ^
In file included from inet/applications/base/ApplicationPacketSerializer.cc:16:
In file included from .\inet/applications/base/ApplicationPacket_m.h:36:
In file included from .\inet/common/INETDefs_m.h:33:
.\inet/common/INETDefs.h:45:4: error: At least OMNeT++/OMNEST version 6.0pre9 required
#  error At least OMNeT++/OMNEST version 6.0pre9 required
   ^
1 error generated.
make[1]: *** [Makefile:1768: ../out/clang-debug/src/inet/applications/base/ApplicationBase.o] Error 1
make[1]: *** Waiting for unfinished jobs....
inet/applications/dhcp/DhcpMessageSerializer.cc
inet/applications/dhcp/DhcpServer.cc
In file included from inet/applications/dhcp/DhcpClient.cc:20:
In file included from .\inet/applications/dhcp/DhcpClient.h:23:
In file included from .\inet/applications/base/ApplicationBase.h:21:
In file included from .\inet/common/lifecycle/ModuleOperations.h:23:
In file included from .\inet/common/lifecycle/LifecycleOperation.h:20:
.\inet/common/INETDefs.h:45:4: error: At least OMNeT++/OMNEST version 6.0pre9 required
#  error At least OMNeT++/OMNEST version 6.0pre9 required
   ^
In file included from inet/applications/dhcp/DhcpClient.cc:20:
In file included from .\inet/applications/dhcp/DhcpClient.h:24:
In file included from .\inet/applications/dhcp/DhcpLease.h:23:
In file included from .\inet/networklayer/arp/ipv4/Arp.h:26:
In file included from .\inet/common/ModuleAccess.h:22:
In file included from .\inet/networklayer/contract/IInterfaceTable.h:22:
In file included from .\inet/networklayer/common/InterfaceEntry.h:25:
.\inet/common/Simsignals.h:123:46: error: unknown type name 'intval_t'
void printSignalBanner(simsignal_t signalID, intval_t value, const cObject *details);
                                             ^
1 error generated.
make[1]: *** [Makefile:1769: ../out/clang-debug/src/inet/applications/base/ApplicationPacketSerializer.o] Error 1
In file included from inet/applications/dhcp/DhcpMessageSerializer.cc:16:
In file included from .\inet/common/packet/serializer/ChunkSerializerRegistry.h:19:
In file included from .\inet/common/packet/serializer/ChunkSerializer.h:19:
In file included from .\inet/common/MemoryInputStream.h:19:
In file included from .\inet/common/Units.h:29:
In file included from .\inet/common/INETMath.h:31:
.\inet/common/INETDefs.h:45:4: error: At least OMNeT++/OMNEST version 6.0pre9 required
#  error At least OMNeT++/OMNEST version 6.0pre9 required
   ^
In file included from inet/applications/dhcp/DhcpClient.cc:20:
In file included from .\inet/applications/dhcp/DhcpClient.h:28:
In file included from .\inet/networklayer/ipv4/Ipv4RoutingTable.h:36:
In file included from .\inet/networklayer/ipv4/IIpv4RoutingTable.h:26:
.\inet/networklayer/ipv4/Ipv4Route.h:62:25: warning: 'detailedInfo' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    virtual std::string detailedInfo() const;
                        ^
D:/programs\omnetpp-5.6.2-src-windows\omnetpp-5.6.2\include\omnetpp\cobject.h:165:40: note: overridden virtual function is here
    _OPPDEPRECATED virtual std::string detailedInfo() const {return "";}
                                       ^
In file included from inet/applications/dhcp/DhcpClient.cc:20:
In file included from .\inet/applications/dhcp/DhcpClient.h:28:
In file included from .\inet/networklayer/ipv4/Ipv4RoutingTable.h:36:
In file included from .\inet/networklayer/ipv4/IIpv4RoutingTable.h:26:
.\inet/networklayer/ipv4/Ipv4Route.h:175:25: warning: 'detailedInfo' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    virtual std::string detailedInfo() const;
                        ^
D:/programs\omnetpp-5.6.2-src-windows\omnetpp-5.6.2\include\omnetpp\cobject.h:165:40: note: overridden virtual function is here
    _OPPDEPRECATED virtual std::string detailedInfo() const {return "";}
                                       ^
In file included from inet/applications/dhcp/DhcpServer.cc:22:
In file included from .\inet/applications/dhcp/DhcpServer.h:25:
.\inet/common/INETDefs.h:45:4: error: At least OMNeT++/OMNEST version 6.0pre9 required
#  error At least OMNeT++/OMNEST version 6.0pre9 required
   ^
In file included from inet/applications/dhcp/DhcpClient.cc:25:
.\inet/networklayer/ipv4/Ipv4InterfaceData.h:172:25: warning: 'detailedInfo' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    virtual std::string detailedInfo() const;
                        ^
D:/programs\omnetpp-5.6.2-src-windows\omnetpp-5.6.2\include\omnetpp\cobject.h:165:40: note: overridden virtual function is here
    _OPPDEPRECATED virtual std::string detailedInfo() const {return "";}
                                       ^
inet/applications/dhcp/DhcpClient.cc:356:5: error: use of undeclared identifier 'rescheduleAfter'; did you mean 'scheduleAt'?
    rescheduleAfter(lease->leaseTime, leaseTimer);
    ^~~~~~~~~~~~~~~
    scheduleAt
D:/programs\omnetpp-5.6.2-src-windows\omnetpp-5.6.2\include\omnetpp\csimplemodule.h:335:18: note: 'scheduleAt' declared here
    virtual void scheduleAt(simtime_t t, cMessage *msg);
                 ^
In file included from inet/applications/dhcp/DhcpServer.cc:22:
In file included from .\inet/applications/dhcp/DhcpServer.h:28:
In file included from .\inet/applications/dhcp/DhcpLease.h:23:
In file included from .\inet/networklayer/arp/ipv4/Arp.h:26:
In file included from .\inet/common/ModuleAccess.h:22:
In file included from .\inet/networklayer/contract/IInterfaceTable.h:22:
In file included from .\inet/networklayer/common/InterfaceEntry.h:25:
.\inet/common/Simsignals.h:123:46: error: unknown type name 'intval_t'
void printSignalBanner(simsignal_t signalID, intval_t value, const cObject *details);
                                             ^
inet/applications/dhcp/DhcpClient.cc:688:5: error: use of undeclared identifier 'rescheduleAfter'; did you mean 'scheduleAt'?
    rescheduleAfter(responseTimeout, timerTo);
    ^~~~~~~~~~~~~~~
    scheduleAt
D:/programs\omnetpp-5.6.2-src-windows\omnetpp-5.6.2\include\omnetpp\csimplemodule.h:335:18: note: 'scheduleAt' declared here
    virtual void scheduleAt(simtime_t t, cMessage *msg);
                 ^
inet/applications/dhcp/DhcpClient.cc:694:5: error: use of undeclared identifier 'rescheduleAfter'; did you mean 'scheduleAt'?
    rescheduleAfter(lease->renewalTime, timerT1);    // RFC 2131 4.4.5
    ^~~~~~~~~~~~~~~
    scheduleAt
D:/programs\omnetpp-5.6.2-src-windows\omnetpp-5.6.2\include\omnetpp\csimplemodule.h:335:18: note: 'scheduleAt' declared here
    virtual void scheduleAt(simtime_t t, cMessage *msg);
                 ^
inet/applications/dhcp/DhcpClient.cc:700:5: error: use of undeclared identifier 'rescheduleAfter'; did you mean 'scheduleAt'?
    rescheduleAfter(lease->rebindTime, timerT2);    // RFC 2131 4.4.5
    ^~~~~~~~~~~~~~~
    scheduleAt
D:/programs\omnetpp-5.6.2-src-windows\omnetpp-5.6.2\include\omnetpp\csimplemodule.h:335:18: note: 'scheduleAt' declared here
    virtual void scheduleAt(simtime_t t, cMessage *msg);
                 ^
In file included from inet/applications/dhcp/DhcpServer.cc:27:
.\inet/networklayer/ipv4/Ipv4InterfaceData.h:172:25: warning: 'detailedInfo' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    virtual std::string detailedInfo() const;
                        ^
D:/programs\omnetpp-5.6.2-src-windows\omnetpp-5.6.2\include\omnetpp\cobject.h:165:40: note: overridden virtual function is here
    _OPPDEPRECATED virtual std::string detailedInfo() const {return "";}
                                       ^
3 warnings and 6 errors generated.
1 error generated.
make[1]: *** [Makefile:1769: ../out/clang-debug/src/inet/applications/dhcp/DhcpClient.o] Error 1
make[1]: *** [Makefile:1769: ../out/clang-debug/src/inet/applications/dhcp/DhcpMessageSerializer.o] Error 1
1 warning and 2 errors generated.
make[1]: *** [Makefile:1769: ../out/clang-debug/src/inet/applications/dhcp/DhcpServer.o] Error 1
make[1]: Leaving directory '/d/programs/omnetpp-5.6.2-src-windows/omnetpp-5.6.2/git/inet/src'
make: *** [Makefile:7: all] Error 2
"make MODE=debug -j8 all" terminated with exit code 2. Build might be incomplete.

12:09:30 Build Failed. 18 errors, 4 warnings. (took 9s.468ms)

**Comment by levy** [comment]
Is this the master branch? If so, then it's in a flux and OMNET is also updated quite often. So you should wait until everything settles down. In any case, the INET master branch will only work with OMNET master branch until the next release.

**Comment by levy** [comment]
With the release of the OMNeT 6 preview 9 release and all related new INET releases, this problem should be solved. Also, the INET master branch should compile with the latest OMNeT release or the latest OMNeT master branch.
