### ISSUE TITLE
Emulation SOLVED

### ISSUE THREAD

**Issue by lIkesimba9** [inet-framework/inet#562]
I try to run emulation examples, and i run this comands $ ```
sudo setcap cap_net_raw,cap_net_admin=eip opp_run_dbg
$ sudo setcap cap_net_raw,cap_net_admin=eip opp_run_release
``` but i get error `Cannot open socket -- in module (inet::ExtEthernetSocket) ExtClientExample.peer.eth[0].socket (id=20), during network initialization` but when i run omnet as root, i didn't this error.

**Comment by lIkesimba9** [comment]
I solved this problem, need to run this command for all files, which have in name "opp_run.*".

**Comment by levy** [comment]
Closing because it's marked solved.

**Comment by zhangteng0526** [comment]
> 我解决了这个问题，需要对名称为“opp_run.*”的所有文件运行此命令。
Is it convenient to contact you? After executing these commands, I found that I still cannot execute the examples in inet. I would like to ask for advice

**Comment by lIkesimba9** [comment]
I create example here https://github.com/lIkesimba9/TwoRoutersInet

**Comment by zhangteng0526** [comment]
> 我在这里创建示例https://github.com/lIkesimba9/TwoRoutersInet
Thank you for your example, I will refer to it. You said need to run this command for all files, which have in name "opp_run.*". You said need to run this command for all files, which have in name "opp_run.*".
I executed the following four commands:
sudo setcap cap_net_raw,cap_net_admin=eip opp_run
sudo setcap cap_net_raw,cap_net_admin=eip opp_run_dbg
sudo setcap cap_net_raw,cap_net_admin=eip opp_runall
sudo setcap cap_net_raw,cap_net_admin=eip opp_run_release
However, when running the server instance, the message Cannot open socket -- in module (inet::ExtEthernetSocket) HITLNetwork.router.eth[0].socket (id=41), during network initialization
Can you help me please? Thank you here

**Comment by lIkesimba9** [comment]
You need to run the project with root rights and you also need to run these commands with root rights.

**Comment by DBC201** [comment]
For anyone who encounters this issue, I was able to solve this by just giving the necessary permissions to the output executable instead of omnet binaries.

So basically, cd to your src folder for your simulation, and give the permissions to the executable there.
