### ISSUE TITLE
Errors when building project using inet and omnet++ in windows 10

### ISSUE THREAD

**Issue by bashartaj** [inet-framework/inet#563]
15:56:39 **** Incremental Build of configuration release for project 
FirstProject ****
make MODE=release all 
cd src && /usr/bin/make
make[1]: Entering directory '/c/omnetpp-5.6.2/samples/FirstProject/src'
Creating executable: ../out/clang-release/src/FirstProject.exe
C:\omnetpp-5.6.2\tools\win64\mingw64\bin\ld: cannot find -lINET
clang++.exe: error: linker command failed with exit code 1 (use -v to see 
invocation)
make[1]: *** [Makefile:101: ../out/clang-release/src/FirstProject.exe] 
Error 1
make[1]: Leaving directory '/c/omnetpp-5.6.2/samples/FirstProject/src'
make: *** [Makefile:2: all] Error 2
"make MODE=release all" terminated with exit code 2. Build might be 
incomplete.

15:56:40 Build Failed. 3 errors, 0 warnings. (took 1s.125ms)

**Comment by levy** [comment]
Cannot reproduce this issue. I'm not even sure that it is an issue with INET.
