### ISSUE TITLE
The transmitter and receiver in the 802154models have incorrect typenames

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#565]
https://github.com/inet-framework/inet/blob/0bc8bff6e3558cfc57596af544ec20a9725e5167/src/inet/physicallayer/ieee802154/packetlevel/Ieee802154NarrowbandRadio.ned#L27

Corrections `Ieee802154ScalarReceiver` => `Ieee802154NarrowbandScalarReceiver` 
Corrections `Ieee802154DimensionalReceiver` => `Ieee802154NarrowbandDimensionalReceiver` 
Corrections `Ieee802154ScalarΤransmitter` => `Ieee802154NarrowbandScalarΤransmitter` 
Corrections `Ieee802154DimensionalΤransmitter` => `Ieee802154NarrowbandDimensionalΤransmitter`

**Comment by levy** [comment]
Indeed, thanks for reporting this.

**Comment by levy** [comment]
This has been fixed in master, thanks!
