### ISSUE TITLE
Error using dynamically linked modules on windows with ModuleAccess.h

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#566]
I have built a custom MAC layer in a separate project that references the INET library and uses the INET Physical layer implementations for radio communication.
When compilling an error is thrown ` dllimport cannot be applied non-inline functions` for the `findConnected...` functions in `ModuleAccess.h` which is being used.

OS: Windows 10
OMNeT 5.6.2 INET 4
Clang compiller

Additionally, there are lots of warnings of `......  redeclared inline; 'dllimport' attribute ignored [-Wignored-attributes]` and `redeclared without 'dllimport' attribute: previous 'dllimport' ignored` for lots of inline functions in header files.

When configuring OMNeT there was a warning shown: no dlopen(): dynamic loading of libs not possible. 
However I didn't think this was required by omnet as stated before https://groups.google.com/g/omnetpp/c/RrTIeGp01HM

**Comment by edlongman** [comment]
I think the warnings have come back to bite, some months down the line.

Using the `getModuleFromPar` function to get a non `inet` child module I get the following error:
```
undefined reference to 'CustomRoutingTable* inet::getModuleFromPar<CustomRoutingTable>(omnetpp::cPar&, omnetpp::cModule const*, bool)'
```

Regarding the original warnings it seems the compiler is always trying to use the function signature in the DLL acording to the INET_API definition, however it should be using the templated inline function. Not sure exactly what is going on here though.

## Workaround
```
        auto const routingTableModule = getModuleFromPar<cModule>(par("routingTableModule"), this);
        routingTable = check_and_cast<CustomRoutingTable*>(routingTableModule);
```

**Comment by edlongman** [comment]
Again this has come back to bite again, it compilled fine into debug mode but release mode doesn't link `getModuleFromPar<cModule>`  *sometimes*. So a new work around of deconstructing the `getModuleFromPar` function is required giving: 
```cpp
        const char *radioModulePath = par("dataRadioModule");
        cModule *radioModule = getModuleByPath(radioModulePath);
        dataRadio = check_and_cast<IRadio *>(radioModule);
```

**Comment by rhornig** [comment]
I cannot reproduce this. If this is still a problem with INET 4.4 and OMNET 6, please provide a minimal example and re-open this.
