### ISSUE TITLE
Ieee802154Mac is missing a Serializer class 

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#567]
There is no packet serializer/deserialzier is provided for the Ieee802154Mac. This means intereference between it and other protocols cannot be investigated along with systemC simulation of other decoding models.

It's probably a simple one to write but I've not written a serializer before so would likely make a mess of it

Also LMAC is missing one.

**Comment by ZoltanBojthe** [comment]
Added an INET-specific ieee 802.15.4 serializer/deserializer

**Comment by ZoltanBojthe** [comment]
Added an INET-specific serializer/deserializer.
