### ISSUE TITLE
"getDuration method" in the ITransmission interface "ITransmission.h"

### ISSUE THREAD

**Issue by BadreddineYACHEUR** [inet-framework/inet#568]
Hello @aarizaq , 

Does the getDuration() method in the ITransmission Interface returns the latency between the transmitter and the receiver (i.e. Does it contain the propagation time?) ? 

Thanks.

**Comment by aarizaq** [comment]
I am not sure, but I think that is the transmission, the time that the transmitter needs to transmit the packet, the propagation in this case is not included

**Comment by BadreddineYACHEUR** [comment]
Okey, thanks for the answer, i will try to investigate more on this.

**Comment by levy** [comment]
This is not the right forum to ask questions. Please use the mailing list for that.
