### ISSUE TITLE
Hello guys. I get some errors when I build project "inet-master" in omnet++. 

### ISSUE THREAD

**Issue by alic-antunez** [inet-framework/inet#569]
I'm newbie in omnet++ and I was lauching inet but I get errors and I don't know why, I just cloned the inet repo from here to be imported in omnet++. 
![inet-master-error](https://user-images.githubusercontent.com/68139074/97615921-8420a500-19e1-11eb-8007-1eea1aa75b31.PNG)

**Comment by avarga** [comment]
It requires OMNeT++ 6.0 preview 9, released a few days ago. See https://omnetpp.org/download/preview
