### ISSUE TITLE
INET+4.2.1 compiling failure using OMNet ++5.6.2

### ISSUE THREAD

**Issue by kaldabbas** [inet-framework/inet#576]
Hi,

I tried to build INET-4.2.1 using OMNet++5.6.2, however, building the project failed. 
I am using windows 10. Downloaded the INET-4.2.1 from Github on the 20.11.2020

 attached you will find the failures
[OMNet_Failure.txt](https://github.com/inet-framework/inet/files/5575163/OMNet_Failure.txt)

I would appreciate your help

**Comment by torokati44** [comment]
INET v4.2.1 [(the release)](https://github.com/inet-framework/inet/releases/tag/v4.2.1) does not contain the error message you attached: https://github.com/inet-framework/inet/blob/v4.2.1/src/inet/common/INETDefs.h#L45
In case you use the latest revision from git, then of course, [OMNeT++ 5.6.2 is not recent enough](https://github.com/inet-framework/inet/commit/491a35dbe80ee522e1599d89f411a91ac5e026d3).

**Comment by levy** [comment]
Then I close this, because the description is incorrect.
