### ISSUE TITLE
ShortcutMac doesnt set a Mtu value for the interfaceEntry

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#577]
Probably belongs in the corresponding NED file and here:
https://github.com/inet-framework/inet/blob/7fe33a42501342e51a59dab12a9baeeb3e42e082/src/inet/linklayer/shortcut/ShortcutMac.cc#L58-L68

Although perhaps this should be implemented in MacProtocolBase, since it seems common to all mac protocols.

**Comment by ZoltanBojthe** [comment]
fixed in master
