### ISSUE TITLE
TCP window scaling is inaccurate

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#59]
Use of state->rcv_wnd_scale in updateRcvWnd

Info: rfc1323 Section 2.3 

The window field (SEG.WND) of every outgoing segment, with the exception of SYN segments, is right-shifted by Rcv.Wind.Scale bits:
       SEG.WND = RCV.WND >> Rcv.Wind.Scale.

Currently the scaling factor is used only if scaled_rcv_wnd > TCP_MAX_WIN. Because the scaled_rcv_wnd based on state->rcv_wnd this is not always true. This overwrites the exchanged factor of the handshake. Thus it is not calculated on every outgoing segment.

To reproduce:
Create a setup with

bool windowScalingSupport = true
a **.tcp.advertisedWindow > 65535 (e.g 70000)

a network setup that use the whole window (at least increase the reported arwnd < 65535).

**Comment by ZoltanBojthe** [comment]
fixed in 2015
