### ISSUE TITLE
AODVUU - Multiple send of the same packet without duplicating it.

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#60]
At aodv_timeout.cc:206
for (i = 0; i < MAX_NR_INTERFACES; i++)
{
   if (!DEV_NR(i).enabled)
       continue;
   aodv_socket_send((AODV_msg *) rerr, rerr_dest,
                    RERR_CALC_SIZE(rerr), 1, &DEV_NR(i));
}

An exception ("not owner of the object") is thrown when this piece of code is called and when there is more than one interface enabled because the same packet is send several times without being duplicated. See attached file for a proposed fix.

in inet 2.5.1

**Comment by rhornig** [comment]
https://gist.github.com/rhornig/7525526838a2499d87c5

**Comment by ZoltanBojthe** [comment]
In inet 3.3.0, the Manet rounting feature was removed from the source tree. The external MANET routing algorithms are available in the INETMANET fork (https://github.com/aarizaq/inetmanet-2.0)
