### ISSUE TITLE
AODVUU - Maximum number of interfaces is hardcoded, but not verification is made on the actual number, hence memory corruption.

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#61]
This bug is due to the fact that the maximum number of interfaces is hardcoded :

defs_aodv.h:94
# define MAX_NR_INTERFACES 10

And used so :
defs_aodv.h:123
    struct dev_info devs[MAX_NR_INTERFACES];

However no checks are performed to verify that this number is not exceeded by the actual numer of interfaces. This can lead to memory corruptions, eg in aodv_uu_omnet.cc:182-185 :

```
for (int i = 0; i <getNumInterfaces(); i++)
    {
        DEV_NR(i).ifindex = i;
        dev_indices[i] = i;
        ...
     }
```

If getNumInterfaces() is higher than MAX_NR_INTERFACES, you end up writing somewhere in memory and silently corrupting other data, leading to random hard-to-debug problems that only appears during execution (in the middle of a rather long one for me).

I attached a quick solution (a simple check is performed at initialisation, throwing an error if a problem is detected), although it would be way better to rewrite this with a malloc instead of this fixed size.

inet version 2.5.1 

https://gist.github.com/rhornig/b75e770626649bf273eb

**Comment by ZoltanBojthe** [comment]
In inet 3.3.0, the Manet rounting feature was removed from the source tree. The external MANET routing algorithms are available in the INETMANET fork (https://github.com/aarizaq/inetmanet-2.0)
