### ISSUE TITLE
Ieee80211Mac - potential segfault when using internal queueing module

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#63]
The Ieee80211Mac implementation (/inet/src/linklayer/ieee80211/mac/) uses the variable queueModule to store a pointer to an external queueing module. If the user chooses the internal module, then this variable is never initialized. All subsequent code in Ieee80211Mac.cc checks if queueModule is null to determine use of an internal or external queue.

To fix, simply add this [Ieee80211Mac.cc:526]:

```
if (par("queueModule").stringValue()[0])
{
   ...
} else {
   queueModule = 0;
}
```

Affects up through INET 2.4

Whether a segfault actually occurs depends on how the compiler treats uninitialized pointers, or sometimes just luck lol :-)

**Comment by levy** [comment]
This bug is obsolete.
