### ISSUE TITLE
syntx error, unexpected '=', expecting '.'

### ISSUE THREAD

**Issue by mateen-malik** [inet-framework/inet#633]
I cloned the inet from the following source to my computer

https://github.com/inet-framework/inet/

I import it to the OMNET++ IDE workspace

and i got same errors (i.e. syntx error, unexpected '=', expecting '.') in three files which are VlanlndFilter.ned, VlanReqFilter.ned and VlanReqMapper.ned 

Is this normal or did i do something the wrong way or how can i fix this?

Thanks in advance,

**Comment by avarga** [comment]
Which OMNeT++ version, which OS, which version of INET?

**Comment by mateen-malik** [comment]
> Which OMNeT++ version, which OS, which version of INET?
> 
> (The current "master" branch in the INET repo requires OMNeT++ 6.0pre10. However, unless you want to develop INET itself, you should use one of the released versions, e.g. 3.6.8 or 4.2.1.)

Got it,  I have now downloaded 4.2.1 and it s build successfully with 0 warnings and 0 errors. 
Thanks alot for the help.

Best wishes,
/MM
