### ISSUE TITLE
Intet Build Issue with Windows 10 and Omnet++

### ISSUE THREAD

**Issue by koushikbhargav** [inet-framework/inet#639]
Cannot export _ZThn8_NK4inet9IPv6Route23getDestinationAsGenericEv: symbol not defined
Cannot export _ZThn8_NK4inet9IPv6Route24getRoutingTableAsGenericEv: symbol not defined
Cannot export _ZThn8_NK4inet9IPv6Route9getMetricEv: symbol not defined
Cannot export _ZThn8_NK4inet9IPv6Route9getSourceEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee8021113RateSelection13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee8021116QoSRateSelection13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee8021123EdcaCollisionController13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee802113Mcf13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee802113Pcf13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee802114Hcca13numInitStagesEv: symbol not defined
Cannot export _ZThn96_N4inet4ospf13ASExternalLSAD0Ev: symbol not defined
Cannot export _ZThn96_N4inet4ospf13ASExternalLSAD1Ev: symbol not defined
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1361: ../out/clang-debug/src/libINET_dbg.dll] Error 1
make[1]: Leaving directory '/c/Users/Koushikbhargav/Documents/omnetpp-5.6.2-src-windows/omnetpp-5.6.2/samples/inet/src'
make: *** [Makefile:6: all] Error 2
"make MODE=debug -j4 all" terminated with exit code 2. Build might be incomplete.

**Comment by edlongman** [comment]
It may help to demangle the c++ names as follows: 
```
Cannot export non-virtual thunk to inet::IPv6Route::getDestinationAsGeneric() const: symbol not defined
Cannot export non-virtual thunk to inet::IPv6Route::getRoutingTableAsGeneric() const: symbol not defined
Cannot export non-virtual thunk to inet::IPv6Route::getMetric() const: symbol not defined
Cannot export non-virtual thunk to inet::IPv6Route::getSource() const: symbol not defined
Cannot export non-virtual thunk to inet::ieee80211::RateSelection::numInitStages() const: symbol not defined
Cannot export non-virtual thunk to inet::ieee80211::QoSRateSelection::numInitStages() const: symbol not defined
Cannot export non-virtual thunk to inet::ieee80211::EdcaCollisionController::numInitStages() const: symbol not defined
Cannot export non-virtual thunk to inet::ieee80211::Mcf::numInitStages() const: symbol not defined
Cannot export non-virtual thunk to inet::ieee80211::Pcf::numInitStages() const: symbol not defined
Cannot export non-virtual thunk to inet::ieee80211::Hcca::numInitStages() const: symbol not defined
Cannot export non-virtual thunk to inet::ospf::ASExternalLSA::~ASExternalLSA(): symbol not defined
Cannot export non-virtual thunk to inet::ospf::ASExternalLSA::~ASExternalLSA(): symbol not defined
```

Perhaps trying `make clean` or compilling with gcc would help

**Comment by rhornig** [comment]
This is a stale bug. INET should compile file in a clean build-tree. There is not enough detail here to reproduce the issue.
