### ISSUE TITLE
Inet build issue Windows 10 and Omnetpp

### ISSUE THREAD

**Issue by koushikbhargav** [inet-framework/inet#640]
Cannot export _ZThn8_NK4inet9IPv6Route23getDestinationAsGenericEv: symbol not defined
Cannot export _ZThn8_NK4inet9IPv6Route24getRoutingTableAsGenericEv: symbol not defined
Cannot export _ZThn8_NK4inet9IPv6Route9getMetricEv: symbol not defined
Cannot export _ZThn8_NK4inet9IPv6Route9getSourceEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee8021113RateSelection13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee8021116QoSRateSelection13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee8021123EdcaCollisionController13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee802113Mcf13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee802113Pcf13numInitStagesEv: symbol not defined
Cannot export _ZThn8_NK4inet9ieee802114Hcca13numInitStagesEv: symbol not defined
Cannot export _ZThn96_N4inet4ospf13ASExternalLSAD0Ev: symbol not defined
Cannot export _ZThn96_N4inet4ospf13ASExternalLSAD1Ev: symbol not defined
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:1361: ../out/clang-debug/src/libINET_dbg.dll] Error 1
make[1]: Leaving directory '/c/Users/Koushikbhargav/Documents/omnetpp-5.6.2-src-windows/omnetpp-5.6.2/samples/inet/src'
make: *** [Makefile:6: all] Error 2
"make MODE=debug -j4 all" terminated with exit code 2. Build might be incomplete.

**Comment by rhornig** [comment]
not enough info to reproduce
