### ISSUE TITLE
Compilation fails on Mac OS - 10.15.7 INET4.2.1 

### ISSUE THREAD

**Issue by lakshmikrish-97** [inet-framework/inet#641]
Hi I am using a Mac OS Catalina 10.15.7 
Trying to build INET4.2.1 
I was able to build OMNeT++ 5.6.2 successfully using 
 ./configure WITH_TKENV=no WITH_QTENV=yes WITH_OSG=no
            
Do we need to enable OSG for INET to build successfully?

This is what I get when I do make for inet:

In file included from ./inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.h:21:
In file included from ./inet/environment/common/PhysicalEnvironment.h:23:
./inet/common/geometry/common/GeographicCoordinateSystem.h:84:5: error: no type named 'Matrixd' in namespace 'inet::osg'; did you mean '::osg::Matrixd'?
    osg::Matrixd locatorMatrix;
    ^~~~~~~~~~~~
    ::osg::Matrixd
/Users/lakshmikrish/omnetpp-5.6.2/tools/macosx/include/osg/Matrixd:26:18: note: '::osg::Matrixd' declared here
class OSG_EXPORT Matrixd
                 ^
In file included from inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.cc:25:
In file included from ./inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.h:21:
In file included from ./inet/environment/common/PhysicalEnvironment.h:23:
./inet/common/geometry/common/GeographicCoordinateSystem.h:85:5: error: no type named 'Matrixd' in namespace 'inet::osg'; did you mean '::osg::Matrixd'?
    osg::Matrixd inverseLocatorMatrix;
    ^~~~~~~~~~~~
    ::osg::Matrixd
/Users/lakshmikrish/omnetpp-5.6.2/tools/macosx/include/osg/Matrixd:26:18: note: '::osg::Matrixd' declared here
class OSG_EXPORT Matrixd
                 ^
2 errors generated.
make[1]: *** [../out/clang-release/src/inet/visualizer/environment/PhysicalEnvironmentOsgVisualizer.o] Error 1
make: *** [all] Error 2

**Comment by edlongman** [comment]
You need to make sure that INET is not built using the "WITH_OSG" and "WITH_OSG" flag.

Check your Eclipse Build Paths and Symbols or whatever make command you are using,
If these flags do not exist then this code will not be compilled and you will not get the error.

**Comment by lakshmikrish-97** [comment]
yeah thank you so much!! Yeah set them to "no" in OMNeT++ config.user file and that fixed it 
(initially I used using ./configure WITH_OSG=no and WITH_OSGEARTH=no )
