### ISSUE TITLE
BitErrorRate filter sending very small value to cHistogram result recorder causing crash

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#648]
The error thrown by the cHistogram is recorded here: https://github.com/omnetpp/omnetpp/issues/863

However, a workaround is to limit the minimum value of the result filter in [ResultFilters.cc](https://github.com/inet-framework/inet/blob/a216682295d90a0f95629fdbaf66aa389e04ce1e/src/inet/common/ResultFilters.cc#L334) with the following:
```cpp
void BitErrorRateFromErrorRateIndFilter::receiveSignal(cResultFilter *prev, simtime_t_cref t, cObject *object, cObject *details)
{
    if (auto pk = dynamic_cast<Packet *>(object)) {
        auto tag = pk->findTag<ErrorRateInd>();
        if (tag){
            const double ber = tag->getBitErrorRate();
            fire(this, t, (ber<2e-320)?0.0:ber, details);  //TODO isNaN?
        }
    }
}
```

The value was being generated by a Ieee802154Radio with modulation QPSK, calling `BpskModulation::calculateSER(snir = 2.6374, bandwidth = 2.8e6, bitrate=10e3) = 2e-323`

**Comment by levy** [comment]
I think this should be fixed in omnet, otherwise we end up with this condition all over the place. I leave this open until it gets fixed there.

**Comment by edlongman** [comment]
I agree, this is very much a workaround of the actual bug, which is only triggered in very speific circumstances!

**Comment by levy** [comment]
The related omnet bug has been closed, so I close this issue now.
