### ISSUE TITLE
the lastest modification in the clock code breaks the build

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#649]
If the clock feature is not active the build fails due to src/inet/applications/common/SimpleClockSynchronizer.h does an "include" of "inet/clock/model/SettableClock.h" and this header needs the definition of OverdueClockEventHandlingMode that is defined in the file "inet/clock/common/ClockEvent.msg" but this file has been excluded from the build

A possible solution
https://github.com/aarizaq/inetmanet-4.x/commit/ec772bcb5c9b1650f80239a20323a3f0590b0f65

**Comment by levy** [comment]
Thanks for reporting this issue!
