### ISSUE TITLE
IPv4NetworkConfigurator check for transmission channel

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#65]
In the function extractWiredNeighbors the line

> cChannel *transmissionChannel = linkOut->getLocalGate()->getTransmissionChannel()

should actually be

> cChannel *transmissionChannel = linkOut->getLocalGate()->findTransmissionChannel()

The former throws an error, but the later returns NULL which should be the correct behavior as it isn't required to have a channel between two modules.

**Comment by levy** [comment]
This is fixed in master.
