### ISSUE TITLE
Linker errors INET 4.2.2 + OMNeT 5.6.2 when building project on Windows

### ISSUE THREAD

**Issue by Kuoreal** [inet-framework/inet#652]
My project with RPL routing protocol implementation references INET and compiles well on latest Ubuntu, but not on Windows 10 due to multiple linking errors, like this one (gcc and clang variants):

`make MODE=release all 
cd src && /usr/bin/make
make[1]: Entering directory '/c/Users/kuore/omnetpp-5.6.2/samples/dummyproj/src'
Rpl.cc
Creating executable: ../out/gcc-release/src/dummyproj.exe
../out/gcc-release/src/Rpl.o:Rpl.cc:(.rdata$_ZTVN4inet19RoutingProtocolBaseE[_ZTVN4inet19RoutingProtocolBaseE]+0x660): undefined reference to non-virtual thunk to inet::OperationalBase::handleOperationStage(inet::LifecycleOperation*, inet::IDoneCallback*)'
../out/gcc-release/src/Rpl.o:Rpl.cc:(.rdata$_ZTVN4inet3RplE[_ZTVN4inet3RplE]+0x660): undefined reference to non-virtual thunk to inet::OperationalBase::handleOperationStage(inet::LifecycleOperation*, inet::IDoneCallback*)'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:104: ../out/gcc-release/src/dummyproj.exe] Error 1
make[1]: Leaving directory '/c/Users/kuore/omnetpp-5.6.2/samples/dummyproj/src'
make: *** [Makefile:2: all] Error 2
"make MODE=release all" terminated with exit code 2. Build might be incomplete.`

`make MODE=release all 
cd src && /usr/bin/make
make[1]: Entering directory '/c/Users/kuore/omnetpp-5.6.2/samples/dummyproj/src'
Rpl.cc
Creating executable: ../out/clang-release/src/dummyproj.exe
../out/clang-release/src/Rpl.o:(.rdata+0x758): undefined reference to non-virtual thunk to inet::OperationalBase::handleOperationStage(inet::LifecycleOperation*, inet::IDoneCallback*)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:104: ../out/clang-release/src/dummyproj.exe] Error 1
make[1]: Leaving directory '/c/Users/kuore/omnetpp-5.6.2/samples/dummyproj/src'
make: *** [Makefile:2: all] Error 2
"make MODE=release all" terminated with exit code 2. Build might be incomplete.`

To reproduce the issue in it's simplest form (above errors), please create a new project with the attached source files and compile.
[rpl.zip](https://github.com/inet-framework/inet/files/5967400/rpl.zip)

Screenshot for better readabiltiy
<img width="1289" alt="Screenshot 2021-02-11 173420" src="https://user-images.githubusercontent.com/31932610/107677897-04220080-6c9b-11eb-9a55-2132114dce03.png">

**Comment by edlongman** [comment]
Did you manage to overcome this error in the end?

**Comment by Kuoreal** [comment]
No, I didn’t attempt anything more than clean reinstall starting from
omnet, due to low priority of this issue atm - need to expand
implementation for another research, rather than wrestle with running
everything on other platform.

**Comment by Kuoreal** [comment]
Just tried it again after quite some time and one (unrelated) Windows reinstallation and now it compiles, interesting.
