### ISSUE TITLE
./inet/networklayer/ipv4/Ipv4RoutingTable.h:259:50: error: unknown type name 'Ipv4Header'

### ISSUE THREAD

**Issue by lakshmikrish-97** [inet-framework/inet#653]
I am trying to use the Ipv4Header file and functionalities but I keep getting this error, this is on INET4.2.1 

Not sure why, this was named as IPv4Datagram in earlier versions - INET3.6, so has it probably been changed again? But I am not sure from the changlog

any help or direction would be greatly appreciated!!

Edit : I noticed, under inet/networklayer/ipv4 : we have Ipv4Header.msg and Ipv4Header.cc but no Ipv4Header.h 
Any help/ guidance on how we need to modify Ipv4Header.msg to generate this?

**Comment by edlongman** [comment]
You need to include `inet/networklayer/ipv4/Ipv4Header_m.h`

the `Ipv4Header.cc` is just the implementation of some custom header functions defined in `Ipv4Header.msg` which is transformed into `Ipv4Header_m.h` (and `Ipv4Header_m.cc`

I hope that helps.

**Comment by lakshmikrish-97** [comment]
Ohh, thank you so much! This fixed that issue now, thanks so much once again
