### ISSUE TITLE
Should Hooks use the Enter_Method/Enter_Method_Silent Macros?

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#654]
I don't fully understand the ownership of objects in OMNeT++ but reading this [Section 4.14](https://doc.omnetpp.org/omnetpp/manual/#sec:simple-modules:direct-method-calls) in the manual it says: 

>  First, the simulation kernel always has to know which module's code is currently executing,  ....
>  The solution is to add the Enter_Method() or Enter_Method_Silent() macro at the top of the methods that may be invoked from other modules.

Regarding things like https://github.com/inet-framework/inet/blob/be4e4cd2953f564cdfca8cbbaaeb476b8df795aa/src/inet/networklayer/common/NetfilterInfoHook.cc#L82-L107

Should they use the Enter_Method macro? I ask because I am implementing my own module with Hook and am not sure if they should be used. But referring to the INET library as a guide I was expecting to see them here, but didn't

**Comment by levy** [comment]
They should. I guess these classes have been converted to modules from simple C++ classes at some point and whoever did that forgot to add the Enter_Method calls. Adding them also allows one to see what calls are being made between modules in the Sequence Chart. The upcoming version will have a much more detailed view in that regard.
