### ISSUE TITLE
Error- getInterfaceById(): no interface with ID=-1 -- in module (inet::Ipv4)

### ISSUE THREAD

**Issue by SamhithReddy** [inet-framework/inet#656]
Hello everyone,

I am working on OMNET5.6.2, INET 4.2.2, and SIMULTE 1.2.0. When I run my simulation for the first 500s its working fine, but after that, I am getting the following error

" getInterfaceById(): no interface with ID=-1 -- in module (inet::Ipv4) error "

Why does this error occur all of a sudden? I have not used this function at all in my file.  Along with the above error I am getting this error " ICMP-error #1 Type3 - code 4 in my console. Can anyone please help me resolve this issue? Any help would be highly appreciated.

**Comment by wischhof** [comment]
Could you give some more details so that one can reproduce the problem? What simulation are you running? Which omnetpp.ini file is used?
