### ISSUE TITLE
error in IPvXAddressResolver::findHostWithAddress(const IPvXAddress & add)

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#66]
There is a problem in the method

> IPvXAddressResolver::findHostWithAddress(const IPvXAddress & add)

if a node doesn't have a IP address, the program abort
Solution:

https://github.com/aarizaq/inetmanet-2.0/commit/049709063f584787c6ed2475737ea081ec99cfe7

**Comment by levy** [comment]
This is fixed in master.
