### ISSUE TITLE
Linker command failed with exit code 1 error in OMNeT++5

### ISSUE THREAD

**Issue by Afsana-Rima** [inet-framework/inet#666]
![Capture](https://user-images.githubusercontent.com/55757169/111747556-d44fb500-8865-11eb-8b88-6a179aa2a9bc.JPG)

Please help me on this issue.

-Afsana

**Comment by edlongman** [comment]
Could you please provide more details about how you are compiling this. 

Are you compiling a custom project or an example from omnet? 

Is the project referencing the inet project in the settings?

What is the command that is being used to link the executable during compillation?
