### ISSUE TITLE
RandomDriftOscillator problems

### ISSUE THREAD

**Issue by ledvinap** [inet-framework/inet#667]
There are several problems in RandomDriftOscillator: https://github.com/inet-framework/inet/blob/950e45851e881cb78b8b855b4617e76bd08be291/src/inet/clock/oscillator/RandomDriftOscillator.cc#L46-L48

- `driftRateParameter->doubleValue()` is in ppm, but it is not divided here (actual drift is 1e6 times larges)
- `driftRate` is member of base class, setting it here may cause problems (setDriftRate compares old and new value). Using local variable will fix this

**Comment by ledvinap** [comment]
Also `par("changeInterval")` is good candidate for cached reference.

**Comment by levy** [comment]
Thanks for reporting, fixed in master.
