### ISSUE TITLE
Power_1.test: FAIL (test program returned exit code 139)

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#668]
Analyzing the power test error, in some modules, the stage variables aren't initialized correctly.

import inet.power.storage.SimpleEpEnergyStorage;
import inet.power.consumer.AlternatingEpEnergyConsumer;
import inet.power.generator.AlternatingEpEnergyGenerator;

network Test
{
    submodules:
        energyStorage: SimpleEpEnergyStorage;
        energyConsumer: AlternatingEpEnergyConsumer;
        energyGenerator: AlternatingEpEnergyGenerator;
}

The first time that the code enters in initialize, the value of INITSTAGE_LOCAL is -1, and it skypes the initialization of the message timer

void SimpleEpEnergyStorage::initialize(int stage)
{
    EpEnergyStorageBase::initialize(stage);
    if (stage == INITSTAGE_LOCAL) {

**Comment by levy** [comment]
Thanks for reporting! This bug should be fixed in the master branch.

**Comment by levy** [comment]
This test passes in the master branch.
