### ISSUE TITLE
tcpType setting in omnetpp.ini missing for certain examples

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#67]
As discussed in this OMNeT mailing list thread (https://groups.google.com/d/msg/inetframework-devel/dDUf6RJNMtY/aaSegx5728sJ [^]):

Certain INET examples miss the definition of the tcpType variable in their respective omnetpp.ini files. 

Without the following line, the NED indexer misses the connection and reports warnings for the tcp parameters:

**.tcpType = "TCP"

This line needs to be inserted in the following INET example's (i.e. in their omnetpp.ini files):
- tcpwindowscale
- tcptimestamps
- tcpsack
- ber

**Comment by ZoltanBojthe** [comment]
as a workaround add (this is the new syntax):
`**.tcp.typename = "Tcp"

added for all examples where using any Tcp implementation-specific parameter
