### ISSUE TITLE
Understanding results of inet configurator example - unroutable, sending ICMP_DESTINATION_UNREACHABLE, dropping packet

### ISSUE THREAD

**Issue by lakshmikrish-97** [inet-framework/inet#677]
Hi,

I am trying to run the examples to understand network setup and in particular how the network configurator works.
On running the inet4/examples/inet/configurator/SimpleConfigurator example, there are multiple instances of "unroutable, sending ICMP_DESTINATION_UNREACHABLE, dropping packet" and also all the pings seem to have a loss rate of 75%. 
Not sure why this is happening and how to interpret these results.

This is on INET4.2.1 running on OMNeT++5.6.2

Any help would be greatly appreciated and also please do let me know if I should be posting this some place else. 

<img width="948" alt="Screen Shot 2021-04-12 at 3 30 57 PM" src="https://user-images.githubusercontent.com/60198977/114470702-2e614300-9ba4-11eb-844c-4b268c3cdcc8.png">
<img width="1202" alt="Screen Shot 2021-04-12 at 3 31 32 PM" src="https://user-images.githubusercontent.com/60198977/114470717-34572400-9ba4-11eb-80b2-a465abc3f128.png">

**Comment by ZoltanBojthe** [comment]
All hosts has one PingApp.
All hosts has 2 interfaces, so 8 IPv4 Addresses exists in network.
All PingApp send one-one pings to all existing IPv4 Address in the network.

In the DisableLink config:
links to/from host21 interfaces have infinite costs, configurator doesn't generate any routing entry for these links.
The host21 has an empty routing table, so the pings responsed only from host21 addresses: send:8, recv:2.
Other hosts receives answers from all hosts except from host21, so send:8, recv:6.

For more info see interfaceTable and ipv4.routingTable modules in all hosts.

**Comment by lakshmikrish-97** [comment]
Thank you so much for your very quick and timely feedback sir, this definitely helps a lot! 
Just few doubts, sorry again for the inconvenience, 
I tried re-running them using the DisableLink config settings, and still do not see send:8 and recv:6 for all other hosts.
Am I supposed to be changing some settings sir, currently they are at the default settings as provided.

Also sorry again but where can I find the individual interfaceTable and ipv4.routingTablle modules for each of the hosts - should I be using some visualization package? 

Thank you so much for your time and help sir!

<img width="908" alt="Screen Shot 2021-04-13 at 12 22 10 PM" src="https://user-images.githubusercontent.com/60198977/114609016-2d3b1f00-9c53-11eb-8a0e-3df787728613.png">
