### ISSUE TITLE
<!> findHostWithAddress() doesn't accept AddressType 'MODULEPATH', yet -

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#681]
Looks pretty trivial to implement, I'll submit a pull request in the next few days

**Comment by edlongman** [comment]
On closer inspection around the `NetworkInterface`, `InterfaceTable` and `L3AddressResolver` there seems to be quite a lot of code duplication in the following:

<table colwidth="200px">
<tr>
<td width="200px">

https://github.com/inet-framework/inet/blob/9a3825df796193b9ab5c8645a51d2be89ff7756d/src/inet/networklayer/common/InterfaceTable.cc#L121-L173

</td>
<td>

https://github.com/inet-framework/inet/blob/9a3825df796193b9ab5c8645a51d2be89ff7756d/src/inet/networklayer/common/NetworkInterface.cc#L362-L400

</td>
</tr>
</table>

And also:
- `InterfaceTable::findInterfaceByAddress(L3Address )` and `NetworkInterface::hasNetworkAddress(L3Address )` where only the Ipv6 has a special case when converting from and Ipv4 address first, all other address conversion (which is explicit doesn't need to be, as handled by `operator==`) is delegated to `hasNetworkAddress(L3Address )`
- `L3AddressResolver::getInterfaceIpv4Address(...)` and `NetworkInterface::getIpv4Address()`/`NetworkInterface::getIpv4Netmask()`
- `L3AddressResolver::findInterfaceWithMacAddress(...)` could correctly and efficiently reuse `L3AddressResolver::findInterfaceWithAddress(...)`

This is obviously quite involved but I could definitely make this simpler and more consistent because currently there are many subtle inconsistencies, like if `NextHopInterfaceData` is used to get the `ModuleIdAddress` or whether `NetworkInterface::getModuleIdAddress()` is used. Proxying it all to a small number of functions would make this more maintainable.

Also, since the renaming of `InterfaceEntry` to `NetworkInterface` there are now a lot of missnamed variables `ie` and `ie*` that I think should be `ni` and `ni*`.

If doing the refactoring, should `NetworkInterface::hasNetworkAddress(...)` take on the `cRuntimeError("Unknown address type");` from `InterfaceTable::findInterfaceByAddress(...)`

**Comment by levy** [comment]
I'm a big fan of the elimination of duplicate code and making it more consistent.

Please try to create a pull request with smaller patches and one that can be rebased on the master branch without merging other branches.

Thank you for your contributions!

**Comment by edlongman** [comment]
What are your thoughts about whether `find...` should match ModuleId and ModuleName if NextHop data has not been attached to the interface?

**Comment by levy** [comment]
I'm not sure I understand your question. Could you please rephrase it?

**Comment by edlongman** [comment]
There is an inconsistency between how `InterfaceTable::findInterfaceByAddress(L3Address )` and `NetworkInterface::hasNetworkAddress(L3Address )` work. 

<table colwidth="200px">
<tr>
<td>

`InterfaceTable::findInterfaceByAddress(L3Address )`

* if type is MODULEID or MODULEPATH
* compare based on componentId (via proxy of `ModuleIdAddress` or `ModulePathAddress`
* return from loop if match
</td>
<td>

`NetworkInterface::hasNetworkAddress(L3Address )`

* if type is MODULEID or MODULEPATH
* **and if `findProtocolData<NextHopInterfaceData>()`**
* compare based **on `NextHopInterfaceData::getAddress()`**
* return true if match
</td>
</tr>
<tr>
<td>

```cpp
{
    InterfaceEntry *entry = itable->getInterface(i);
    switch (add.getType()) {
        ...
    case L3Address::MODULEPATH: {
         if(entry->getModulePathAddress() == add.toModulePath()){
              return mod;
         }
         break;
    }
    case L3Address::MODULEID: {
        if(entry->getModuleIdAddress() == add.toModuleId()){
            return mod;
        }
        break;
        }
        default:
        ...
        break;
     }
}
```
</td>
<td>

```cpp
{
    switch(address.getType()) {
    ...
    case L3Address::MODULEID:
    case L3Address::MODULEPATH: {
#ifdef WITH_NEXTHOP
        auto nextHopData = findProtocolData<NextHopInterfaceData>();
        return nextHopData != nullptr && nextHopData->getAddress() == address;
#else
        return false;
#endif // ifdef WITH_NEXTHOP
    }
    default:
        break;
    }
    return false;
}
```
</td>
</tr>
</table>

Both validate the same thing, and `findHostWithAddress()` then returns the host if it matches, but they would disagree depending on if you've used `NextHopInterfaceData`.

The same problem exists in `L3AddressResolver::findHostWithAddress`

**Comment by levy** [comment]
Which version of INET are you looking at? The latest master branch doesn't look like the one you have posted on the left (InterfaceTable::findInterfaceByAddress) to me. I'm not saying that INET master is good as it is, but first we should make sure that we are talking about the same version.

In general, I think it would be better if a network interface would have to be explicitly assigned a non-standard L3 address by attaching for example a NextHopInterfaceData to it. Otherwise there might be accidentally successful name resolutions to module ID or module path based addresses. I guess the findInterfaceByAddress could simply loop through the interfaces and return the first one which has the requested L3 address.

What do you think?

**Comment by edlongman** [comment]
Sorry, I'd muddled up `L3AddressResolver::findHostWithAddress` and `InterfaceTable::findInterfaceByAddress`. I've edited the above and it's all based on master branch.

I think that the NextHopInterfaceData is a must for matching `InterfaceTable::findInterfaceByAddress` and `InterfaceEntry::hasNetworkAddress`. 

It's a bit less clear whether a host has to have the address assigned to an interface to match for `L3addressResolver`, but given the scenario of a host with no interfaces, it would not match, so equally if no interfaces have `NextHopInterfaceData` it should also not match.

**Comment by edlongman** [comment]
Are there any tests for the behaviour of these functions?

And is there any examples you expect might break if I modify them?

**Comment by levy** [comment]
I agree with the above.

Some fingerprint tests use these address types. For example, hierarcical99 contains some configurations. You can search for others by looking for hasGn = true in the INI files.

**Comment by ZoltanBojthe** [comment]
fixed in inet4.4
