### ISSUE TITLE
Build errors and warnings INET 4.3.2 in Omnet++ 6.0 preview 11

### ISSUE THREAD

**Issue by lingcy0328** [inet-framework/inet#686]
A bunch of warnings appeared when i import INET into Omnet++. Also, a few errors appeared when I ignore the warnings and try to simulate the examples. Attachment below is the screenshot of the warnings after imported INET and errors of the example simulation. Any opinion on how to solve this? 
![Screenshot 2021-04-29 110324](https://user-images.githubusercontent.com/83384074/116497687-8ef9bb00-a8da-11eb-84e4-4b52df3ef958.png)
![Screenshot 2021-04-29 110536](https://user-images.githubusercontent.com/83384074/116497832-daac6480-a8da-11eb-9698-5ea7068f12f1.png)

**Comment by rhornig** [comment]
INI warnings are unrelated to the main problem that the executable crashed. It must be debugged because there is not enough information to reproduce this.
