### ISSUE TITLE
`./featuretest` fails to run on windows because of leading `/` in pwd output

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#687]
Error when running feature tests on OMNET 6 preview and inet master branch.

`./featuretest: line 37: //c/PATH_TO_INET_DIR/tests/features/_log/all_disabled-build.out`

Because of line: https://github.com/inet-framework/inet/blob/8515a0cac14581821f1d4ecf9116c6e136fb6f91/tests/features/featuretest#L37

Where `$LOG_DIR = pwd = /c/PATH_TO_INET_DIR/tests/features/` so `/$LOG_DIR/$1-build.out` evaulates with two leading `/` which cannot resolve, possibly because windows treats it as a network destination

`

**Comment by rhornig** [comment]
Fixed by 9e4acbd26ced2870a99287c16bff14e39be93a29
