### ISSUE TITLE
`RECEPTION_STATE_IDLE` channel busy measurement breaks when `noise > energyDetection`

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#697]
Using `IRadio::RECEPTION_STATE_IDLE` for channel busy doesn't work with high levels of noise (or low sensitivity thresholds), that is, the receptionState always remains as `RECEPTION_STATE_BUSY` because `isListeningPossible` always evaluates as true. 
https://github.com/inet-framework/inet/blob/4843226469be84c75917876c0a0e5697020f98a2/src/inet/physicallayer/wireless/common/radio/packetlevel/Radio.cc#L557-L566
Which get's the decision from
https://github.com/inet-framework/inet/blob/007bc454ec7749e2dea8fcb808429d21074880ad/src/inet/physicallayer/wireless/common/base/packetlevel/FlatReceiverBase.cc#L60-L68

Since maxPower is at minimum the value of background noise level from whaetever noise model is being used it is always true if the sensitivity is lower than the noise level.

Implemented this way for: 
* `Ieee80211Mac` & `Ieee80211LayeredOfdmReceiver`
* `CsmaCaMac` & `FlatReceiverBase`
* `Ieee802154Mac` & `FlatReceiverBase`

I think this is somewhat legitimate behaviour, but it is also extremally hard to track down, and there is no kind of safety check of valid settings anywhere.  The consequences of getting it wrong would mean your received packet rate would be 0 as soon as you reach the threshold.

I have chosen to put a safety check in the Mac layer initialize. What do you think about incorporating this more generally, probably into `Radio::initialize()`?
```cpp

        /*
         * Warning of noise in radio medium exceeding energy detection threshold
         */
        auto medium = getModuleFromPar<physicallayer::IRadioMedium>(radioModule->par("radioMediumModule"), radioModule);
        auto noiseModel = medium->getBackgroundNoise();
        auto scalarNoiseModel = check_and_cast<const physicallayer::IsotropicScalarBackgroundNoise*>(noiseModel);
        auto dataReceiverModel = check_and_cast<const physicallayer::FlatReceiverBase*>(dataRadio->getReceiver());
        if(scalarNoiseModel && dataReceiverModel)
            if(scalarNoiseModel->getPower() > dataReceiverModel->getEnergyDetection())
                cRuntimeError("Background noise power is greater than data radio energy detection threshold. Radio will always be \"Busy\"");
```
I think it would also need a new interface `IBackgroundNoise::getPower(bandwidth)` mirroring `IsotropicScalarBackgroundNoise::getPower()`

---
Also, `ApskLayeredReceiver` is also quite correlated with `Ieee80211LayeredOfdmReceiver` possibly room for making a common base for these. Would that be sensible?

**Comment by levy** [comment]
Hmm, I see your point. There should be some kind of check for this case in order to prevent endless debugging sessions.

I think it should probably be a check in the Radio, it should check that reception state of the receiver can be IDLE at all.
Factoring out the common parts of the layered (or modular) receivers is generally a good idea.

**Comment by levy** [comment]
How about 3aaf38a4510ea23950a07c36bf8f556b7face935?

**Comment by edlongman** [comment]
Yes, that would be suitable.
I think some more explanation of the "energy detection" and "sensitivity"
parameters would be helpful as well.
I think "carrier detection threshold" may make more sense than "energy
detection" especially as it is actually power, not energy.

Coming from a Wireless background it all makes sense to me but might be
hard for other newcomers.

**Comment by levy** [comment]
I agree, some parameter/class/function names are less than ideal, and I'm open for renaming them. Especially because I'm not a wireless expert even if I learned a lot of things over the years. I had to figure out most of these names by selecting the most appropriate ones I could find in the literature. But I guess renaming should be done in another issue/PR.
