### ISSUE TITLE
void InterfaceTable::deleteInterface(NetworkInterface *entry) doesn't work

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#703]
NetworkInterface is derived from the class cSimpleModule and cannot be deleted by delete entry, it must be replaced by entry->deleteModule()

void InterfaceTable::deleteInterface(NetworkInterface *entry)
{
    int id = entry->getInterfaceId();
    if (entry != getInterfaceById(id))
        throw cRuntimeError("deleteInterface(): interface '%s' not found in interface table", entry->getInterfaceName());

    emit(interfaceDeletedSignal, entry); // actually, only going to be deleted

    idToInterface[id - INTERFACEIDS_START] = nullptr;
    delete entry;
    invalidateTmpInterfaceList();
}

**Comment by ZoltanBojthe** [comment]
fixed
