### ISSUE TITLE
Cannot build inet 4.3.1, documentation out-of-date

### ISSUE THREAD

**Issue by smblackledge** [inet-framework/inet#708]
I built Omnetpp-6.0pre11 successfully.  Once X-forwarding was enabled, I started omnetpp.  The usual splash screen appeared, and then the IDE.  The new format "Welcome" screen is not documented and there is no "Workbench" icon to click on.  I got rid of the welcome screen, thinking that it would be simple to get to the location where I was asked if I wanted inet to be automatically loaded.  (Keep in mind that there is a huge several-second response lag.)  I got the desired screen once and only once, and I can't even tell how I got that because of the lag.  I must learn patience, I know, I know.  But, I clicked around, viewing all and selecting anything that looked like a possibility, but all was for naught.  I did quit and restart the IDE, thinking that I'd see the same screens again, but once cancelled, the welcome screen stays cancelled.  Yep, I could uninstall and reinstall, but I wanted to try this avenue before that final act of desperation. 

I'd like to know exactly how to get https://inet.omnetpp.org/Installation.html updated so that I can auto-load inet.  Failing that, I'm asking for a description of exactly how to get that welcome screen back, which I couldn't do without re-installing omnet++, and exactly how to get to the auto-load request pop-up.  Implied here is a request for any other information that you experienced types believe that I need or at least would find useful.

**Comment by rhornig** [comment]
Install simulation models from the Help menu should also give you an automatic INET download / install option.
