### ISSUE TITLE
InterfaceVisualizer displaying additional interface

### ISSUE THREAD

**Issue by adamgeorge309** [inet-framework/inet#710]
In addition to the interfaces it is supposed to display

![Screenshot from 2021-07-23 14-32-43](https://user-images.githubusercontent.com/17473608/126782143-2e4a4c3b-9212-446b-ae7e-eb539c623afe.png)

**Comment by dragos-bth** [comment]
I am seeing the same behavior on inet-4.3.4 for wlan0 interfacea. For each host (derived from AdHocHost) there are two wlan0 interfaces: one initialized with correct MAC address,  IP address and netmask and another wlan0 with MAC address all-zeroes and no IP address or netmask.

``*.wlan[*].typename = "AckingWirelessInterface"``

with Ipv4NetworkConfigurator and GlobalArp

Network configuration

```
<?xml version="1.0"?>

<config>
   <interface hosts='**' address='10.0.0.x' netmask='255.255.255.0'/>
   <blah>
   <route hosts='**' destination='10.0.1.0' netmask='255.255.255.0' gateway='10.0.0.100'/>
   </blah>
</config>
```
