### ISSUE TITLE
OmittedIeee8021dQosClassifier doesn't exist

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#712]
The Ieee80211Interface uses OmittedIeee8021dQosClassifier but this module is not present

**Comment by aarizaq** [comment]
I have included a basic implementation that allows to run the examples
https://github.com/aarizaq/inetmanet-4.x/commit/99578d7d148bf5694c90b23fe22a13142ee3f5c3

**Comment by ZoltanBojthe** [comment]
OmittedIeee8021dQosClassifier,ned added to inet at 2021-09-09: 13e98dc081d56ab2118e8d42884ce9dca6f5327e
