### ISSUE TITLE
Enabling TCP Window Scaling 

### ISSUE THREAD

**Issue by lakshmikrish-97** [inet-framework/inet#715]
INET version : 4.3.2
OMNeT version : omnetpp-6.0pre11

Currently the advertised window size is set to 65535. I am trying to enable window scaling, and so set the window scaling parameter to be true and also the scale factor to be 4. The TcpSessionApp and TcpSinkApp are used as sending and receiving applications. 

I added print statements from TcpConnectionUtil and noticed that in the SYN segment, ws-scale is set to 0 whereas in SYN-ACK segment the ws-scale is set to 1, due to which window-scaling isn't working. I am not sure how to set the ws-scale option from the sender side too. 

Please do let me know your thoughts and or suggestion and anything I might be doing wrong. 
Please do let me know if you need any other information at all, and any help, guidance or pointers would really be super helpful.

**Comment by ZoltanBojthe** [comment]
I checked the examples/inet/tcpwindowscale/ with config WS_enabled on inet master.
It looks like works correctly.

For demonstrate your problems, please attach a simple example with ini+ned files.

**Comment by ZoltanBojthe** [comment]
Tested with OMNeT++ 6.0 and INET4.3.9: the inet/examples/inet/tcpwindowscale example works correctly with the `WS_enabled` config and with this config, too:
```
[Config WS_enabled2]
**.tcp.windowScalingSupport = true
**.tcp.windowScalingFactor = 4
**.tcp.advertisedWindow = 65535
```
