### ISSUE TITLE
Region tags not placed or displayed properly with multiple packet flows

### ISSUE THREAD

**Issue by adamgeorge309** [inet-framework/inet#716]
![flowtag](https://user-images.githubusercontent.com/17473608/130596461-8638d320-e4c8-41e0-813c-9fd70b85ac55.png)

The first flowtag is added at the sender application, so it contains only the data payload (0-500B). The second flowtag is added when the packet is already encapsulated by IP, UDP and Ethernet (42B headers total). This second tag is added at the end of the packet (500-542B region) instead of the beginning.

Reproduce with examples/timing or showcases/general/flowmeasurement.

**Comment by levy** [comment]
This is fixed in master now and a new test case was also added.
