### ISSUE TITLE
Errors shown by IDE when INET features disabled

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#720]
## Steps to reproduce
- Disable EIRGP and BGP (and OSPFv2) 
- Open /inet/src/inet/node/inet/Router.ned

## Eclipse Errors shown
- 'ospfRoutingModule': no such parameter
- 'enableIpv6': no such parameter
- 'enableIpv4': no such parameter

Not sure if anything can actually fix this without changing the omnet ned interpreter.

**Comment by rhornig** [comment]
This is indeed an IDE issue, that should be fixed in OMNeT++. Created a probably related issue and referencing this one.
https://github.com/omnetpp/omnetpp/issues/923
