### ISSUE TITLE
Opp6-pre12: Clang LLD Cannot link inet derivatives using Mixin classes ClockUserModuleBase and OperationalBase

### ISSUE THREAD

**Issue by edlongman** [inet-framework/inet#723]
This is related to https://github.com/omnetpp/omnetpp/issues/862 and maybe https://github.com/msys2/MINGW-packages/issues/6855

- Windows 10
- OMNeT++ 6-pre12

## MWE
```cpp
#include <omnetpp.h>
#include <inet/common/clock/ClockUserModuleBase.h>

class FooModule : public inet::ClockUserModuleBase{
};
Define_Module(FooModule);
```

## Errors with
```
test.cc
Creating executable: out/clang-debug//test_dbg.exe
lld-link: error: duplicate symbol: inet::ClockUserModuleMixin<omnetpp::cSimpleModule>::ClockUserModuleMixin()
>>> defined at ../inet/src\inet/common/clock\ClockUserModuleMixin.h:30
>>>            out/clang-debug//test.o
>>> defined at libINET_dbg.dll

lld-link: error: duplicate symbol: inet::ClockUserModuleMixin<omnetpp::cSimpleModule>::exponential(inet::ClockTime, int) const
>>> defined at ../inet/src\inet/common/clock\ClockUserModuleMixin.h:67
>>>            out/clang-debug//test.o
>>> defined at libINET_dbg.dll

lld-link: error: duplicate symbol: inet::ClockUserModuleMixin<omnetpp::cSimpleModule>::truncnormal(inet::ClockTime, inet::ClockTime, int) const
>>> defined at ../inet/src\inet/common/clock\ClockUserModuleMixin.h:69
>>>            out/clang-debug//test.o
>>> defined at libINET_dbg.dll

etc.
```

## Workaround
None yet.... ld is too slow to be usable!

**Comment by edlongman** [comment]
So ld can succesfully compile the mixin if the correct makefile options are set

`LDFLAGS += -Wl,--allow-multiple-definition`
```
#include <omnetpp.h>
#include <inet/common/clock/ClockUserModuleBase.h>

class FooModule : public inet::ClockUserModuleMixin<omnetpp::cSimpleModule>{
};
Define_Module(FooModule);
```

But not using the base module
```
#include <omnetpp.h>
#include <inet/common/clock/ClockUserModuleBase.h>

class FooModule : public inet::ClockUserModuleBase{
};
Define_Module(FooModule);
```

**Comment by edlongman** [comment]
I can now successfully compile (with duplicate symbol warnings) using the following LDFLAGS in my makefrag

`LDFLAGS += -Wl,-Xlink=-force:multiple`

**Comment by rhornig** [comment]
This is happening because the same template is implicitly instantiated in both the INET project and the derived project. Usually happens when you instantiate an object that is derived from a templated class. As a workaround, you can add something like this in the derived project (i.e. for OperationalMixin problem):
`extern template class inet::OperationalMixin<omnetpp::cSimpleModule>;`

The proper solution would be to add this extern definition in INET header files and add an EXPLICT template initialization in INET cc files. That would prevent instatiation in the derived project.

**Comment by rhornig** [comment]
in ffc2ee03a55bb8d8aa25611e983ef9f7a52f537d I have added some `extern template` markers to prevent implicit instatiation of these mixin classes. This should prevent the duplicate symbol error.
