### ISSUE TITLE
Preemption showcase: traffic arriving at the same time is selected incorrectly

### ISSUE THREAD

**Issue by infacc** [inet-framework/inet#725]
Version: OMNeT++ 6.0 Preview 12 (commit: 13e98dc081d56ab2118e8d42884ce9dca6f5327e)

## Steps to Reproduce 

- Modify the [preemption showcase](https://github.com/inet-framework/inet/tree/5f2f56a787d2d165c460f0b7da07fb79a82a2ead/showcases/ethernet/preemption) such that `background` traffic and `high-ts` traffic arrive at the `EthernetPreemptingMacLayer` at the same time.
  
  E.g. remove the `source.initialProductionOffset` for `host1.app[0]` in the [omnetpp.ini](https://github.com/inet-framework/inet/blob/07097e6f1669d97c609015074e8f572fe1f8db49/showcases/ethernet/preemption/omnetpp.ini#L31-L34) file:
  ```diff
  # background ~96Mbps
  *.host1.app[0].source.packetLength = 1200B
  *.host1.app[0].source.productionInterval = truncnormal(100us,50us)
  - *.host1.app[0].source.initialProductionOffset = 5us
  ```
- Run the modified showcase. To observe the problem, zoom into `EthernetPreemptionShowcase.host1.eth[0].macLayer` and let the simulation run to event `17`.

## Problem

Both, the `background` and `high-ts` traffic, arrive at the `macLayer` of `host1.eth[0]` at the same simulation time. Therefore, the `high-ts` traffic should be forwarded first. But, what actually happens, is that the `background` traffic gets forwarded first and then preempted as soon as possible.
From my point of view the `high-ts` traffic should be forwarded first, since no simulation time has passed between the arrival of the `background` and `high-ts` traffic.

https://user-images.githubusercontent.com/33042539/133763721-455dab9b-26ca-4907-8070-748d477e9f01.mp4

**Comment by levy** [comment]
This is a known limitation. In principle you are right about what should happen, but in practice this change would have very little effect on the statistical simulation results. Moreover, it's very unlikely in a real-world scenario that two frames with different priorities arrive at the exact same moment to the MAC layer.

The difficulty that this change would introduce in the MAC layer simply not worth it. This difficulty comes from the fact that the background frame arrives earlier to the MAC layer and it would have to be delayed in the processing to see if any higher priority frame arrives at the very same moment of time. The number of potential events at that simulation time are unknown, so the processing would have to be delayed after the last such event is processed. There isn't any easy solution for this kind of problem and it's probably not worth fixing it. In the above example if the background frame would have arrived 1 ps earlier you would pretty much get the above result.

**Comment by infacc** [comment]
Thanks for the quick reply. In general I agree that the effect on statistical simulation results is very small, but with identical `productionInterval`s of two apps the effect adds up.
As you indicated, one can set the `initialProductionOffset` to 1 ps to work around the problem, or one can [randomize](https://doc.omnetpp.org/omnetpp/manual/#sec:sim-lib:random-variate-generation) the `productionInterval` as in the [preemption showcase](https://github.com/inet-framework/inet/tree/5f2f56a787d2d165c460f0b7da07fb79a82a2ead/showcases/ethernet/preemption) to avoid the cyclic repetition of the error.
Furthermore, in this specific scenario, traffic prioritized indexing of the apps seems to produce the desired behavior (`host1.app[0]` &#x1f862; `high-ts` traffic, `host1.app[1]` &#x1f862; `background` traffic).

**Comment by rhornig** [comment]
Also using different (OMNeT++) message priorities at the application layer would work around this problem. But I agree, ordering the apps is a much simpler solution (although this is undefined behavior and may change unexpectedly). The proper solution is indeed adding a jitter to the application traffic parameters.
