### ISSUE TITLE
Features.h file is missing in both the .zip and .tgz files of INET4.3.2.

### ISSUE THREAD

**Issue by Gulabi-star** [inet-framework/inet#729]
A message "features.h file is missing" popped up (image is attached) when we initiated the "build project" in OMNeT++ 6.0 prev11. Although the build project runs without any errors, this step caused a ripple effect in generating a series of errors in our Veins_Inet, and Simu5G "build project" execution.
We found that both your ".zip file", and ".tgz file" of INET 4.3.2 do not contain the "features.h" file (images are attached for ready reference). Thought of bringing this to your notice.  

Thank you, 
Regards, 
Gulabi Mandal

![INET_Popup](https://user-images.githubusercontent.com/85755755/135738715-52aeb912-32d8-4fab-9f19-e004bd0c6f1e.png)

![ZipFile_with_Features_h_Present](https://user-images.githubusercontent.com/85755755/135738734-64f3061b-8592-466d-a5df-831c6730f94c.png)
![tgzfile_Features_h_missing](https://user-images.githubusercontent.com/85755755/135738735-3d00ffb4-3600-441d-916c-c65ca0b70499.png)

**Comment by rhornig** [comment]
Thnaks fot the report. `features.h` is generated on the first build of INET so it should not be included in the ZIP/TGZ file. It seems that the IDE starts to index the workspace while the INET project was not built and that causes the given error dialog. Once you build INET it will not appear again. I admit, this is annoying. I will try to take a look how to avoid this, but it might be out of the control of the INET project.

**Comment by rhornig** [comment]
This is an IDE artifact. The IDE itself tries to index all header files, but feature.h is created only on the first INET build
