### ISSUE TITLE
Class "inet::visualizer::SceneOsgVisualizer" not found error

### ISSUE THREAD

**Issue by adamgeorge309** [inet-framework/inet#730]
When osg and osg-earth are disabled in the INET features, simulations which have IntegratedVisualizer throw this error when run from Cmdenv or with fingerprint test. It works in Qtenv.

**Comment by levy** [comment]
I checked this as follows:
 - WITH_OSG=no and WITH_OSGEARTH=no in omnetpp configure
 - added IntegratedVisualizer to wireless tutorial
 - run tutorial both in Cmdenv and Qtenv

There were no errors.
