### ISSUE TITLE
simulate AFDX

### ISSUE THREAD

**Issue by Jin10Dong** [inet-framework/inet#731]
I want to simulate complete AFDX with INET4 and omnetpp-models/afdx, such as 
                                                        switch0
                                                     //             \\
                                                   //                  \\
                                                 //                      \\
app0--->udp--->ipv4--->es0                            es1--->ipv4--->udp--->app1
                                                 \\                      //
                                                   \\                  //
                                                      \\             //
                                                         switch1

Can someone give me some ideas?
Thanks

**Comment by rhornig** [comment]
no a bugreport
