### ISSUE TITLE
End-to-end delay vector recorded incorrectly

### ISSUE THREAD

**Issue by adamgeorge309** [inet-framework/inet#735]
The first end-to-end delay (meanBitLifeTimePerPacket) vector value is recorded incorrectly in showcases/measurement/endtoenddelay.
Recorded value: 116us
Correct value: 100.37us

The time is incorrect as well.
Recorded time: ~400us
Correct value: 100.37us

I'm on the topic/tsn branch in INET.

**Comment by levy** [comment]
This seems to work in master now:
![image](https://user-images.githubusercontent.com/112461/157853598-824c722b-e10c-4cfc-949f-339d8dabcd84.png)
