### ISSUE TITLE
Linker error for INET 4.3.5 and OMNeT++ 6.0 preview 15 (Windows)

### ISSUE THREAD

**Issue by Jurek822** [inet-framework/inet#736]
In OMNeT++ 6.0 pre 15 compilation of INET 4.3.5 results in the following linker error.
OS: Windows 10

    Creating shared library: ../out/clang-debug/src/libINET_dbg.dll
    lld-link: error: undefined symbol: __declspec(dllimport) select
    >>> referenced by inet/common/scheduler/RealTimeScheduler.cc:135
    >>>   ../out/clang-debug/src/inet/common/scheduler/RealTimeScheduler.o:(inet::RealTimeScheduler::receiveWithTimeout(long long))
    lld-link: error: undefined symbol: __declspec(dllimport) htons`
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:39
    >>>../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::serialize(inet::MemoryOutputStream&, inet::IntrusivePtr<inet::Chunk const> const&) const)
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:48
    >>>  ../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::serialize(inet::MemoryOutputStream&, inet::IntrusivePtr<inet::Chunk const> const&) const)
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:53
    >>>   ../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::serialize(inet::MemoryOutputStream&, inet::IntrusivePtr<inet::Chunk const> const&) const)
    >>> referenced 188 more times
    
    lld-link: error: undefined symbol: __declspec(dllimport) htonl
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:51
    >>>               ../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::serialize(inet::MemoryOutputStream&, inet::IntrusivePtr<inet::Chunk const> const&) const)
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:52
    >>>               ../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::serialize(inet::MemoryOutputStream&, inet::IntrusivePtr<inet::Chunk const> const&) const)
    >>> referenced by inet/transportlayer/sctp/SctpChecksum.cc:115
    >>>               ../out/clang-debug/src/inet/transportlayer/sctp/SctpChecksum.o:(inet::sctp::SctpChecksum::checksum(void const*, unsigned int))
    >>> referenced 66 more times
    
    lld-link: error: undefined symbol: __declspec(dllimport) ntohl
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:168
    >>>               ../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::deserialize(inet::MemoryInputStream&) const)
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:169
    >>>               ../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::deserialize(inet::MemoryInputStream&) const)
    >>> referenced by inet/transportlayer/sctp/SctpHeaderSerializer.cc:1158
    >>>               ../out/clang-debug/src/inet/transportlayer/sctp/SctpHeaderSerializer.o:(inet::sctp::SctpHeaderSerializer::deserialize(inet::MemoryInputStream&) const)
    >>> referenced 42 more times
    
    lld-link: error: undefined symbol: __declspec(dllimport) ntohs
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:172
    >>>               ../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::deserialize(inet::MemoryInputStream&) const)
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:173
    >>>               ../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::deserialize(inet::MemoryInputStream&) const)
    >>> referenced by inet/networklayer/ipv4/Ipv4HeaderSerializer.cc:177
    >>>               ../out/clang-debug/src/inet/networklayer/ipv4/Ipv4HeaderSerializer.o:(inet::Ipv4HeaderSerializer::deserialize(inet::MemoryInputStream&) const)
    >>> referenced 88 more times
    clang++: error: linker command failed with exit code 1 (use -v to see invocation)
    C:\omnetpp\omnetpp-6.0pre15\tools\win32.x86_64\mingw64\bin/llvm-ar.exe: error: unable to load '../out/clang-debug/src/libINET_dbg.dll.a': No such file or directory
    make[1]: *** [Makefile:1762: ../out/clang-debug/src/libINET_dbg.dll] Error 1
    make[1]: Leaving directory '/c/omnetpp/omnetpp-6.0pre15/samples/inet4.3.5/src'
    make: *** [Makefile:7: all] Error 2
    "make MODE=debug -j8 all" terminated with exit code 2. Build might be incomplete.

15:26:09 Build Failed. 2 errors, 0 warnings. (took 11s.960ms)

**Comment by lqywow** [comment]
So how can i solve this problem?

**Comment by rhornig** [comment]
This happened because the ws2_32 (winsock2) DLL is not linked to INET. `-lws2_32` is added in the `makefrag` file and the test condition around the addition (testing for win32 architecture) changed. i.e. the $(PLATFORM) variable no longer contains the architecture also on omnetpp 6 pre15. Exactly for this reason a new INET version was released and it's explictly stated that INET 4.3.5 does NOT work omnet 6 pre15.
