### ISSUE TITLE
Question - 802.1Qcr asynchronous traffic shaper implementation

### ISSUE THREAD

**Issue by guohaorui** [inet-framework/inet#738]
Hi,
I saw that there are some ATS related files in `inet/showcases/tsn/trafficshaping/asynchronousshaper/`. Recently i am working on relevant work on ATS (Asynchronous Traffic Shaper, proposed in Qcr), so i am wondering the progress of qcr implementation work (including UBS, paternoster), or maybe could you give me some suggestions on implementing UBS and paternoster?
Best,
Henry

**Comment by guohaorui** [comment]
Additionally, i am wondering whether the ats related must require version 6 of omnet++ cause that version (preview) crashed

**Comment by levy** [comment]
I'm sorry but I don't know much about the ATS details you asking for. The current version supports the basic ATS functionality as demonstrated by the corresponding showcase.

The latest version is available in the topic/tsn branch and it should work with the latest OMNeT++ preview version. Right now I'm working on merging this branch into the INET master branch.

**Comment by guohaorui** [comment]
Thanks very much! There is one more question that the `omnetpp.ini` file in the `inet/showcases/tsn/trafficshaping/asynchronousshaper/` states the `inet.networks.tsn.TsnLinearNetwork` network is used, could you please tell me where this network location is?
