### ISSUE TITLE
Question: How to assign priority based on time slots on 802.1Qci(Per-Stream Filtering and Policing)

### ISSUE THREAD

**Issue by LystarmyNZT** [inet-framework/inet#749]
Hi,
I'm just getting started and it's a pleasure to use your framework! I would like to implement the model mentioned in IEEE802.1Qch, which involves applying internal priority values and time slot classification of PSFP (IEEE802.1Qci). This problem has been bothering me for weeks, so please give some suggestions to implement it. 
Good luck with your work!

**Comment by levy** [comment]
The github issue tracker is not a discussion forum, please send your questions to the mailing list instead.
