### ISSUE TITLE
"simtime_t: Out of range" in IEEE 802.11 model on OMNeT++ 6.0, INET 4.3.7  

### ISSUE THREAD

**Issue by sommer** [inet-framework/inet#756]
Tried `examples/wireless/lan80211` using OMNeT++ 6.0 with both INET 4.3.7 and the current v4.3.x branch. Got the following error when `MediumLimitCache` tries to initialize `minInterferenceTime`.

Is OMNeT++ 6.0 not compatible with INET 4.3.7 as stated on https://inet.omnetpp.org/Download.html ? Am I doing something wrong?

```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.2.1

$ clang++ --version
Apple clang version 13.0.0 (clang-1300.0.29.30)

$ opp_run --version
OMNeT++ Discrete Event Simulation  (C) 1992-2022 Andras Varga, OpenSim Ltd.
Version: 6.0, build: 220413-71d8fab425, edition: Academic Public License -- NOT FOR COMMERCIAL USE

$ git describe --tags HEAD
v4.3.7-6-g1f3998168a

$ cd examples/wireless/lan80211
$ lldb -- opp_run_dbg --debug-on-errors=true -u Cmdenv -c Ping1 -m -n ../../../src:../..:../../../tutorials:../../../showcases -x "inet.emulation;inet.showcases.visualizer.osg;inet.showcases.emulation;inet.clock.common;inet.clock.model;inet.examples.voipstream;inet.clock.oscillator;inet.examples.emulation;inet.transportlayer.tcp_lwip;inet.applications.voipstream;inet.clock.base;inet.examples.clock;inet.transportlayer.tcp_nsc" --image-path=../../../images -l ../../../src/INET omnetpp.ini
[...]
(lldb) pro lau
[...]
<!> Cannot convert nan to simtime_t: Out of range (-9223372.036854775807,9223372.036854775807), allowed by scale exponent -12 -- in module (inet::physicallayer::RadioMedium) Lan80211.radioMedium (id=4), during network setup
[...]
(lldb) up 10
frame #10: 0x000000011633c721 libINET_dbg.dylib`inet::physicallayer::MediumLimitCache::MediumLimitCache(this=0x000000010233c040) at MediumLimitCache.cc:72:5
   69  	    minInterferencePower(W(NaN)),
   70  	    minReceptionPower(W(NaN)),
   71  	    maxAntennaGain(NaN),
-> 72  	    minInterferenceTime(NaN),
   73  	    maxTransmissionDuration(NaN),
   74  	    maxCommunicationRange(m(NaN)),
   75  	    maxInterferenceRange(m(NaN))
```

**Comment by wischhof** [comment]
Had the same problem. It is fixed on the master in commit fed4529f3d828f5ff8df20733a6358ad6b0731c9. 
If you cherry-pick this commit on top of the v4.3.7 branch, it works for me. However, it would of course be great to have an official new inet release which includes this fix. ;-)

**Comment by dragos-bth** [comment]
Had the same problem and checked for advice on the omnetpp mailing list (see below). Thanks for the fix, would welcome a new inet release though!

---

I have upgraded to omnetpp-6.0 (release) from omnetpp-6.0rc2. I run make cleanall in inet-4.3.7 and my own MANET project. After rebuilding, as soon as I re-rerun the simulation I am greeted by an error message "Cannot convert nan to simtime_t: Out of range (-9223372.036854775807,9223372.036854775807), allowed by scale exponent -12 -- in module (inet::physicallayer::RadioMedium) MANET.radioMedium (id=4), during network setup”.

When downgrading back to omnetpp-6.0rc2 I can run the simulation with no problems. My nodes use the AckingWirelessInterface. Any ideas what it is going wrong and how I can fix it? For now, I can keep running on rc2. Please, let me know if you need additional information to diagnose the problem. Environment Mac OS x86_64.

**Comment by levy** [comment]
Thanks for the bug report and we're sorry for the inconvenience!

Indeed, we will have to backport some fixes from the INET master branch. The omnet 6.0 version correctly reports an error for converting a double NAN to a simtime, because it cannot be represented. Unfortunately, old INET versions incorrectly used NANs as the default uninitialized value for several simtime variables.

**Comment by rhornig** [comment]
INET 4.3.8 released.
