### ISSUE TITLE
.ini files location for Linklayer configuration. For example, B-Mac or X-Mac .ini file not found on src folder

### ISSUE THREAD

**Issue by mbhuiyanst** [inet-framework/inet#759]
My INET version is 4.2.10 , and omnet++ is 6.0. I did not find .ini files for Linklayer protocol configuration.
Any one can help me regarding where is the .ini file for Linklayer configuration.

Thanks

**Comment by levy** [comment]
This is not a forum but a bug tracker. Please either report an issue or ask questions on the mailing list.
