### ISSUE TITLE
IPvXAddress::doPacking results in a weird infinite loop

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#76]
If I call doPacking on a IPvXAddress which is an IPv4Address at runtime, the IPvXAddress::doPacking member function for some reason calls itself, which results in an infinite loop. This is the part of the code:

/src/networklayer/contractIPvXAddress.h:
295 inline void doPacking(cCommBuffer *buf, const IPvXAddress& addr)
296 {
297 if (buf->packFlag(addr.isIPv6()))
298 doPacking(buf, addr.get6());
299 else
300 doPacking(buf, addr.get4());
301 }

I do not really understand why this happens, since addr.get4() returns an IPv4Address object - so line 300 should call IPv4Address::doPacking?! However, it seems to work for IPv6: Ctrl+Click on line 298 in the OmNET IDE jumps to the correct function. :-)

Additional Information: I fixed this for myself by passing a "real" IPv4Address:

inline void doPacking(cCommBuffer *buf, const IPvXAddress& addr)
{
    if (buf->packFlag(addr.isIPv6()))
        doPacking(buf, addr.get6());
    else {
        IPv4Adress ipv4 = addr.get4();
        doPacking(buf, ipv4);
    }
}

from: http://dev.omnetpp.org/bugs/view.php?id=735

**Comment by ZoltanBojthe** [comment]
IPvXAddress class removed, obsolete
