### ISSUE TITLE
z3-solver set-up

### ISSUE THREAD

**Issue by ghjk138243** [inet-framework/inet#760]
When i running the simulation of gate-scheduling ,I met with this error--->TSNsched command execution failed, make sure TSNSCHED_ROOT is set and Microsoft Z3 is installed -- in module

How can i set the z3-solver in the same directory?

**Comment by levy** [comment]
You can install Z3 with
```
sudo apt install libz3-dev
```
and set TSNSCHED_ROOT with something like
```
export TSNSCHED_ROOT=/home/user/TSNsched
```

**Comment by ghjk138243** [comment]
![7](https://user-images.githubusercontent.com/103174038/169056650-6ee679f7-b324-49b4-b9ba-7edc3c54ce98.PNG)
when i import the inet-framework, i found z3 folder does not work

**Comment by levy** [comment]
You need to enable the feature in the project properties page.

**Comment by levy** [comment]
Please ask these questions on the mailing list.
