### ISSUE TITLE
tsnsched

### ISSUE THREAD

**Issue by ghjk138243** [inet-framework/inet#761]
![9](https://user-images.githubusercontent.com/103174038/169248851-530ce7ab-65da-48dd-930f-060240dc885f.PNG)
when i running tsnsched , i met with this bug 
How can i solve it?

**Comment by levy** [comment]
Check the log, my guess is that there was an error in the TSNsched gate scheduler, most likely it couldn't satisfy the constraints.

**Comment by ghjk138243** [comment]
![11](https://user-images.githubusercontent.com/103174038/169352473-24d875d4-6507-4f0c-8be1-1c0b395d2977.PNG)
where can i fix to satisfy the constraints?

**Comment by levy** [comment]
Try changing the traffic, maybe it doesn't fit into the available throughput. You can also try the other two gate schedulers.

**Comment by ghjk138243** [comment]
![12](https://user-images.githubusercontent.com/103174038/169515717-a3e456e9-5e05-4cb4-8e0a-4f6932e1df98.PNG)
When i running the combining features/invehicle，i set the cofig name to general time sensitive network，i met with this issue. How can i solve it?

**Comment by levy** [comment]
In that example, you should either select StandardEthernet, ManualTsn or AutomaticTsn configuration.

The General configuration cannot be run, because it is no fully parameterized.

**Comment by ghjk138243** [comment]
> 嘗試更改流量，也許它不適合可用的吞吐量。您也可以嘗試其他兩個門調度程序。

where can i modify the traffic?

**Comment by levy** [comment]
This is an issue tracker and not a place for asking such questions. Please read the OMNeT++/INET documentation and ask questions on the mailing list.
