### ISSUE TITLE
ScenarioManager <set-param/> fails for string parameters

### ISSUE THREAD

**Issue by Musteblume** [inet-framework/inet#764]
When i try to set a string parameter a runtime error is thrown. 
Example:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/22887071/170222173-8d03782c-e73f-480d-83da-5b99b5911bbc.png">
With this workaround in ScenarioManager.cc it is working for me:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/22887071/170222420-45ce6d02-b7bb-4728-b990-e433d2223f7f.png">

**Comment by ZoltanBojthe** [comment]
accepted formats in omnetpp 6.0:
`<set-param t="1s" module="path.to.module" par="stringParamName" value='"new string value"'/>`
`<set-param t="2s" module="path.to.module" par="stringParamName" value="&quot;new string value&quot;"/>`
_set path.to.module.stringParamName to "new string value"_

**Comment by Musteblume** [comment]
Ahh okay perfect. Thanks for your help.
