### ISSUE TITLE
Pcaprecorder can't record UDP inet::ApplicationPacket

### ISSUE THREAD

**Issue by asiahowtone** [inet-framework/inet#766]
Hi, I'm working on a Veins project which needs to record the UDP inet::ApplicationPacket through 802.11. I can only record 802.11 ACK packet,but can't record the UDP inet::Application packet using pcaprecorder. Is it possible to record the packet, or just something wrong with my code. Thanks. 
![擷取](https://user-images.githubusercontent.com/52411064/171092858-071d3ea1-d254-4f66-a0fa-c811c7aea329.JPG)
![image](https://user-images.githubusercontent.com/52411064/171093056-706a89d4-644b-4a1c-bb81-fe89e4393934.png)
![image](https://user-images.githubusercontent.com/52411064/171093114-766b8dea-a1c2-4a37-a583-ff42cdfa5963.png)

**Comment by levy** [comment]
It should be possible to record them in PCAP files in the latest INET version.

What is the exact error message? Which INET version are you using?

**Comment by asiahowtone** [comment]
There is no error message. It's my pcap file only have LLC and 802.11 packet. I want to record the UDP packet in the above picture. 
My INET version is 4.2.8. 
Does it only work in the latest INET verison?
![image](https://user-images.githubusercontent.com/52411064/171110444-3618bf2d-8b43-47e4-93ab-8e5035eb944d.png)

**Comment by levy** [comment]
No, it should work in your version too.

**Comment by asiahowtone** [comment]
Do you have any idea of this problem? I have tried to solve this for a while. Thanks.

**Comment by ZoltanBojthe** [comment]
@asiahowtone could you attach your pcap file to this issue? I think the LLC frames equals to your missing UDP frames but something wrong in frame content ...

**Comment by ZoltanBojthe** [comment]
Not reproducible,  ApplicationPacket recorded correctly to pcap file in current master.
