### ISSUE TITLE
[TSN bug] PeriodicGate: Unexpected Guard Bands

### ISSUE THREAD

**Issue by yue2388253** [inet-framework/inet#775]
In the function `canPacketFlowThrough` of PeriodicGate, it creates a guard band when the 
gate is about to close.

https://github.com/inet-framework/inet/blob/edf1bd0a8139571923601f29d87826700d21872b/src/inet/queueing/gate/PeriodicGate.cc#L105-L115

However, this would lead to unexpected guard bands.
For example, using a `AlwaysOpenGateScheduleConfigurator` with `gateCycleDuration` being `500us`,
it would generate two `changeTimer` events each `500us`---one for closing the gate and the other for 
immediately opening the gate, as shown in the picture below.

![Screenshot from 2022-06-29 10-35-48](https://user-images.githubusercontent.com/33801130/176339026-c46a49c4-b7a2-491d-934f-9b2f71c397ef.png)

**Comment by yue2388253** [comment]
I think maybe PeriodicGate can provide a parameter to disable this implicit guard band feature
and simply forwards the packet depending on the current gateState, e.g.,

```cpp
 bool PeriodicGate::canPacketFlowThrough(Packet *packet) const 
 { 
     if (std::isnan(bitrate.get())) 
         return PacketGateBase::canPacketFlowThrough(packet); 
     else if (packet == nullptr) 
         return false; 
     else { 
         return isOpen_;
     } 
 } 
```

This can be helpful for users who have some GCLs where there are explicit guard bands (i.e., 
the gates for transmitting unprotected packets are closed in advanced).

**Comment by levy** [comment]
Hmm. I think the PeriodicGate should be able to handle the case when it's either open or closed all the time. Maybe the AlwaysOpenGateScheduleConfigurator should result in an empty durations parameter setting and an initiallyOpen parameter set to true.

**Comment by yue2388253** [comment]
Yep. 

Currently PeriodicGate assumes the input `durations` parameter should be even.
In each two durations, one is for opening the gate and the other is for closing.
This requirement can be relaxed by re-writing the `initializeGating()` and `scheduleChangeTimer()`
methods of `PeriodicGate`.

**Comment by levy** [comment]
This has been fixed in the master branch. Now the AlwaysOpenGateScheduleConfigurator creates a schedule that has zero intervals and open by default. This results in the change timers to not being not used by the PeriodicGate, so there's no unexpected implicit guard band.
