### ISSUE TITLE
Still linking errors with INET 4.4 & WindowsOS when deriving class derivative of ClockUserModuleMixin

### ISSUE THREAD

**Issue by LucaBH** [inet-framework/inet#777]
Hi guys.
I'm facing the same linking error described in #723, which I see has been closed because supposedly resolved.

However when I moved from INET 4.3 to 4.4 it starts popping up. In details, I'm implementing a class deriving PacketDelayer, and linker fails dumping errors like this one:
```
lld-link: error: duplicate symbol: inet::ClockUserModuleMixin<inet::queueing::PacketPusherBase>::normal(inet::ClockTime, inet::ClockTime, int) const
>>> defined at <my_derived_class.o>
>>> defined at libINET.dll
```

There's something I can do or I'm missing?

Regards,
Luca

**Comment by rhornig** [comment]
Sight..  Windows linker cannot eliminate these duplicate symbols automatically and they happen only if you instantiate a template class that is also used and exported by INET. Would you mind trying out 8d683bdde60f1be1e167a44799cbf19b32a6ad56 whether it works? I have added this to the v4.4.x branch so it is supposed to be included in 4.4.1

**Comment by LucaBH** [comment]
Hi.
I tried but I cannot confirm if the commit solves the issue as another one keeps my project from linking. I'm going to open a new issue for that. I'll get back here once I have an answer.

**Comment by rhornig** [comment]
Thanks. Added it also to the master branch.
