### ISSUE TITLE
WiseRoute problem

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#805]
The packet of type ROUTE_FLOOD doesn't have payload,  the code try to copy the payload with length 0 that throw an exception

A possible solution is to check that the packet is of the type ROUTE_FLOOD and avoid the data copy

https://github.com/aarizaq/inetmanet-4.x/commit/6c1accf4e1b720606934df26d94ac573798fdf32

**Comment by ZoltanBojthe** [comment]
@aarizaq I added a new topic/issue805 branch for INET with the fixing. Try it please, and send me an example to demonstrate the error when occured.

**Comment by aarizaq** [comment]
With the changes, the simulations run fine.

**Comment by ZoltanBojthe** [comment]
thx, merged to master
