### ISSUE TITLE
Inet and Nesting TSN modules

### ISSUE THREAD

**Issue by MaFe1401** [inet-framework/inet#808]
Hi! If I am not wrong the Inet TSN features are based on the Nesting library. I need to redo a project which used Nesting but using only Inet. Is it possible? Are there any equivalent modules in Inet to this ones from Nesting? : 

![Captura de pantalla de 2022-08-14 18-07-14](https://user-images.githubusercontent.com/57569408/184545439-217d0dcd-2654-4b35-9583-54a55ecf5f79.png)

The modules' names are: FilteringDatabase (used to store filtering and forwarding rules), ScheduleSwap (to initiate schedule changes in FilteringDatabase), IOscillator (to provide a stub for oscillator components with a configurable clock rate), IClock (to provide a stub for clock components with a configurable clock rate) and IClock2.

Thank you in advance.

**Comment by levy** [comment]
No, there are no one-to-one drop in replacements for Nesting modules in INET. Please take a look at the showcases and the documentation in the User's Guide. INET supports the TSN functionality (even more) present in Nesting. Porting a simulation project requires understanding both INET and Nesting and converting by creating an equivalent simulation. Let me know if you have any issues with the implementation in INET.
