### ISSUE TITLE
[bug?] PTP+TAS

### ISSUE THREAD

**Issue by ulbricht-inr** [inet-framework/inet#811]
Hi,
I tried to combine the simple examples for gPTP and TimeawareShaping. Client-Switch-Server and PTP-clock. If I run the simulation this produced in the error message:
```omnetpp::common::expression::ExprNode::eval_error: Object nullptr has no member named 'destPort' -- in module (inet::queueing::PacketMultiplexer) OneMasterClockGptpShowcase.client.bridging.directionReverser.join (id=337), at t=0s, event #13 ```

I appended both files for a minimal example. [simulations.tar.gz](https://github.com/inet-framework/inet/files/9550431/simulations.tar.gz)

If I disable `*.client.hasOutgoingStreams = true` this solved the problem with the error message and the simulation is running, but all packets are sorted in the same queue :/

Could someone confirm if this is a bug?

Thank you very much, 

Greeting :)

**Comment by ulbricht-inr** [comment]
ok, could be solved by adapting the filter to check for UDP: https://stackoverflow.com/questions/73651281/how-can-i-integratre-inet-gptp-with-inet-tas .. no BUG just RTFM ;)

**Comment by levy** [comment]
BTW, there's already a showcase that combines gPTP and TAS: https://inet.omnetpp.org/docs/showcases/tsn/combiningfeatures/gptpandtas/doc/index.html
