### ISSUE TITLE
Ethernet emulation EthernetMacBase doesn't work

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#812]
ExtUpperEthernetInterface doesn't include the queue module and EthernetMacBase::initialize(int stage) raises an error in 
txQueue = getQueue(gate(upperLayerInGateId));

**Comment by ZoltanBojthe** [comment]
@aarizaq Could you try my fix?

**Comment by aarizaq** [comment]
I have tried to test, there is an error in the NAT configuration of the showcases example. I have tried to find the configuration documentation, but I cannot find the instructions.

**Comment by ZoltanBojthe** [comment]
The PacketFilter and the showcase are fixed in inet master, too
