### ISSUE TITLE
Implicit chunk serialization Error - While using Access Category QoS IEEE802.11p

### ISSUE THREAD

**Issue by JeffreyRed** [inet-framework/inet#813]
With the attached setup after few seconds I am getting error Implicit chunk serialization. No modification has been performed in inet. everything is used by the examples and showcases. Could you help me to see if anything is wrongly configure? or is this a problem with inet? to happen earlier or later in the simulation the packet size has to be changed. Currently the configuration is done to fail as fastest as possible.

OMNet++ 5.7
inet [4.2.9]

- Few wireless adhoc nodes configure with 4 "UdpBasicApp"
- one wireless server adhoc 4 UdpSink.
- QoS
> - *.*.wlan[*].mac.qosStation = true
> - *.*.wlan[*].classifier.typename = "QosClassifier"

- configuration to run : **[Config QoS]**
- ini file, .ned file:
[files.zip](https://github.com/inet-framework/inet/files/9626310/files.zip)

**Comment by ZoltanBojthe** [comment]
Ethernet frame was unsupported in QosClassifier in inet 4.2.9.
The next commit added ethernet support for QosClassifier (available from inet 4.3.0).
https://github.com/inet-framework/inet/commit/eb3ab52ac6c40d2bf99e6aadf1fe6471b1677baf

**Comment by JeffreyRed** [comment]
Hi, 
I have tried inet4.3.9 as suggested (OMNet++ 6.0). Still I got the same error. it looks when I put packet size higher the fragmentation confuses the header. same configuration 

*.node[*].app[3].messageLength = 3900B
*.node[*].app[3].sendInterval = normal(350us,10us)

![image](https://user-images.githubusercontent.com/38228891/191961965-7769616e-19df-4411-ace5-bb8e23d54d96.png)

When selecting a lower value, I got new error 
*.node[*].app[3].messageLength = 900B
*.node[*].app[3].sendInterval = normal(350us,10us)
![image](https://user-images.githubusercontent.com/38228891/191962115-8cd2ebe2-1eaa-41fa-8114-57b63d8419ad.png)



Regards.
Jeffrey Redondo
