### ISSUE TITLE
Inet4.3.9 - Implicit chunk serialization Error - While using Access Category QoS IEEE802.11p

### ISSUE THREAD

**Issue by JeffreyRed** [inet-framework/inet#814]
Hi, 
I have tried inet4.3.9 as suggested (OMNet++ 6.0). Still I got the same error. it looks when I put packet size higher the fragmentation confuses the header. same configuration 

*.node[*].app[3].messageLength = 3900B
*.node[*].app[3].sendInterval = normal(350us,10us)

![image](https://user-images.githubusercontent.com/38228891/191961965-7769616e-19df-4411-ace5-bb8e23d54d96.png)

When selecting a lower value, I got new error 
*.node[*].app[3].messageLength = 900B
*.node[*].app[3].sendInterval = normal(350us,10us)
![image](https://user-images.githubusercontent.com/38228891/191962115-8cd2ebe2-1eaa-41fa-8114-57b63d8419ad.png)
#Previous 
_Originally posted by @JeffreyRed in https://github.com/inet-framework/inet/issues/813#issuecomment-1256160069_

**Comment by JeffreyRed** [comment]
Attaching files.
[files.zip](https://github.com/inet-framework/inet/files/9633892/files.zip)

**Comment by ZoltanBojthe** [comment]
@JeffreyRed Added a minor fix for QosClassifier in inet master branch: disable parsing the transport layer header in fragmented IPv4 datagrams.
