### ISSUE TITLE
Dielectric loss factor exponent error

### ISSUE THREAD

**Issue by nestor-rdgz** [inet-framework/inet#815]
Hello, 

I have been reviewing the code in `src/inet/physicallayer/wireless/common/obstacleloss/DielectricObstacleLoss.cc` , more specifically, the `computeDielectricLoss` function, which is the following:

```
double DielectricObstacleLoss::computeDielectricLoss(const IMaterial *material, Hz frequency, m distance) const
{
    // NOTE: based on http://en.wikipedia.org/wiki/Dielectric_loss
    double lossTangent = material->getDielectricLossTangent(frequency);
    mps propagationSpeed = material->getPropagationSpeed();
    double factor = std::exp(-atan(lossTangent) * unit(2 * M_PI * frequency * distance / propagationSpeed).get());
    ASSERT(0 <= factor && factor <= 1);
    return factor;
}
```

I believe that the factor is lacking a "2" in the exponent, which is shown by the[ wikipedia page on Dielectric Loss](http://en.wikipedia.org/wiki/Dielectric_loss): $P = P_{0} e^{-2\delta kz}$

However, what is currently programmed in the function is the following:

$e^{\frac{-\delta 2\pi f z}{\nu}} = e^{\frac{-\delta \omega z n}{c}} = e^{\frac{-\delta \omega z \sqrt{\varepsilon_{r} \mu_{r}}}{c}} = e^{\frac{-\delta \omega z \sqrt{\frac{\varepsilon ' \mu}{\varepsilon_{0} \mu_{0}}}}{c}} = e^{\frac{-\delta \omega z \sqrt{\varepsilon ' \mu}}{\sqrt{\varepsilon_{0} \mu_{0}} \cdot c}} \rightarrow$ if $k=\omega \cdot \sqrt{\varepsilon ' \mu} \Rightarrow  e^{-\delta k  z}$    

**Therefore, it seems that in the code it would be needed a "2" multiplying the exponent in order to calculate the $e^{-2\delta k  z}$ factor as presented in the wikipedia formula.**

I don't know if this is solved in other function, when applying the factor. If so, I did not notice it. 

I would appreciate if someone could check this issue.

Thank you!

**Comment by levy** [comment]
Thank you for reporting this issue!

I have checked the code and indeed it seems to be missing a factor of 2. I guess the reason is that there is a 2 * PI in the code, which looks like the missing factor of 2, but in fact that is another factor of 2. I'll double check this with another colleague and create a fix.

**Comment by torokati44** [comment]
Indeed, one factor of two is directly in the exponent of the power coefficient, and another one is "hidden" in the `k` in the exponent.
