### ISSUE TITLE
Chaos management module for manet

### ISSUE THREAD

**Issue by n-jay** [inet-framework/inet#817]
`ScenarioManager` currently operates in a static/predetermined manner using a script on an XML file.

Was wondering whether a chaos management/random fault injection system is currently available that can be used for manets, and if not was thinking of developing one based on `ScenarioManager`.

**Comment by n-jay** [comment]
Hi,
I created a PR with a new module adding this functionality to INET.
https://github.com/inet-framework/inet/pull/821

Would appreciate some feedback on this @rhornig @levy

**Comment by levy** [comment]
See my comment at the PR.
