### ISSUE TITLE
802.11 wrong CSMA behavior

### ISSUE THREAD

**Issue by avarga** [inet-framework/inet#82]
INET version: 2.0

In certain simulations, Ieee80211MAC will start transmitting even when the channel is busy. This should not happen.

The error is in the Radio model that can stay in IDLE when it hears a frame but its receive power is below the sensitivity parameter, see Radio::handleLowerMsgStart(). This is wrong because 'sensitivity' is the minimum power for receiving a frame _correctly_, not the minimum power that will make concurrent frames garbled.

Migrated from: http://dev.omnetpp.org/bugs/view.php?id=624

**Comment by avarga** [comment]
There should be *two* thresholds. The current Radio implementation is totally confused. Keywords: Clear Channel Assessment Energy Detection

**Comment by avarga** [comment]
Introductory material on wifi carrier sensing:
http://revolutionwifi.blogspot.hu/2011/03/understanding-wi-fi-carrier-sense.html?m=1 [^]

**Comment by avarga** [comment]
Alfonso Ariza: A possible solution:
https://github.com/aarizaq/inetmanet-2.0/commit/f0ecf22d2890c382af555ee1b0b54317b8a37826

**Comment by levy** [comment]
This bug is obsolete.
