### ISSUE TITLE
Ethernet cut-through switching breaks when a cut-through transmission is already ongoing

### ISSUE THREAD

**Issue by levy** [inet-framework/inet#820]
When two frames arrive at the same time to a switch and both are eligibile for cut-through transmission, then the simulation stops with an error.

See the description of a problem where this issue is the root cause:
https://stackoverflow.com/questions/73797937/cut-through-switching-is-not-working-when-integrating-with-time-aware-shaper-ta

This is an attempt for fixing this bug: https://github.com/inet-framework/inet/commit/51c3c8850ea7ca505cd8d7d014404ff930bef4a8

**Comment by levy** [comment]
Here is an updated attempt 2a0205205aeb0f7070404b5b160fd4d2b4d6b29e to fix this issue which also works for the Gptp messages coming from TsnClocks. The problem was that TsnClock-s didn't use EthernetStreamingPhyLayer so it wasn't compatible with a cut-through enabled switch.

**Comment by howhangliu** [comment]
Hello Levy,
There is still a bug, where the cut-through stream didn't follow the gate control.

I add the following codes to add the time-aware shaper:

`*.switch*.eth[*].macLayer.queue.numTrafficClasses = 2
*.switch*.eth[*].macLayer.queue.*[0].display-name = "besteff"
*.switch*.eth[*].macLayer.queue.*[1].display-name = "tactile"
*.switch*.eth[*].macLayer.queue.transmissionGate[0].offset = 0ms
*.switch*.eth[*].macLayer.queue.transmissionGate[0].durations = [5ms, 5ms] # period is 10 # length of periods
*.switch*.eth[*].macLayer.queue.transmissionGate[1].offset = 5ms
*.switch*.eth[*].macLayer.queue.transmissionGate[1].durations = [5ms, 5ms]
`
But the streams pass even when the gate is closed.

Please have a look. Thank you.

**Comment by levy** [comment]
Hmm, I believe cut-through switching cannot be used with time aware shaping, because the cut-through path from the incoming interface to the outgoing interface right now completely bypasses the shaping mechanism. Otherwise there could be a delay and it would not even be cut-through switching anymore. Ethernet cut-through only checks if the outgoing interface can be determined from the MAC header and the outgoing interface is not busy at the moment. If both turns out to be true, the packet is immediately forwarded without any further queueing or delay.

**Comment by levy** [comment]
In theory, Ethernet cut-through switching could work with per-stream filtering and traffic shaping, even time-aware shaping could work. But if and only if all components from the incoming network interface, the Ethernet protocol, the bridging layer with the stream decoding and the ingress filter, the interface selection, and finally the outgoing network interface with the queueing and traffic shaper mechanism all would use the packet streaming API, which unfortunately they don't.

**Comment by levy** [comment]
This has been fixed in the master branch. The issue was that the cut-through source module didn't check if another cut-through was already going on in the outgoing network interface cut-through sink module, so two simultaneous cut-through operations from two different incoming network interfaces could lead to an error.
