### ISSUE TITLE
[showcase / measurement / relationships] documentation broken

### ISSUE THREAD

**Issue by windy32** [inet-framework/inet#824]
https://inet.omnetpp.org/docs/showcases/measurement/relationships/doc/index.html

![screenshot208](https://user-images.githubusercontent.com/12342773/197491738-6c2ea81d-54ab-4767-b7b1-a19de704396d.png)

It seems that this page is not completed yet. It is not a valid showcase.

Please fix the content or hide the link in sidebar.

**Comment by adamgeorge309** [comment]
Fixed in master. It'll be fixed on the website eventually, when it's deployed.
