### ISSUE TITLE
Error in examples/diffserv/onedomain/omnetpp.ini

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#825]
The example set the Ppp queue to Ethernet type and the classifier assume that the received packet is Ethernet but with the PPP interface the packet is of the type Network
Possible solution
https://github.com/aarizaq/inetmanet-4.x/commit/9fb9817211c83026eb3d71660d8a3a6cfc635d68

**Comment by ZoltanBojthe** [comment]
Modified the `**.queue.typename = "EthernetQosQueue"` to `**.eth[*].queue.typename = "EthernetQosQueue"` for set only ethernet queues, in inet master.
