### ISSUE TITLE
Link in Time-Aware Shaping showcase broken

### ISSUE THREAD

**Issue by haug-den-lucas** [inet-framework/inet#828]
On the doc page for time-aware shaping https://inet.omnetpp.org/docs/showcases/tsn/trafficshaping/timeawareshaper/doc/index.html the link after _Source files location:_ is broken

Here:
https://github.com/inet-framework/docs/blob/4c8a378ec338cdaa905a33f33cac6d24392f7173/_sources/showcases/tsn/trafficshaping/timeawareshaper/doc/index.rst.txt#L13 (line 13)

**Comment by adamgeorge309** [comment]
Fixed in master. It's going to be fixed on the website eventually, when it's deployed. Thanks for pointing this out.
