### ISSUE TITLE
Simultaneous use of Wifi and Bluetooth

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#829]
Sorry, it is more a curiosity that a problem.

At this moment, if you try two use simultaneously Wi-Fi and Bluetooth, due to that the bandwidth are very different, if they use the same radioMedium the code will crash, it is necessary to use two different radio mediums. It is not problematic except that you lost the interference. 
I am not sure if this behavior was deliberate, considering that most of the scenarios don't use two interfaces of different technologies and in the worst case, we can ignore the interferences between the two technologies.

I think that would be a no-bad idea to include an example using the two technologies simultaneously and with the two simultaneous radioMedium

**Comment by levy** [comment]
You can use the DimensionalRadioMedium variant. It can handle all kinds of different signal shapes, bandwidth and center frequency.

**Comment by aarizaq** [comment]
Ok, thank you
