### ISSUE TITLE
Wireless Throughput example crashes

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#83]
Whne mgmtType of wlan Ieee80211Nic is changed from "Ieee80211MgmtSTASimplified" to "Ieee80211MgmtSTA" (so client needs to do connection handshake with AccessPoint) simulation crashes every time with message opp_run.exe has stopped responding (on Windows 7 64 bit platform).

If mgmtType is set to "Ieee80211MgmtSTASimplified" there are no problems with simulation. This problem also arise in other simulations every time if EtherTrafGen or EtherAppCli simple modules are used with Ieee80211Nic when mgmtType is set to "Ieee80211MgmtSTA".

from: http://dev.omnetpp.org/bugs/view.php?id=678

**Comment by levy** [comment]
This bug is quite old. Does it still crashes on windows?

**Comment by rhornig** [comment]
This issue was submitted for INET 2.2, so it's way outdated. INET 4 has completely new code for 802.11
