### ISSUE TITLE
End - to - end delay in asynchronous shaping

### ISSUE THREAD

**Issue by adsdsfsdfsefdsfd** [inet-framework/inet#831]
[General]
network = test1
description = "Traffic shaping using asynchronous shapers"

*.MU.numApps = 1
*.MU.app[*].typename = "UdpSourceApp"
*.MU.app[0].display-name = "SV"
*.MU.app[*].io.destAddress = "BP"
*.MU.app[0].io.destPort = 1000
#*.client.app[*].source.packetLength = 1000B
*.MU.app[0].source.packetLength = 1200Byte
*.MU.app[0].source.productionInterval = 250us

*.BR.numApps = 1
*.BR.app[*].typename = "UdpSourceApp"
*.BR.app[0].display-name = "GOOSEB"
*.BR.app[*].io.destAddress = "BP"
*.BR.app[0].io.destPort = 1001
#*.client.app[*].source.packetLength = 1000B
*.BR.app[0].source.packetLength = 1200Byte
*.BR.app[0].source.productionInterval = 500us

*.BP.numApps = 2
*.BP.app[*].typename = "UdpSinkApp"
*.BP.app[0].display-name = "SV"
*.BP.app[1].display-name = "GOOSEB"
*.BP.app[0].io.localPort = 1000
*.BP.app[1].io.localPort = 1001

*.MU.hasOutgoingStreams = true
*.BR.hasOutgoingStreams = true

*.MU.bridging.streamIdentifier.identifier.mapping = [{stream: "SV", packetFilter: expr(udp.destPort == 1000)}]
*.BR.bridging.streamIdentifier.identifier.mapping = [{stream: "GOOSEB", packetFilter: expr(udp.destPort == 1001)}]

*.MU.bridging.streamCoder.encoder.mapping = [{stream: "SV", pcp: 7}]
*.BR.bridging.streamCoder.encoder.mapping = [{stream: "GOOSEB", pcp: 6}]

*.switch.bridging.streamCoder.decoder.mapping = [{pcp: 7, stream: "SV"},
                                                 {pcp: 6, stream: "GOOSEB"}]

*.switch.hasIngressTrafficFiltering = true

*.switch.bridging.streamFilter.ingress.numStreams = 2
*.switch.bridging.streamFilter.ingress.classifier.mapping = {"SV": 0, "GOOSEB": 1}
*.switch.bridging.streamFilter.ingress.*[0].display-name = "SV"
*.switch.bridging.streamFilter.ingress.*[1].display-name = "GOOSEB"
*.switch.bridging.streamFilter.ingress.meter[*].typename = "EligibilityTimeMeter"
*.switch.bridging.streamFilter.ingress.meter[*].maxResidenceTime = 10ms
*.switch.bridging.streamFilter.ingress.meter[0].committedInformationRate = 40Mbps
*.switch.bridging.streamFilter.ingress.meter[0].committedBurstSize = 10*1200Byte
#*.switch.bridging.streamFilter.ingress.meter[0].committedBurstSize = 10 * (196B + 28B)
*.switch.bridging.streamFilter.ingress.meter[1].committedInformationRate = 20Mbps
*.switch.bridging.streamFilter.ingress.meter[1].committedBurstSize = 5*1200Byte

*.switch.bridging.streamFilter.ingress.filter[*].typename = "EligibilityTimeFilter"

*.switch.hasEgressTrafficShaping = true

*.switch.eth[*].macLayer.queue.numTrafficClasses = 2
*.switch.eth[*].macLayer.queue.*[0].display-name = "SV"
*.switch.eth[*].macLayer.queue.*[1].display-name = "GOOSEB"
*.switch.eth[*].macLayer.queue.queue[*].typename = "EligibilityTimeQueue"
*.switch.eth[*].macLayer.queue.transmissionSelectionAlgorithm[*].typename = "Ieee8021qAsynchronousShaper"

Hello, the initialization file I set is as shown above, the size of two kinds of packet bytes is 1200 bytes, and the bandwidth of switch port is 100Mbps. In the simulation results,The average value of end-to-end delay packetDelayVariation is 25us in app[0].sink, I think this value is wrong. Because the forwarding delay of the switch port has been about 96us, I think the value of end-to-end delay packetDelayVariation must be larger than 25us, please help me to answer the confusion.

**Comment by levy** [comment]
PacketDelayVariation is not the same as end-to-end delay, it is the variation of the end-to-end delay statistic instead.
