### ISSUE TITLE
Configuring asynchronous shaping (ATS)

### ISSUE THREAD

**Issue by adsdsfsdfsefdsfd** [inet-framework/inet#836]
Hello，“Typically in the per-stream filtering the classifier uses the stream identifier of packets, and in the traffic shaper the classifier uses the traffic category of packets. ”How to set the traffic category in this sentence?For example, Is through "*. switch. bridging. streamFilter. ingress.classifier.mapping = {" best effort" : 0, "video" : 1} "this code sets?Besides,how to set the stream identifier?By" *.client.bridging.streamIdentifier.identifier.mapping = [{stream: "best effort", packetFilter: expr(udp.destPort == 1000)}, {stream: "video", packetFilter: expr(udp.destPort == 1001)}] "?

**Comment by levy** [comment]
This isn't an issue but a question. Please use the mailing list to ask questions.
