### ISSUE TITLE
PCAP time skipping after 1s

### ISSUE THREAD

**Issue by tsnsystemspieter** [inet-framework/inet#838]
Using PCAP recording in inet4.4 + OMNEST 6.0.1 as set up in the `showcases/general/pcaprecording` showcase generates files correctly for the first 1s of simtime. Opening the pcap files in Wireshark (and in the terminal) shows that after the first second (simtime=1s) the time jumps to 4294.967299s and at simtime = 2s it jumps to 8589.934595s. 
The packets continue to be correct, however the time values seem to jump as described prior.

**Comment by ZoltanBojthe** [comment]
Duplicated.
The pull request #763 merged to inet master at 2022-05-24: commit https://github.com/inet-framework/inet/commit/ee77aad1d6b0fab1b855a9184c412919e993f9c5
The fix picked to v4.4.x branch now.
