### ISSUE TITLE
RoutingTableCanvasVisualizer crashes with NoiseSource

### ISSUE THREAD

**Issue by adamgeorge309** [inet-framework/inet#839]
When there is a `NoiseSource` in the network, the `RoutingTableCanvasVisualizer` crashes with segfault in `RoutingTableVisualizerBase::getDestinations()`. The visualizer tries to iterate over all interfaces of network nodes, but the `NoiseSource` is a network node with no interfaces.

**Comment by adamgeorge309** [comment]
Adding a check `if (interfaceTable != nullptr)` seems to solve this.

**Comment by ZoltanBojthe** [comment]
fixed with https://github.com/inet-framework/inet/commit/3570aade9e63e37fac35f81a6eea4cdf9d2f1b83 by adamgeorge309
