### ISSUE TITLE
Src mac address of the arp package during emulation is 00:00:00:00:00:00

### ISSUE THREAD

**Issue by Jimmy01240397** [inet-framework/inet#854]
I'm trying to edit [emulation/pinger](/inet-framework/inet/tree/master/examples/emulation/pinger) and make it can ping another host on LAN.
But when I use tcpdump to capture traffic I saw the src mac address of the arp package is 00:00:00:00:00:00 and arp didn't response then ping failed. Why?

![image](https://user-images.githubusercontent.com/57281249/215602139-60ea1c46-3c86-42b5-83f2-c926894f3e9f.png)

**Comment by ZoltanBojthe** [comment]
For reproduce your bug, need more information:
Which inet version was used when the error occurred?
Could you attach your modified ned/ini files?

Your patch is unnecessary, the EthernetMacHeaderInserter and EthernetEncapsulation modules contain code for replace 00-00-00-00-00-00 source MacAddress to MacAddress of the sender interface.

**Comment by ZoltanBojthe** [comment]
Fixed in INET master.
