### ISSUE TITLE
Error in noise computation due to time resolution 

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#857]
I am working with an implementation of sound transducer, and I am using the Radio class as base.
I have modified the time resolution and I have found that the noise computation doesn't work if the time resolution is smaller than 1e-12.
The reason is this method "bool Radio::isListeningPossible() ", specifically here:
     const IListening *listening = receiver->createListening(this, now, now + 1E-12, position, position);

With resolutions smaller than 1e-12 the isotropic noise computation is infinite because now = now + 1E-12.

I have solved this problem with this code 

   double delta = 1E-12;
    double exponent = now.getScaleExp();
    if (exponent > -12)
        delta = std::pow(10.0, exponent);
    const IListening *listening = receiver->createListening(this, now, now + delta, position, position);

**Comment by aarizaq** [comment]
I think that this solution is more elegant
https://github.com/aarizaq/inetmanet-4.x/commit/15f58b95ae4cc10d0f3e541dfab4bd69d7c2c2c9

Also, Ieee802154UwbIrTransmitter::generateSyncPreamble uses 1E-12.

**Comment by levy** [comment]
Thank you for reporting this. The solution is not ideal but it's still better than it was before.
