### ISSUE TITLE
Missing Z3GateScheduleConfigurator for SAT-Solver-based Gate Schedule Configuration

### ISSUE THREAD

**Issue by PhilippComet** [inet-framework/inet#858]
Can anyone please give me a hint which installations are required or how to implement the Z3GateScheduleConfigurator in OMNeT++ to use the SAT-Solver-based Gate Schedule Configuration? I'm stuck at the following error message:

![grafik](https://user-images.githubusercontent.com/121798011/220203650-b6f39877-40dd-4249-bf02-16276524f8aa.png)

**Comment by levy** [comment]
You need to install the external libz3-dev or z3-devel package and enable the corresponding INET feature using the project properties page (right click on the project name).

**Comment by PhilippComet** [comment]
Thank you very much for your quick response and help.
