### ISSUE TITLE
Cannot change network namespace 

### ISSUE THREAD

**Issue by zhangteng0526** [inet-framework/inet#862]
I encountered the problem shown in the title when running the showcases/simulation example
After viewing readme, the above method adds the CAP_ SYS_ ADMIN privilege to opp_ run
So, I executed the following command
cd omnetpp-5.6.2/bin
sudo setcap cao_ sys_ admin+ep opp_ run_ release
sudo setcap cap_ sys_ admin+ep opp_ run_ dbg
But the problem has not been solved
What should I do?

**Comment by levy** [comment]
There's no showcases/simulation example in INET. Please provide a detailed step-by-step instruction how to reproduce the problem, otherwise I'm going to close as not reproducible. Thanks!

**Comment by ZoltanBojthe** [comment]
not reproducible.
