### ISSUE TITLE
 Network creation step fails with segmentation fault.

### ISSUE THREAD

**Issue by dekaio** [inet-framework/inet#863]
Debugger points to [MacForwardingTableConfigurator.cc]  file, in the extendConfiguration function, in the line interfacename = firstInterface->networkInterface->getInterfaceName(). 

The network consists of a TSN switch, a clock, and a modified standardHost. The error gets thrown at the switch. What could be the potential reason why an error is thrown in this particular line?
Please see the screenshot of the debug flow in the attachment.

![download](https://user-images.githubusercontent.com/47273651/223487791-2ec5aad1-118f-48db-8675-80a5ce5976ec.png)

**Comment by levy** [comment]
Please attach the NED and INI files that you were using when this problem occurred. Thanks!

**Comment by dekaio** [comment]
Hi, unfortunately, I am not allowed to post my complex NED and INI files.
However, the error is thrown when I connect the TSN switch to the ethernet port of a Simu5G UE.
Thanks.

**Comment by levy** [comment]
The issue creator replied the following:

    Hi, unfortunately, I am not allowed to post my complex NED and INI files.
    However, the error is thrown when I connect the TSN switch to the ethernet port of a Simu5G UE.
    Thanks.

I tried to reproduce this bug without the requested files but I could not, so I close this issue as not reproducible.
