### ISSUE TITLE
On Printing Packet Class Messages

### ISSUE THREAD

**Issue by zhangteng0526** [inet-framework/inet#866]
I sent a 'hello, world' message from the external real network to a node in the simulator through UdpSinkapp. I want to print the received message in some way. But I use pk ->str() to print out 12 B (UNKNOWN) BytesChunk, length=12 B, bytes={72, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100}. I want to implement the message I want to print through the member function printMessage of the PacketPrinter class. Is this way feasible? Do you have any better suggestions.At present, the difficulty I encounter is that I cannot force the message of Packet class to be converted into the message of cmessage class.Can you help me？

**Comment by levy** [comment]
This forum is an issue tracker, please ask questions on the mailing list instead!
