### ISSUE TITLE
Max Contention Window Decreases Throughput

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#87]
Throughput decreases when cwMaxData is set same value with cwMaxData. Using throughput example under wireless directory when 

cwMaxData:7
cwMinData:7

values are set measured throughput is 2.6 Mbps. However 

cwMaxData: Not Set (Default Value -1)
cwMinData: 7

are set throughput is measured 5.4 Mbps. Both tests are made with 1 AP and 1 wireless client. 

from: http://dev.omnetpp.org/bugs/view.php?id=685

**Comment by levy** [comment]
This bug is probably obsolete, because the 802.11 model was largely re-implemented since the bug was added. Also, the cwMaxData parameter no longer exists.
