### ISSUE TITLE
error: 'this' argument to member function 'setDestAddress' has type 'const inet::Ipv4Header', but function is not marked const

### ISSUE THREAD

**Issue by dekaio** [inet-framework/inet#870]
Hi,
I tried to change the destination IP address of a UDP packet in my custom module as follows.   
```
 Ipv4Address changedIpAddr("10.0.0.11");
 auto ipv4Header = packet->peekAtFront<Ipv4Header>()->setDestAddress(changedIpAddr);
```
However, I get the below compile time error.   
_error: 'this' argument to member function 'setDestAddress' has type 'const inet::Ipv4Header', but function is not marked const._   
Is this the expected behavior?   
Thanks.

**Comment by ZoltanBojthe** [comment]
The `packet->peekAtFront<Ipv4Header>()` returns a shared pointer to a const Ipv4Header.
For modify the packet content, use the `removeAtFront()` and `insertAtFront()` functions:
```
auto ipv4Header = packet->removeAtFront<Ipv4Header>();
ipv4Header->setDestAddress(changedIpAddr);
packet->insertAtFront(ipv4Header);
```
