### ISSUE TITLE
[ThreeColorMeter] Feature Req. for displaying separate token statistics

### ISSUE THREAD

**Issue by olfline** [inet-framework/inet#872]
Hello there,

The DualThreeColorMeter (and all other ThreeColorMeter/Classifier) only display statistics for all tokens in summary (green and yellow). I want to display the Tokens per color. 

**Feature Request:**
Implementation of a separate statistic for green and yellow tokens respectively (numTokensGreen, numTokensYellow).

Would it be much effort to do so?

Kind regards

**Comment by levy** [comment]
I think the %n directive prints the number of tokens for all buckets. The DualRateTreeColorMeter looks like this by default:

![image](https://user-images.githubusercontent.com/112461/226302459-e3f80ede-d20f-4ff4-8168-21902e8f8acc.png)

**Comment by olfline** [comment]
Thanks for the fast answer!

To be more specific:
The ThreeColorMeter has two buckets with tokens: green and yellow ones.
To examine the used tokens over the time after a simulation run, I want to display the used green tokens in a graph and  the used yellow tokens in another graph. 
At the moment, the two buckets and their token capacity are thrown together into one parameter "numTokens":

![grafik](https://user-images.githubusercontent.com/50140648/226364382-febb7e56-ae40-41aa-8dfa-929631ce6cf4.png)

So I suggest to implement two more statistic parameters: "numGreenTokens" and "numYellowTokens". And as far as I could understand, two more signal parameters are needed.

I hope, it is now clearer what I intend.
Kind regards!

**Comment by levy** [comment]
Thanks for the clarification. This makes sense, though the names may need to be different, because color names are parameters.

**Comment by levy** [comment]
The feature request has been implemented in INET master.
