### ISSUE TITLE
questions about macforwardingconfigurator

### ISSUE THREAD

**Issue by Jiacheng188** [inet-framework/inet#880]
Hello, when i build an ethernet network with 128 hosts and use the _macforwardingconfigurator_ to config all the MacForwarding tables , I find that there are only 127 items in the tables. All the hosts are connected to each other with the help of ethernet switches.
Then I studied the code in the _macforwardingconfigurator_ .
I find that in  the method:
```MacForwardingTableConfigurator::extendConfiguration(Node *destinationNode, Interface *destinationInterface, MacAddress macAddress)```
when the first host and the first non-loopback interface is treated as the destination and destInterface,  it only creates the configuration for all switches but not initialize it for them, just as indicated in the figure below.
 
![1680832323788](https://user-images.githubusercontent.com/78731659/230524572-5a351cde-1c0f-4b3d-9325-a985a43a0977.png)
Then I changed the code as follows and the number of  items in all switches is 128.
![1680832685064](https://user-images.githubusercontent.com/78731659/230525218-e8033092-e331-4a3b-8f3e-7e1a69d69c28.png)
I wonder if i have done the right thing ?

**Comment by levy** [comment]
Thanks for reporting! Could you please verify if this 4b51da04be1e99997f988b69b5f6a040204dc42d patch solves your issue?

**Comment by Jiacheng188** [comment]
Thanks for solving the problem. It works fine for me!

**Comment by lukefadedaway** [comment]
This bug is still in INET version: 4.5.2

Apparently this fix wasn't correctly pushed to the releases.  

To reproduce this bug, use these two files: 
(Configuration A-to-B will run without the bug because B is not the first Device in the ini file. B-to-A will show the bug because A is the first device and therefore can't bee addressed)
bugtest.ini :
```
[A-to-B]
network = bugtest

*.*.eth[*].bitrate = 1Gbps

*.A.numApps = 1
*.A.app[0].typename = "UdpSourceApp"
*.A.app[0].display-name = "A-B"
*.A.app[0].io.destAddress = "B"
*.A.app[0].io.destPort = 1000 
*.A.app[*].source.packetNameFormat = "%M-%m-%c"
*.A.app[0].source.packetLength = 1200B 
*.A.app[0].source.productionInterval = 490000ns  

# server applications
*.B.numApps = 1
*.B.app[*].typename = "UdpSinkApp"
*.B.app[0].display-name = "A-B"
*.B.app[0].io.localPort = 1000 

[B-to-A]
network = bugtest

*.*.eth[*].bitrate = 1Gbps

*.B.numApps = 1
*.B.app[0].typename = "UdpSourceApp"
*.B.app[0].display-name = "B-A"
*.B.app[0].io.destAddress = "A"
*.B.app[0].io.destPort = 1000 
*.B.app[*].source.packetNameFormat = "%M-%m-%c"
*.B.app[0].source.packetLength = 1200B 
*.B.app[0].source.productionInterval = 490000ns  

# server applications
*.A.numApps = 1
*.A.app[*].typename = "UdpSinkApp"
*.A.app[0].display-name = "B-A"
*.A.app[0].io.localPort = 1000 
```

bugtest.ned :
```
import inet.networks.base.TsnNetworkBase;
import inet.node.ethernet.EthernetLink;
import inet.node.tsn.TsnDevice;
import inet.node.tsn.TsnSwitch;

network bugtest extends TsnNetworkBase
{
    submodules:

        switch: TsnSwitch {
            @display("p=650,400");
        }
        A: TsnDevice {
            @display("p=496,401");
        }
        B: TsnDevice {
            @display("p=650,254");
        }
        C: TsnDevice {
            @display("p=818,401");
        }

    connections:
        switch.ethg++ <--> EthernetLink {  delay = 200ns; } <--> A.ethg++;
        switch.ethg++ <--> EthernetLink {  delay = 200ns; } <--> B.ethg++;
        switch.ethg++ <--> EthernetLink {  delay = 200ns; } <--> C.ethg++;
}
```
Packet A-to-B going the correct path:
<img width="372" alt="A-to-B Packet" src="https://github.com/inet-framework/inet/assets/30881021/ff180f1f-a192-4a70-bc76-b501534ebfda">

Packet B-to-A not being able to be correctly routed:

<img width="364" alt="B-to-A Packet" src="https://github.com/inet-framework/inet/assets/30881021/315d6bb4-62cf-4f29-9581-2a26a9541e74">
