### ISSUE TITLE
how to rebuild precompiled header

### ISSUE THREAD

**Issue by aiying299** [inet-framework/inet#885]
fatal error: file '/usr/include/asm-generic/errno-base.h' has been modified since the precompiled header 'inet/common/precompiled_release.h.pch' was built: mtime changed
note: please rebuild precompiled header 'inet/common/precompiled_release.h.pch'

**Comment by levy** [comment]
Precompiled headers are managed automatically. If you wish to submit a bug report then please include the exact reproduction steps.
