### ISSUE TITLE
GateScheduleVisualizer shows empty schedule

### ISSUE THREAD

**Issue by adamgeorge309** [inet-framework/inet#887]
The GateScheduleVisualizer sometimes shows empty shedules:

![image](https://github.com/inet-framework/inet/assets/17473608/fe7c06e5-d8dc-49ee-af37-ebdbb320d264)

When the simulation is run for a bit, the schedules are displayed, then disappear again.

**Comment by levy** [comment]
I cannot reproduce this bug, please provide exact steps!

**Comment by adamgeorge309** [comment]
works on master
