### ISSUE TITLE
On the inconsistency between forward and reverse routing in AODV networks

### ISSUE THREAD

**Issue by zhangteng0526** [inet-framework/inet#889]
In the example/aodv provided by INET, I set up a scenario. Here is my ini code
[Config Test]
description = routing without mobility and 64
sim-time-limit = 100s
*.numHosts = 64
*.host[*].wlan[*].radio.transmitter.communicationRange = 3000m
*.host[0].app[0].destAddr = "host[1](ipv4)"
**.mobility.constraintAreaMaxX = 10000m
**.mobility.constraintAreaMaxY = 10000m
However, the route from host0 to host1 is inconsistent with the route from host1 to host0. The intermediate nodes it passes through are different. May I ask what is the reason for this?

**Comment by zhangteng0526** [comment]
I found that as long as metric ≥ 3, there will be inconsistencies between forward and reverse routing. However, this situation does not exist in AODV. So where exactly is the problem

**Comment by levy** [comment]
This forum is an issue tracking tool. Please use the mailing list for asking questions.
