### ISSUE TITLE
Error in iteration of the list of routing table

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#89]
File: BGPFSM.cc
Function: Established::entry()

for (int i=1; i<IPRoutingTable->getNumRoutes(); i++)
    {...}

why i start from 1

also in 
File: OSPFRouting.cc
Function: OSPFRouting::checkExternalRoute(const IPv4Address &route)

for (unsigned long i=0; i < ospfRouter->getASExternalLSACount(); i++)
    {...}

why i start from 1

from: http://dev.omnetpp.org/bugs/view.php?id=645

**Comment by levy** [comment]
These bugs have been fixed with the recent changes in INET 4.1 done by @ManiAm
