### ISSUE TITLE
Credit-based Shaper faulty Calculation of Credit

### ISSUE THREAD

**Issue by Clunphumb** [inet-framework/inet#890]
Hello everyone,

currently I'm trying to simulate a network using the Showcase "cbsandtas". While trying to verify that it is working correctly, I noticed, that the usage of credit per packet isn't calculated correctly or so it seems.

I set packetLength = 1000B - 58B and the idleSlope = 10Mbps. When running the simulation, I took a look at the packet while it is "on the wire" which revealed the expected packet size of 1000B. Right before going into the Queue, the packet has a size of 992B, which seems to be correct, as it should be less than on the wire. 

When the packet has traversed the CBS credit is reduced to -7286.4 cr. This value can be used to determine the packet length that was used in the cbs: credit = packet_length/total_bandwidth * sendSlope => packet_length = credit*total_bandwidth / sendSlope, where sendslope = idleSlope - total_bandwidth. packet_length = -7286.4/8 * 100Mbps / 90Mps = 1012B.

According to IEEE 802.1Q the CBS should use the actual bandwidth consumed for all calculations (idleSlope, SendSlope), which would include the packet length. As 1012B is higher than the anticipated 1000B, I would think that the CBS currently uses less bandwidth than what should actually be possible.

Maybe I am missing something and there is actually another 12B in headers somewhere, but I can't find any point, where a packet exceeds 1000B.

For simulations this (faulty?) behavior can be avoided easily by subtracting another 12B from the packet size for now, but it would be nice of course, if anyone could provide some insight on this issue or would be able to fix it.

Thank you very much!
[omnetpp.ini.txt](https://github.com/inet-framework/inet/files/11530799/omnetpp.ini.txt)

**Comment by levy** [comment]
The current implementation decreases the number of credits with sendSlope rate for the total transmission duration of the packet plus its IFG. The following calculation shows the number of credits spent for a single packet (1000 * 8 + 96) / 100E-6 * 90E-6 = 7286.4, it is exactly the value you are seeing. The extra 12 B (96 bits) is the IFG period, which IIRC also has to be included.
