### ISSUE TITLE
Simulation stops at arbitrary points in time

### ISSUE THREAD

**Issue by PhilippComet** [inet-framework/inet#894]
Hello community,

I know this is probably not an INET specific issue, but my simulations (50s simtime) stop and freeze at arbitrary points in time. This problem occurs in about 2 out of 3 runs and is unfortunately a big hindrance to workflow. Two subsequent simulations are practically not possible.

Do you have any ideas what this could be related to? Is it perhaps a cache or RAM problem?
Let me know, if I can provide some more information

Edit: When I force the simulation to quit I get following error message:
![grafik](https://github.com/inet-framework/inet/assets/121798011/10c2bd7d-a650-475c-ab6e-09474d6d620f)

**Comment by levy** [comment]
Does the simulation perhaps eat all RAM? Does it occur under both Cmdenv and Qtenv, debug and release mode? What platform are you using? Can you send the simulation please?

**Comment by PhilippComet** [comment]
Hi Levente, thanks the response. 
I use Windows 11 and could already improve the problem with changing the PC with more RAM installed. I seems that now a very small amount of simulations have to be restarted due to freezing during execution in the Qtenv GUI. After restarting the simulation that crashed before, the problem is mostly always gone. I can live with that. 
The weird thing about this, is that the .exe file of the simulation is actually not listed in the Task Manager as using high amount of RAM.

**Comment by levy** [comment]
This issue cannot be reproduced, so we can't do anything with it.
