### ISSUE TITLE
Randomized App Sending Behaviour

### ISSUE THREAD

**Issue by PhilippComet** [inet-framework/inet#896]
Dear INET Team,

I would like to define my sending app to choose its initial sending offset randomly between 0s and 0.1s everytime I restart the simulation. But I discovered that everytime I restart the simulation the value remains the same. The interval is correct, but is doesn't change when I close Qtenv and restart the run. Do you have an idea, what I did wrong here?

The related code line in the .ini file looks like this:
```
*.ES1.app[1].source.initialProductionOffset = uniform(0s,0.1s) 	# randomized AVB initial offset
```
![grafik](https://github.com/inet-framework/inet/assets/121798011/2fcc84c0-8069-4e66-953b-3db121084f23)

**Comment by torokati44** [comment]
The PRNG seeds are fixed, so naturally you will get the same "random" values in every run. This is not a bug, it's a feature. To change the random numbers, you can use the `seed-set` configuration variable, for example.

See also:
https://doc.omnetpp.org/omnetpp/manual/#sec:sim-lib:random-number-generators
https://doc.omnetpp.org/omnetpp/manual/#sec:config-sim:repeating-runs-with-different-seeds

**Comment by PhilippComet** [comment]
Thank you for the fast response. Wow, this is a very interesting feature. 
For running 100 simulations with different values I specified `repeat = 100` and change in an increasing manner the `-r <run_number>` when starting the simulation from the console.

**Comment by torokati44** [comment]
Great, that is perhaps the best way to produce different trajectories for a given configuration.
