### ISSUE TITLE
Reproducing the example in INET showcase.

### ISSUE THREAD

**Issue by ccsssyyy** [inet-framework/inet#899]
I am not sure how to classify the problem. So I have had sent the same issue in omnetpp github repo.

Platform

OMNeT++ version: 6.0 , Build ID 220413-71d8fab425
INET version: 4.4.0
OS: Windows 11 , VMware 16.1.0 build-17198959 , Ubuntu-20.04.4-desktop-amd64
Python version : 3.8
Describe the bug
Couldnt reproduce the example described at : https://inet.omnetpp.org/docs/showcases/tsn/timesynchronization/clockdrift/doc/index.html
Example: Constant Clock Drift Rate
I want to reproduce the example shown figure -- Clock drift - Constant drift rate, but failed.

To Reproduce
Run the showcase in INET -> showcases -> tsn -> timesynchronization -> clockdrift -> omnetpp.ini
Select : ConstantClockDriftRate -- Clocks with constant drift rate diverge over time. And use FAST RUN to speed up the process.
open ConstantClockDriftRate-#0.vec in results folder. Save the corresponding anf file.
Select Browse Data -> Vectors
Plot using Line Chart with all the three timeChanged:vector
Applying Linear Trend operation with argument -1 to reproduce the figure.
![1](https://github.com/inet-framework/inet/assets/132052625/af26ccd0-8e38-4d05-8360-829f8dc1055a)
![2](https://github.com/inet-framework/inet/assets/132052625/cb419544-1cef-4bac-a63d-b8e5a05bcf7d)
![3](https://github.com/inet-framework/inet/assets/132052625/d9e76684-8a4a-4798-9348-2baf0cf0e81e)
![4](https://github.com/inet-framework/inet/assets/132052625/d58a86a6-4f93-42c1-9129-562dae34d294)

**Comment by avarga** [comment]
The actual error is what's displayed on the chart: `'DataFrame' object has no attribute append`. Sounds like a problem with the Pandas version.

Have you tried upgrading to OMNeT++ 6.0.1? The changelog says: "On Windows, the bundled Python was upgraded to 3.10, fixing several issues in NumPy and Matplotlib."

**Comment by ccsssyyy** [comment]
OMNeT++ version: 6.0.1
INET version: 4.4.0
OS: Windows 11 , VMware 16.1.0 build-17198959 , Ubuntu-22.04-desktop-amd64
Python version : 3.10.6

OMNeT++ version: 6.0.1
INET version: 4.5.0
OS: Windows 11 , VMware 16.1.0 build-17198959 , Ubuntu-22.04-desktop-amd64
Python version : 3.10.6

I have tested with these two environment. 
Both are the same mistake shown below.
![1](https://github.com/inet-framework/inet/assets/132052625/c0acf54a-f913-4da8-bb99-8bf90bdcd4f8)

**Comment by ccsssyyy** [comment]
The pandas version used in Ubuntu 22.04 is pandas 2.0.3

**Comment by ccsssyyy** [comment]
Yes!!! I had solved the problem by down-grade the pandas version to 1.5.0.
![2](https://github.com/inet-framework/inet/assets/132052625/13a41efb-1701-4e32-8a0a-8c17f3dbfd33)

**Comment by levy** [comment]
Please note that the showcase documentation is for INET version 4.5 as stated in the goals section.
