### ISSUE TITLE
Memory leak in DSR protocol

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#90]
the link layer notification of lost frame can provoke a memory leak

solution
https://github.com/aarizaq/inetmanet-2.0/commit/c70417a597cd845239b120dc8c5bdf708b602cd1 

from: http://dev.omnetpp.org/bugs/view.php?id=635

**Comment by levy** [comment]
There's no DSR routing protocol in INET any more. It was part of the extras folder taken over from INETMANET, but it's no longer present.
