### ISSUE TITLE
undisposed object: receptionTimer

### ISSUE THREAD

**Issue by fysch** [inet-framework/inet#906]
I've got a bunch of these in the logs of my recent simulations:
`undisposed object: (omnetpp::cMessage) World.node[3025].wlan[0].radio.receptionTimer -- check module destructor`

I suspect in the `Radio.cc` destructor, a `cancelAndDelete(receptionTimer);` is missing?

**Comment by levy** [comment]
Unfortunately there are multiple reception timers, not just one. I assume the simulation created and destroyed Radio modules dynamically, otherwise the reception timers are deleted by the FES automatically when the simulation terminates. Do you still have the example to reproduce this?

**Comment by levy** [comment]
This has been fixed in the master branch.
