### ISSUE TITLE
Contributor License Agreement

### ISSUE THREAD

**Issue by tkitc** [inet-framework/inet#908]
If someone wants to contribute to the inet project, does he need to sign a Contributor License Agreement before submitting a pull request? In that case, is the agreement form available anywhere in the repository?

**Comment by tabgab** [comment]
INET is licensed under LGPL (
https://github.com/inet-framework/inet/blob/master/LICENSE.md) If you
contribute to it, it will also be licensed under the same license if the
pull request is accepted.
There is no paper to be signed, though, if you contribute code to INET, you
accept these license terms to be valid to the contributed code as well.

**Comment by tkitc** [comment]
Thank you very much for the response, @tabgab!
