### ISSUE TITLE
Auto route metric 'delay' causes empty chunk in L3NetworkConfiguratorBase.cc

### ISSUE THREAD

**Issue by Zenith-Xiang** [inet-framework/inet#913]
When I change the autoroute metric from 'errorRate' to 'delay' in **Wireless04 of the tutorial ini file** ([https://github.com/inet-framework/inet/blob/master/tutorials/wireless/omnetpp.ini](url)), I encounter an error 'Returning an empty chunk is not allowed'.

I checked the code in L3NetworkConfiguratorBase.cc and found that there is only an empty packet in the 'delay' part (Line 386).
But in the 'errorRate' part, the new packet is inserted with some bytes and tags (Line 408-414).

After I copying those codes from 'errorRate' part to 'delay' part, the 'empty chunk' error no longer occurs.
Is it reasonable to do so?

**Comment by levy** [comment]
Thanks for the bug report! Yes, the packet length doesn't matter because the 'delay' metric calculates with the signal propagation time.
