### ISSUE TITLE
Use the OpenFlow module for data transfer between 2 standardhosts

### ISSUE THREAD

**Issue by slblbwl** [inet-framework/inet#918]
I downloaded the openflow module and now I want to use the module for communication between two standards, what do I do?
such as
![image](https://github.com/inet-framework/inet/assets/143598243/ccff163d-f24d-492a-aaff-a3e5ca80c4b2)
How do I set up my ini file?？Thank you very much for your help！
my ned file

package openflow;

import inet.common.misc.ThruputMeteringChannel;
import inet.networklayer.configurator.ipv4.IPv4NetworkConfigurator;
import inet.node.ethernet.EtherSwitch;
import inet.node.inet.StandardHost;
import openflow.openflow.controller.Open_Flow_Controller;
import openflow.openflow.switch.Open_Flow_Switch;
import openflow.utility.OpenFlowGraphAnalyzer;
import openflow.utility.StaticSpanningTree;

network openflowmod
{
    parameters:
        int numClients @display("bgb=768,465") = default(1);

        @display("bgb=925,638");
    types:
        channel ethernetline extends ThruputMeteringChannel
        {
            delay = 1us;
            datarate = 100Mbps;
            thruputDisplayFormat = "u";
        }

    submodules:
        spanningTree: StaticSpanningTree {
            @display("p=61,108");
        }
        openflowGraphAnalyzer: OpenFlowGraphAnalyzer {
            @display("p=61,39");
        }

        clientG1[numClients]: StandardHost {
            @display("p=123,346");
        }
        clientG2[numClients]: StandardHost {
            @display("p=848,354");
        }
        configurator: IPv4NetworkConfigurator {
            parameters:
                @display("p=61,172");
        }

        open_flow_switch1: Open_Flow_Switch {
            @display("p=278,345");
        }
        open_flow_switch4: Open_Flow_Switch {
            @display("p=698,353");
        }

        open_flow_controller1: Open_Flow_Controller {
            @display("p=455.81998,141.23999");
        }
    connections allowunconnected:
        for i=0..(numClients)-1 {
            clientG1[i].ethg++ <--> ethernetline <--> open_flow_switch1.gateDataPlane++;
        }
        open_flow_switch1.gateDataPlane++ <--> ethernetline <--> open_flow_switch4.gateDataPlane++;
        for i=0..(numClients)-1 {
            clientG2[i].ethg++ <--> ethernetline <--> open_flow_switch4.gateDataPlane++;
        }
        open_flow_switch1.gateControlPlane++ <--> ethernetline <--> open_flow_controller1.ethg++;
        open_flow_switch4.gateControlPlane++ <--> ethernetline <--> open_flow_controller1.ethg++;

}

**Comment by levy** [comment]
This is the INET Framework issue tracker. It's not a forum to ask question.
