### ISSUE TITLE
802.1as

### ISSUE THREAD

**Issue by jakstevns** [inet-framework/inet#920]
why not  using gptp->setCorrectionField(correctionField + peerDelay + sentTimeSyncSync - receivedTimeSync) but  gptp->setCorrectionField(CLOCKTIME_ZERO) in 802.1as(Gptp.cc)

**Comment by levy** [comment]
I have no idea. It seems like that the expression should be used instead of 0 but it was commented out for a reason I guess. Needs more investigation.

**Comment by haug-den-lucas** [comment]
I would be highly interested in this as well.
If someone can find out why this change was made I wouldn't mind fixing it myself.

**Comment by jakstevns** [comment]
> I have no idea. It seems like that the expression should be used instead of 0 but it was commented out for a reason I guess. Needs more investigation.
Now we have three time-aware systems(i-1 ,i ,i+1).I think the newtime should equal the slave_port (i) receiving time of sync  from last master_port(i-1)，but you using the newtime is current master_port (i) send sync to next slve_port (i+1）time of sync，and PreciseOriginTimestamp  if is equal to the time grandMaster  takes to send Follow_up, instead of being equal to the time it takes to send Follow_up from the previous time-sensitive systemthe , this why the correction equal zero .

**Comment by jakstevns** [comment]
When I was using the result analysis template of GptpAndTasShowcase.anf, I found some problems , indicating the lack of optimparallel, which I could not solve at present.
The software version is 6.0.2,the inet framework was recently updated on github
![8a1304afb7c3ea22b9a92886ac0929c](https://github.com/inet-framework/inet/assets/148611613/e001f157-201b-4cda-bb06-7912f49d1c56)

**Comment by levy** [comment]
optimparallel is a Python library. You can install it with the usual `pip3 install optimparallel` command.

**Comment by ZoltanBojthe** [comment]
fixed in master at https://github.com/inet-framework/inet/commit/7fccdb23ba3040bcb025aa5aeca8202eed608978
