### ISSUE TITLE
Ieee80211ScalarRadioMedium not taking any pathloss models 

### ISSUE THREAD

**Issue by arahman33** [inet-framework/inet#925]
I am using Ieee80211ScalarRadioMedium with Adhoc hosts and I try to set the pathloss model that I want to use through 

*.radioMedium.pathloss.typename = "SuiPathLoss"

I have also tried others like RicianFading, TwoRayGround etc.  but there seem to be no difference. I went into the .cc files and added EV_INFO in the initialization functions but none of them showed up during the initialization. This made me believe I am probably adding the path loss model incorrectly? I even tried to misspell the pathloss (like writing SuoPathLoss instead of SuiPathLoss) to see if it threw me an error but I did not get any. I finally found out that the Pathloss model used is FreeSpacePathLoss. But how to override this?

I have set the opMode to be "ac". Is this why none of the pathloss models are working?

*.*.wlan[0].typename = "Ieee80211Interface"
*.*.wlan[0].mgmt.typename = "Ieee80211MgmtAdhoc"
*.*.wlan[0].radio.typename = "Ieee80211ScalarRadio"
*.*.wlan[0].radioMedium.typename = "Ieee80211ScalarRadioMedium"
**.opMode = "ac"

**Comment by levy** [comment]
Replace pathloss with pathLoss :-)

**Comment by arahman33** [comment]
I changed it to *.*.wlan[0].radioMedium.pathLoss.typename = "RicianFading"
but still I am getting 

Initialized (inet::physicallayer::RadioMedium)radioMedium id=5, propagation = { ConstantSpeedPropagation, ignoreMovementDuringTransmission = 1, ignoreMovementDuringPropagation = 1, ignoreMovementDuringReception = 1, propagationSpeed = 2.99792e+08 mps }, **pathLoss = { FreeSpacePathLoss, alpha = 2, systemLoss = 1 }**, analogModel = { ScalarAnalogModel }, obstacleLoss = <nullptr>, backgroundNoise = { IsotropicScalarBackgroundNoise, power = 0.01 pW, bandwidth = 22 MHz }, mediumLimitCache = { RadioMediumLimits, minConstraintArea = (0, 0, 0) m, maxConstraintArea = (0, 0, 0) m, maxSpeed = 0 mps, maxTransmissionPower = 20 mW, minInterferencePower = 0.01 pW, minReceptionPower = 3.16228 pW, maxAntennaGain = 1, minInterferenceTime = 0.000000000001, maxTransmissionDuration = 0.01, maxCommunicationRange = 790.523 m, maxInterferenceRange = 14057.7 m },

**Comment by levy** [comment]
No, right now you cannot set the antenna height on a per antenna basis.
