### ISSUE TITLE
How to calcutae the receiving power of a packet?

### ISSUE THREAD

**Issue by Ambica2022** [inet-framework/inet#930]
Hi,

I am unable to locate the code related to "calculation of receivng power of each packet".
Any clue is appreciated.Thanks in advance.

Regards,
Ambica

**Comment by n-jay** [comment]
Hi @Ambica2022, are you referring to RSSI value from a transmission?

Also in the future, I think it would be ideal to use the [discussion section](https://github.com/inet-framework/inet/discussions) for questions such as this.

**Comment by Ambica2022** [comment]
@n-jay , yes....I mean RSSI RSSI value in a wireless transmission expressed in dBm.
Thank you....started a new discussion thread......So closing here
