### ISSUE TITLE
Nodes do not take Z coordinates?

### ISSUE THREAD

**Issue by arahman33** [inet-framework/inet#937]
From the code in "inet/common/geometry/common/Coord.h". I can see there are codes for 2D as well as 3D distance calculation including x, y, z coordinates. But I am not able to add the Z coordinate in the .NED file.

 when I add @display("p=131.53847,86.15385, 100"), i get an error. 

How else can I add the Z coordinates? PS. the nodes are not mobile.

**Comment by n-jay** [comment]
Hi @arahman33 

> when I add @display("p=131.53847,86.15385, 100"), i get an error.

The` @display ` keyword is used for rendering the module when running simulations in _graphical environments_ as per the OMNET++ simulation [manual](https://doc.omnetpp.org/omnetpp/manual/#sec:ned-lang:warmup:the-simple-modules).
I think the Z-axis coordinates could be set via the .INI file. Will have to refer to the docs and showcases to be certain.

Also, I believe the project maintainers recommend using the issues tab for feature requests/bugs, and using the [discussion tab](https://github.com/inet-framework/inet/discussions) for questions such as this.

**Comment by rhornig** [comment]
The `displayString` mechanism is designed to be used in the 2D Qt graphical environment so it does not support Z coodinates. Also, OMNeT++ does not now anything about node positions and mobility. That is the area of the user model. INET has 3D mobility models (and it has a 3D visualization too using OpenSceneGraph, but that has nothing to do with display strings)

Indeed, for questions it is recommended to use the main opmnetpp/omnetpp repos's discussion tab (note: you cannot create new discussions for the inet-framework/inet repo. you should use the main omnetpp repo even if the question is INET related)
