### ISSUE TITLE
U/L bit is ignored in the MACAddress class

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#94]
The MACAddress class use to have the first bit of the first byte as the multicast/unicast bit and now it's correctly set as the last bit (less significant) of the first byte.

The problem is that, as far as I know, the universal/local bit (U/L bit) is omitted and never used. It doesn't even have a function to check it, like isLocal() or something similar (as isBroadcast() or isMulticast()).

However, the real problem is that MAC addresses are assigned by default in the class and they start with 0x0A, and that type of addresses have the U/L bit (the second less significant of the first byte) set to 1, that is, they are meant to be local, but they are not.

This causes confusion and problems if you are working with local MAC addresses (in my case), so the first byte of auto assignment should be something ending in 0, 4, 8 or C in order to have both bits (multicast and local) set to 0.
Additional Information  I might be wrong or confused with this issue, since I'm no expert, but this is how it works and how it should work as far as I know. Thank you.

from: http://dev.omnetpp.org/bugs/view.php?id=630

**Comment by ZoltanBojthe** [comment]
fixed.
