### ISSUE TITLE
Compilation error in linux

### ISSUE THREAD

**Issue by aarizaq** [inet-framework/inet#945]
I have this error in Kubuntu 22.04

inet/visualizer/base/RoutingTableVisualizerBase.cc:288:17: error: use of class template 'vector' requires template arguments
    "return std::vector(multicastGroups.begin(), multicastGroups.end());"

Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

This is my fix
https://github.com/aarizaq/inetmanet-4.x/commit/cc307ab23a02bab75118cd5636baf442c36193bf

**Comment by rhornig** [comment]
what inet version? because master does not even have that line in that file.

**Comment by levy** [comment]
Thank you for reporting! This has been just fixed in the master branch.
