### ISSUE TITLE
Does not get Received packets in Statistic MAC protocols

### ISSUE THREAD

**Issue by abdulafroz04** [inet-framework/inet#960]
In the sensor networks of wireless folder , The omnetpp.ini file contains Statistic BMAC, Statistic XMAC, Statistic LMAC. When the simulation is being done, the received packets are zero for each scenario. Even after turning the vector recording on. 
![image](https://github.com/inet-framework/inet/assets/109869836/537f8dfb-c35d-4905-9046-2a9655d77ae0)
![image](https://github.com/inet-framework/inet/assets/109869836/fe791246-5399-4c65-b3d2-1db001781c29)

while using LMAC scenario there is the below issue
![image](https://github.com/inet-framework/inet/assets/109869836/5a10d9d9-8b4c-4dc3-800c-9485604ca76a)

Need resole as soon as possible

**Comment by adamgeorge309** [comment]
The StatisticLMac configuration is a parameter study, and with some values of slotDuration, this error occurs. However, most simulation runs don't lead to error.

**Comment by abdulafroz04** [comment]
Hi,

I'm unable to get the number of packets received vs slot duration plot for
all the protocols (BMAC, LMAC, XMAC), using the sensornetwork.anf file. Can
you help me with this?

Thank & regards
MD Abdul Afroz

**Comment by adamgeorge309** [comment]
The .anf file works with the latest INET version (4.5.4). Make sure to run all the simulations in the parameter study to generate the results.
