### ISSUE TITLE
Issues about doParsimPacking() and doParsimUnpacking() for TcpOption in TcpHeader_m.h

### ISSUE THREAD

**Issue by kalsasdf** [inet-framework/inet#961]
Issue Description:

In the TcpHeader_m.h file, there exists an inconsistency regarding the definition of the doParsimPacking() and doParsimUnpacking() functions for the TcpOption class, which mismatches the way TcpOption is used in the TcpHeader class.

The issue arises from the fact that the doParsimPacking() and doParsimUnpacking() functions expect TcpOption& as parameters, while in the TcpHeader class, TcpOption objects are defined as a two-level pointer, TcpOption * *headerOption = nullptr.

Consequently, when dereferencing in the doParsimArrayPacking() function in TcpHeader_m.cc, 
![1710916650656](https://github.com/inet-framework/inet/assets/31431263/d6e4f168-856b-4f85-930b-8083169103f6)

the TcpOption object cannot locate the correct doParsimPacking() and doParsimUnpacking() functions, resulting in the error "Parsim error: No doParsimPacking() function for type inet::tcp::TcpOption *".
![1710916696935](https://github.com/inet-framework/inet/assets/31431263/2ab91cb8-0d51-45c4-b221-f1085e54c092)

We propose an improvement method as illustrated below. 
![1710916753579](https://github.com/inet-framework/inet/assets/31431263/54cdb5ba-d91d-4155-9b0f-ba8a0526053b) in TcpHeader::parsimPack(omnetpp::cCommBuffer *b)
![1710916813693](https://github.com/inet-framework/inet/assets/31431263/1be81b00-bdac-4e48-9742-14a4fd3d2e37)
 in TcpHeader::parsimUnpack(omnetpp::cCommBuffer *b)

However, the issue is that TcpHeader_m.cc and TcpHeader_m.h are generated by TcpHeader.msg and would be cleared during make clean. As a result, our modifications will also be wiped out. Moreover, TcpHeader.msg does not directly relate to the doParsimPacking() and doParsimUnpacking() functions, making it impossible for us to amend TcpHeader.msg to generate these functions correctly.

Therefore, we suggest submitting this issue to the official INET for further enhancement.

**Comment by kalsasdf** [comment]
Supplementary: 
The above method enables the normal packing and unpacking of the TcpOption field. However, further testing revealed that this modification affects the subsequent fields' ability to pack and unpack correctly, like EthernetPadding in SYN. Therefore, we switched to the following approach, which effectively bypasses the inline packing and unpacking functions (doParsimPacking() and doParsimUnpacking()) of TcpOption. Instead, we directly call the parsimPack and parsimUnpack functions within the TcpOption class.
 
![1711866010254](https://github.com/inet-framework/inet/assets/31431263/d50db531-fea7-4db5-9c4a-2c04dfd6063f)
 in TcpHeader::parsimPack(omnetpp::cCommBuffer *b)
![1711866021708](https://github.com/inet-framework/inet/assets/31431263/ae7de51c-cb3d-4018-9210-d6e8c1af10bc)
 in TcpHeader::parsimUnpack(omnetpp::cCommBuffer *b)

**Comment by ZoltanBojthe** [comment]
Fixed in inet master (for INET 4.6)
