### ISSUE TITLE
GPSR does not work properly when using 2 source nodes send simultaneously

### ISSUE THREAD

**Issue by maicuongtho** [inet-framework/inet#966]
![gpsr](https://github.com/inet-framework/inet/assets/17454951/9f861463-23a2-4a3d-bae8-91391530deb3)

If I just use only one U1, or U2 it works OK, (test on StationaryMobility config)

-- -------- this is my INI file 

```
[General]
network = KhaoSatGPSR.MangMoPhong
sim-time-limit = 180s			 
repeat = 1						 
num-rngs = 3
#abstract-config = true (requires omnet 6)

**.mobility.rng-0 = 1
**.wlan[*].mac.rng-0 = 2

**.wlan[*].radio.typename = "Ieee80211ScalarRadio"
**.wlan[*].radio.bandName = "2.4 GHz"   #5 GHz
**.opMode = "g(mixed)"
**.wlan[*].bitrate = 2Mbps
**.wlan[*].radio.transmitter.power =9dBm

#**.wlan[*].radio.transmitter.power =3dBm (=1.995mW)   #3dBm-> com range =250m
#**.wlan[*].radio.transmitter.power =9dBm (=7.943mW)  #9dBm-> com range =500m

*.radioMedium.pathLoss.typename = "FreeSpacePathLoss"	


#*.visualizer.*.dataLinkVisualizer.displayLinks = true
*.visualizer.*.networkRouteVisualizer.displayRoutes = true
*.visualizer.*.networkRouteVisualizer[0].packetFilter = "UDP*"

*.visualizer.*.infoVisualizer.modules = "*.*.app[0]"
*.visualizer.*.infoVisualizer.format = "%t"
*.visualizer.*.infoVisualizer.placementHint = "topCenter"


*.U1.numApps = 1
*.U1.app[0].typename = "UdpBasicApp"
*.U1.app[0].destAddresses = "GCS"
*.U1.app[0].destPort = 1000
*.U1.app[0].sendInterval = 1s
*.U1.app[0].startTime = 1s
*.U1.app[0].messageLength = 512Byte 
*.U1.app[0].packetName = "UDPdata"

#
*.U2.numApps = 1
*.U2.app[0].typename = "UdpBasicApp"
*.U2.app[0].destAddresses = "GCS"
*.U2.app[0].destPort = 1000
*.U2.app[0].sendInterval = 1s
*.U2.app[0].startTime = 0s
*.U2.app[0].messageLength = 512Byte 
*.U2.app[0].packetName = "UDPdata"


*.GCS.numApps = 1
*.GCS.app[0].typename = "UdpSink"
*.GCS.app[0].localPort = 1000

*.U*.mobility.constraintAreaMinX = 0m
*.U*.mobility.constraintAreaMinY = 0m
*.U*.mobility.constraintAreaMinZ = 0m
*.U*.mobility.constraintAreaMaxX = 1200m
*.U*.mobility.constraintAreaMaxY = 1000m
*.U*.mobility.constraintAreaMaxZ = 0m 


[Config StationaryMobility]
*.*.mobility.typename = "StationaryMobility"

[Config MassMobility_5mps]
*.U**.mobility.typename = "MassMobility"
*.U**.mobility.changeInterval = 1s
*.U**.mobility.angleDelta = uniform(-10deg,10deg)
*.U**.mobility.speed = uniform(1mps,2mps)  
```

**Comment by maicuongtho** [comment]
for the case only one source node U1 send to GCS
![image](https://github.com/inet-framework/inet/assets/17454951/a6c50a5a-930d-4ea9-ba5b-f033f157ce08)

**Comment by levy** [comment]
Thanks for reporting this issue.

**Comment by maicuongtho** [comment]
thanks for help, this is my full simulation folder, 
[MoPhongGPSR.zip](https://github.com/inet-framework/inet/files/14766257/MoPhongGPSR.zip)

**Comment by rhornig** [comment]
I have edited the original post to include proper code block. FYI, use ` ``` ` (three back quites) to delimit a code block, both at the start and at the end. (or just select your code block and use the code toolbar button. github will do the rest.

**Comment by levy** [comment]
I was able to reproduce the incorrect behavior using the original INI file in the bug report and the network from the zip file. When only U1 or U2 sends packets then they reach GCS but when both send then U1 does not.

**Comment by levy** [comment]
You can workaround the issue by adding the following line to your INI file:

`**.arp.typename = "GlobalArp"`

This will disable ARP messages and fill in the ARP tables in the initialization stage of the simulation.

**Comment by levy** [comment]
This issue has nothing to do with GPSR. The reason the packets don't go through from U1 to GCS is related to ARP requests. The two applications send packets at the exact same moments, so the ARP requests are also sent at the exact same moments. This causes the U1 ARP requests to get lost due to interference, but U2 eventually goes through by chance. Of course, this can be avoided several ways: replace ARP with global ARP as suggested above, change the start time and send interval such that U1 and U2 don't send packets in sync, add jitter to ARP, etc.

**Comment by maicuongtho** [comment]
Many thanks for your help and clear explanation.
