### ISSUE TITLE
Packet size/datagram size less than 65,535 bytes but still gets fragmented. Why?

### ISSUE THREAD

**Issue by arahman33** [inet-framework/inet#970]
** Event #22  t=0.25  Backhaul.helio_666.ipv4.ip (Ipv4, id=205)  on UDPData-0 (inet::Packet, id=266)

INFO: Received (inet::Packet)UDPData-0 (7893 B) (inet::SequenceChunk) length = **7893** B from upper layer.
DETAIL: Sending datagram 'UDPData-0' with destination = 10.0.0.5
INFO: Routing (inet::Packet)UDPData-0 (7913 B) (inet::SequenceChunk) length = 7913 B with destination = 10.0.0.5, output interface = wlan0, next hop address = <unspec>
DETAIL: Breaking datagram into 2 fragments

The messageLength does not exceed 65,535 bytes. Then why is it getting fragmented?

attaching parts of the .ini file.

*.*.wlan[0].typename = "AckingWirelessInterface"
*.*.wlan[0].mac.useAck = false
*.*.wlan[0].mac.fullDuplex = false
*.*.wlan[0].radio.typename = "UnitDiskRadio"
*.*.wlan[0].radio.analogModel.typename = "UnitDiskAnalogModel"
*.helio_666.app[0].typename = "UdpBasicApp"
*.helio_666.app[0].localPort = 666
*.helio_666.app[0].messageLength = 7885B

Update: I changed the MTU from AckingWireless and it no longer gets fragmented.

**Comment by levy** [comment]
Fragmentation depends on the MTU size specified on the network interface.
