### ISSUE TITLE
Error and fix: "error: no member named 'ipprotocol' in 'inet::ProtocolGroup'" in the 4.5.2 INET version

### ISSUE THREAD

**Issue by rezapajhouhesh** [inet-framework/inet#975]
Hi, I use the INET 4.5.2 framework. In the following code:
`auto payloadProtocol = ProtocolGroup::ipprotocol.getProtocol(245);`
the compiler generate this error:

> error: no member named 'ipprotocol' in 'inet::ProtocolGroup'

In the list of changes log, there is no explanation about it. Please explain, instead of the above command, what command should I write that is compatible with the 4.5.2 INET version and does the same thing.
Thanks in advance

**Comment by levy** [comment]
I'm not sure why you would do this but you can use ProtocolGroup::getIpProtocolGroup() instead.
