### ISSUE TITLE
outgoingPacketLengths:histogram shows some small wrong details

### ISSUE THREAD

**Issue by marsluca** [inet-framework/inet#980]
In the module `ClientServer.client.eth[0].queue`, I noticed that `outgoingPacketLengths:histogram` shows some small wrong details. This is the result:

```
Experiment	Measurement	Replication	Module	Name	Kind	Count	SumWeights	Mean	StdDev	Variance	#Bins	Hist. Range	
General		#0	ClientServer.client.eth[0].queue	outgoingPacketLengths:histogram	h	66	-	**11,612.121212 b**	**2,456.080076 b**	6,032,329.338928 b²	76	0 .. 15,200 b	
General		#0	ClientServer.server.eth[0].queue	outgoingPacketLengths:histogram	h	64	-	463 b	12.709202 b	161.523810 b²	96	336 .. 528 b	
```
![image](https://github.com/inet-framework/inet/assets/34103646/b751799d-a295-4e8d-8839-39e3736bb34b)
- The histogram range should not be measured in bits
- The variance is not present for the client

[server.csv](https://github.com/inet-framework/inet/files/15442214/server.csv)
[client.csv](https://github.com/inet-framework/inet/files/15442215/client.csv)

My omnet.ini:
```
[General]
network = ClientServer
sim-time-limit = 5s

**.client.numApps = 1
**.client.app[*].typename = "TcpSessionApp"
**.client.app[0].active = true
**.client.app[0].localPort = -1
**.client.app[0].connectAddress = "server"
**.client.app[0].connectPort = 1000
**.client.app[0].tOpen = 0.2s
**.client.app[0].tSend = 0.4s
**.client.app[0].sendBytes = 1MiB
**.client.app[0].dataTransferMode = "bytestream"
**.client.app[0].sendScript = ""
**.client.app[0].tClose = 0s

**.server.numApps = 1
**.server.app[*].typename = "TcpSinkApp"
**.server.app[0].localAddress = ""
**.server.app[0].localPort = 1000

**.ppp[*].queue.typename = "PacketQueue" # in routers

**.tcp.tcpAlgorithmClass = "TcpReno"
**.tcp.mss = 1460
```

My network:
```
import inet.networklayer.configurator.ipv4.Ipv4NetworkConfigurator;
import inet.node.inet.StandardHost;
//import inet.node.inet.Router;
import inet.node.ethernet.EthernetHub;
import inet.node.ethernet.Eth10G;
import ned.DatarateChannel;

network ClientServer
{
    @display("bgb=1098,534");
    submodules:
        client: StandardHost {
            @display("p=89.5375,93.67");
        }
        server: StandardHost {
            @display("p=1044,454");
        }
        configurator: Ipv4NetworkConfigurator;
        router: EthernetHub {
            @display("p=89.5375,356.7725");
        }
        router1: EthernetHub {
            @display("p=699.77,137.75");
        }
    connections:
        client.ethg++ <--> Eth10G <--> router.ethg++;
        router.ethg++ <--> Eth10G <--> router1.ethg++;
        router1.ethg++ <--> Eth10G <--> server.ethg++;
}
```

**Comment by levy** [comment]
1. The histogram range is correctly measured in the same unit as the statistic value, I think this **isn't** a bug.
2. The exported CSV file doesn't contain all columns that are shown in the browse data page. I think this **is** a bug.

**Comment by levy** [comment]
1: I don't know why do you think that the histogram range should not be measured in bits when the statistic value is itself measured in bits. I disagree with your statement.

2: the '#' characters are displayed in the variance column for the client because the value doesn't fit into the space available. If you increase the column width then it will display the value correctly.

I close this issue because there's nothing to fix here.
