### ISSUE TITLE
IPv4 tunneling is bit rotten

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#99]
reassembleAndDelivered() contains this code:

```
    // tunnelled IP packets are handled separately
    send(packet, "preRoutingOut");
```

However there is no "preRoutingOut" gate in the IPv4 module.

from: http://dev.omnetpp.org/bugs/view.php?id=462

**Comment by rhornig** [comment]
#130 and the related changes will allow much cleaner tunneling implementation.

**Comment by levy** [comment]
This bug is obsolete. There's an IPv4 tunnel example which works in a clean way.
