### ISSUE TITLE
Meet problem like "Invalid value "21 BK 80 BE 4000 VI 5000 VO", should be one of: """

### ISSUE THREAD

**Issue by Andy-Lorre** [inet-framework/inet#990]
when I have finished installing Inet, I meet the problem like blow:
<img width="921" alt="截屏2024-08-27 01 45 31" src="https://github.com/user-attachments/assets/e0ae8537-0f1d-406a-bd27-2dfa70c5fea6">

Is there something that I missed?

**Comment by levy** [comment]
The @enum should not be there with the latest omnetpp because it validates the default value. How did the @enum get there?

**Comment by levy** [comment]
This has been fixed in INET master.
