### ISSUE TITLE
hasStatus=true fails with error "Enum "inet::NodeStatus" not found" in 4.5.3 (works in 4.5.1).

### ISSUE THREAD

**Issue by v44r** [inet-framework/inet#995]
For example, launching examples/aodv:

Enum "inet::NodeStatus" not found -- its declaration may be missing from .msg files, or the code was not linked in -- in module (inet::NodeStatus) AODVNetwork.host[0].status (id=31), during network initialization

Same with other examples with hasStatus=true (dhcp -> RebotingDHCP, etc).

**Comment by MiniDudi** [comment]
same problem
