### ISSUE TITLE
GateControlList parameters are mutable but handleParameterChange is not implemented

### ISSUE THREAD

**Issue by haug-den-lucas** [inet-framework/inet#996]
As stated in the title, the parameters of a GateControlList are marked as `@mutable`  which suggests that these parameters can be changed during runtime:

https://github.com/inet-framework/inet/blob/ce08305b86ddff9534e870ccd1aa913553d50c56/src/inet/queueing/gate/GateControlList.ned#L17-L18

However, parameter changes are ignored, so either:
- The parameters should not be marked as mutable
- handleParameterChange should be implemented

**Comment by ZoltanBojthe** [comment]
Removed the @mutable property in master branch.
